// angular/demo/bootstrap/src/app/samples/resizeObserver/resizeObserver.route.ts
import {AgnosUIAngularModule, createResizeObserver, toAngularSignal} from '@agnos-ui/angular-bootstrap';
import {UseDirective} from '@agnos-ui/angular-headless';
import {Component, computed, signal} from '@angular/core';

@Component({
	imports: [UseDirective, AgnosUIAngularModule],
	template: `
		<div class="demo-resize-observer">
			<label for="resizable">Resizable textarea:</label>
			<textarea
				[auUse]="resizeDirective"
				name="resizable"
				id="resizable"
				rows="6"
				cols="50"
				class="form-control"
				[class.fontsize]="observedHeight$() && observedHeight$()! > 200"
				[style.height.px]="heightValue()"
			>
This simple example is using the resizeObserver feature from @agnos-ui/core and displays the height of the textarea below it.
Modify the height to more than 200 px and see the font size changing.
	</textarea
			>
			<div>
				Textarea content height: <span id="dynamic-height">{{ observedHeight$() }}</span
				>px
			</div>
			<button type="button" class="btn btn-primary m-2" id="decreaseHeight" (click)="decreaseHeight()">Height --</button>
			<button type="button" class="btn btn-primary m-2" id="increaseHeight" (click)="increaseHeight()">Height ++</button>
		</div>
	`,
	styles: "@use '@agnos-ui/common/samples/resizeobserver/resizeobserver.scss';",
})
export default class ResizeObserverComponent {
	readonly heightValue = signal(180);

	readonly resizeObserver = createResizeObserver();

	readonly resizeDirective = this.resizeObserver.directive;

	readonly dimensions$ = toAngularSignal(this.resizeObserver.dimensions$);

	readonly observedHeight$ = computed(() => this.dimensions$()?.contentRect?.height);

	increaseHeight() {
		this.heightValue.set((this.observedHeight$() || 0) + 50);
	}

	decreaseHeight() {
		this.heightValue.set(this.observedHeight$() ? this.observedHeight$()! - 50 : 0);
	}
}

// svelte/demo/src/bootstrap/samples/resizeObserver/ResizeObserver.route.svelte
<script lang="ts">
	import '@agnos-ui/common/samples/resizeobserver/resizeobserver.scss';
	import {createResizeObserver} from '@agnos-ui/svelte-bootstrap/services/resizeObserver';

	const {dimensions$, directive: resizeDirective} = createResizeObserver();
	$: observedHeight$ = $dimensions$?.contentRect?.height;

	let heightValue = 180;

	function increaseHeight() {
		heightValue = (observedHeight$ || 0) + 50;
	}

	function decreaseHeight() {
		heightValue = observedHeight$ ? observedHeight$ - 50 : 0;
	}
</script>

<div class="demo-resize-observer">
	<label for="resizable">Resizable textarea:</label>
	<textarea
		use:resizeDirective
		name="resizable"
		id="resizable"
		rows="6"
		cols="50"
		class="form-control"
		class:fontsize={observedHeight$ && observedHeight$ > 200}
		style:height={heightValue + 'px'}
		value="This simple example is using the resizeObserver feature from @agnos-ui/core and displays the height of the textarea below it.
Modify the height to more than 200 px and see the font size changing."
	/>
	<div>Textarea content height: <span id="dynamic-height">{observedHeight$}</span>px</div>
	<button type="button" class="btn btn-primary m-2" id="decreaseHeight" on:click={decreaseHeight}>Height --</button>
	<button type="button" class="btn btn-primary m-2" id="increaseHeight" on:click={increaseHeight}>Height ++</button>
</div>
