// angular/ssr-app/src/app/app.component.ts
import {Component} from '@angular/core';
import {AgnosUIAngularModule, type TreeItem} from '@agnos-ui/angular-bootstrap';

@Component({
	selector: 'app-root',
	imports: [AgnosUIAngularModule],
	templateUrl: './app.component.html',
})
export class AppComponent {
	readonly nodes: TreeItem[] = [
		{
			label: 'Node 1',
			isExpanded: true,
			children: [
				{
					label: 'Node 1.1',
					children: [
						{
							label: 'Node 1.1.1',
						},
					],
				},
				{
					label: 'Node 1.2',
					children: [
						{
							label: 'Node 1.2.1',
						},
					],
				},
			],
		},
	];
	readonly photos = [944, 1011, 984].map((n) => ({id: `carousel-photo-${n}`, src: `https://picsum.photos/id/${n}/900/500`}));
}

<div class="container">
	<h1>SSR Test</h1>
	<h2>Accordion</h2>
	<div class="my-3">
		<div auAccordion>
			<div auAccordionItem auHeader="First" auVisible>Content 1</div>
			<div auAccordionItem auHeader="Second">Content 2</div>
			<div auAccordionItem auHeader="Disabled" auDisabled>Content 3</div>
		</div>
	</div>
	<h2>Alert</h2>
	<div class="my-3">
		<au-component auAlert>This is an alert!</au-component>
	</div>
	<h2>Carousel</h2>
	<div class="my-3">
		<div auCarousel [auSlidesData]="photos">
			<ng-template auCarouselSlide let-src="src">
				<img class="w-100" alt="random picsum" [src]="src" />
			</ng-template>
		</div>
	</div>
	<h2>Modal</h2>
	<div>
		<au-component auModal>This is a modal!</au-component>
	</div>
	<h2>Pagination</h2>
	<div class="my-3">
		<nav auPagination auCollectionSize="60"></nav>
	</div>
	<h2>Progressbar</h2>
	<div class="my-3">
		<div auProgressbar auValue="20"></div>
	</div>
	<h2>Rating</h2>
	<div class="my-3">
		<div [auRating]></div>
	</div>
	<h2>Select</h2>
	<div class="my-3">
		<div auSelect [auItems]="['AgnosUI']"></div>
	</div>
	<h2>Slider</h2>
	<div class="my-3">
		<div auSlider [auValues]="[50]"></div>
	</div>
	<h2>Toast</h2>
	<div class="my-3">
		<au-component auToast>This is a toast!</au-component>
	</div>
	<h2>Tree</h2>
	<div class="my-3">
		<au-component auTree [auNodes]="nodes" />
	</div>
	<h2>Drawer</h2>
	<div class="my-3">
		<au-component auDrawer />
	</div>
	<!-- [content-placeholder] -->
</div>

// react/ssr-app/src/App.tsx
import {Accordion, AccordionItem} from '@agnos-ui/react-bootstrap/components/accordion';
import {Alert} from '@agnos-ui/react-bootstrap/components/alert';
import {Carousel} from '@agnos-ui/react-bootstrap/components/carousel';
import {Modal} from '@agnos-ui/react-bootstrap/components/modal';
import {Pagination} from '@agnos-ui/react-bootstrap/components/pagination';
import {Progressbar} from '@agnos-ui/react-bootstrap/components/progressbar';
import {Rating} from '@agnos-ui/react-bootstrap/components/rating';
import {Select} from '@agnos-ui/react-bootstrap/components/select';
import {Slider} from '@agnos-ui/react-bootstrap/components/slider';
import {Toast} from '@agnos-ui/react-bootstrap/components/toast';
import {Tree, type TreeItem} from '@agnos-ui/react-bootstrap/components/tree';
// [import-placeholder]

const nodes: TreeItem[] = [
	{
		label: 'Node 1',
		isExpanded: true,
		children: [
			{
				label: 'Node 1.1',
				children: [
					{
						label: 'Node 1.1.1',
					},
				],
			},
			{
				label: 'Node 1.2',
				children: [
					{
						label: 'Node 1.2.1',
					},
				],
			},
		],
	},
];
const photos = [944, 1011, 984].map((n) => ({id: `carousel-photo-${n}`, src: `https://picsum.photos/id/${n}/900/500`}));

export const App = () => (
	<div className="container">
		<h1>SSR Test</h1>
		<h2>Accordion</h2>
		<div className="my-3">
			<Accordion>
				<AccordionItem visible header="First">
					Content 1
				</AccordionItem>
				<AccordionItem header="Second">Content 2</AccordionItem>
				<AccordionItem disabled header="Disabled">
					Content 3
				</AccordionItem>
			</Accordion>
		</div>
		<h2>Alert</h2>
		<div className="my-3">
			<Alert>This is an alert!</Alert>
		</div>
		<h2>Carousel</h2>
		<div className="my-3">
			<Carousel slidesData={photos} slide={({src}) => <img className="w-100" alt="random picsum" src={src} />} />
		</div>
		<h2>Modal</h2>
		<div>
			<Modal>This is a modal!</Modal>
		</div>
		<h2>Pagination</h2>
		<div className="my-3">
			<Pagination collectionSize={60} />
		</div>
		<h2>Progressbar</h2>
		<div className="my-3">
			<Progressbar value={20} />
		</div>
		<h2>Rating</h2>
		<div className="my-3">
			<Rating />
		</div>
		<h2>Select</h2>
		<div className="my-3">
			<Select items={['AgnosUI']} />
		</div>
		<h2>Slider</h2>
		<div className="my-3">
			<Slider values={[50]} />
		</div>
		<h2>Toast</h2>
		<div className="my-3">
			<Toast>This is a toast!</Toast>
		</div>
		<h2>Tree</h2>
		<div className="my-3">
			<Tree nodes={nodes} />
		</div>
		{/* [content-placeholder] */}
	</div>
);
