// angular/demo/daisyui/src/app/samples/collapse/collapse.component.ts
import {createSimpleClassTransition, createTransition, UseDirective} from '@agnos-ui/angular-headless';
import {Component, input, output} from '@angular/core';
/**
 * You can create easily your own collapse component with the help of the `createTransition` function
 * you will be able to plug the transition event of DaisyUI to your component.
 * The `createSimpleClassTransition` is a helper to create a transition that will add a class to the element but you don't have to add classes as this
 * DaisyUI CSS is not using this feature.
 */
@Component({
	selector: 'app-collapse',
	imports: [UseDirective],
	template: `
		<div
			tabindex="0"
			class="collapse collapse-arrow bg-base-100 border border-base-300"
			[auUse]="transition.directives.directive"
			(blur)="transition.api.hide()"
			(focus)="transition.api.show()"
		>
			<div class="collapse-title font-semibold">{{ title() }}</div>
			<div class="collapse-content"><ng-content /></div>
		</div>
	`,
})
export class CollapseDaisyComponent {
	readonly title = input('Focus me to see content');

	// The advantage of AgnosUI here is that it plug the transition state to some possible callbacks
	readonly shown = output();
	readonly hidden = output();

	transition = createTransition({
		props: {
			visible: false, // could be something in an input that also add the collapse-open class
			transition: createSimpleClassTransition({}),
			onShown: () => this.shown.emit(),
			onHidden: () => this.hidden.emit(),
		},
	});
}

// react/demo/src/daisyui/samples/collapse/Collapse.tsx
import {createTransition} from '@agnos-ui/react-headless/services/transitions/baseTransitions';
import {createSimpleClassTransition} from '@agnos-ui/react-headless/services/transitions/simpleClassTransition';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import type {PropsWithChildren} from 'react';
/**
 * You can create easily your own collapse component with the help of the `createTransition` function
 * you will be able to plug the transition event of DaisyUI to your component.
 * The `createSimpleClassTransition` is a helper to create a transition that will add a class to the element but you don't have to add classes as this
 * DaisyUI CSS is not using this feature.
 */
export const Collapse = (props: PropsWithChildren<Partial<{title: string; onHidden: () => void; onShown: () => void}>>) => {
	const transition = createTransition({
		props: {
			visible: false, // could be something in an input that also add the collapse-open class
			transition: createSimpleClassTransition({}),
			onShown: () => props.onShown?.(),
			onHidden: () => props.onHidden?.(),
		},
	});

	return (
		<>
			<div
				tabIndex={0}
				className="collapse collapse-arrow bg-base-100 border border-base-300"
				{...useDirective(transition.directives.directive)}
				onBlur={() => transition.api.hide()}
				onFocus={() => transition.api.show()}
			>
				<div className="collapse-title font-semibold">{props.title ?? 'Focus me to see content'}</div>
				<div className="collapse-content">{props.children}</div>
			</div>
		</>
	);
};
