// react/demo/src/app/samples/rating/Form.route.tsx
import {Rating} from '@agnos-ui/react/components/rating';
import {useState} from 'react';

interface CtrlState {
	value: number;
	valid: boolean;
	invalid: boolean;
	disabled: boolean;
}

const RatingDemo = () => {
	const [ctrl, setCtrl] = useState({value: 0, valid: false, invalid: true, disabled: false} as CtrlState);
	function updateCtrl(values: Partial<CtrlState>) {
		const value = values.value ?? ctrl.value;
		const enabled = !(values.disabled ?? ctrl.disabled);
		const isValid = value >= 1;
		const newCtrl = {...ctrl, ...values, value, valid: enabled && isValid, invalid: enabled && !isValid};
		setCtrl(newCtrl);
	}

	return (
		<>
			<label className="form-label" id="ratingLabel">
				Rating of your experience
			</label>
			<br />
			<Rating rating={ctrl.value} disabled={ctrl.disabled} onRatingChange={(value) => updateCtrl({value})} ariaLabelledBy="ratingLabel" />
			<div id="form-msg" className="form-text small">
				{ctrl.valid && <div className="text-success">Thanks!</div>}
				{ctrl.invalid && <div className="text-danger-emphasis">Please rate us</div>}
			</div>
			<pre>
				Model:{' '}
				<span id="form-model">
					<b>{ctrl.value}</b>
				</span>
			</pre>
			<button
				id="form-btn-enable"
				className={`btn btn-sm btn-outline-${ctrl.disabled ? 'danger' : 'success'} me-2`}
				onClick={() => updateCtrl({disabled: !ctrl.disabled})}
			>
				{ctrl.disabled ? 'control disabled' : ' control enabled'}
			</button>
			&nbsp;
			<button id="form-btn-clear" className="btn btn-sm btn-outline-primary me-2" onClick={() => updateCtrl({value: 0})}>
				Clear
			</button>
		</>
	);
};
export default RatingDemo;

// svelte/demo/src/app/samples/rating/Form.route.svelte
<script lang="ts">
	import {Rating} from '@agnos-ui/svelte/components/rating';

	let ctrl = {value: 0, valid: false, invalid: true, disabled: false};
	$: {
		const isValid = ctrl.value >= 1;
		const enabled = !ctrl.disabled;
		ctrl = Object.assign(ctrl, {valid: enabled && isValid, invalid: enabled && !isValid});
	}
</script>

<!-- svelte-ignore a11y-label-has-associated-control -->
<label class="form-label" id="ratingLabel">Rating of your experience</label><br />
<Rating bind:rating={ctrl.value} disabled={ctrl.disabled} ariaLabelledBy="ratingLabel" />
<div id="form-msg" class="form-text small">
	{#if ctrl.valid}
		<div class="text-success">Thanks!</div>
	{/if}
	{#if ctrl.invalid}
		<div class="text-danger-emphasis">Please rate us</div>
	{/if}
</div>
<pre>Model: <span id="form-model"><b>{ctrl.value}</b></span></pre>
<button
	id="form-btn-enable"
	class="btn btn-sm btn-outline-{ctrl.disabled ? 'danger' : 'success'} me-2"
	on:click={() => (ctrl.disabled = !ctrl.disabled)}
>
	{ctrl.disabled ? 'control disabled' : ' control enabled'}
</button>
<button id="form-btn-clear" class="btn btn-sm btn-outline-primary me-2" on:click={() => (ctrl.value = 0)}>Clear</button>
