// react/demo/src/bootstrap/samples/rating/Readonly.route.tsx
import '@agnos-ui/common/samples/rating/readonly.scss';
import type {StarContext} from '@agnos-ui/react-bootstrap/components/rating';
import {Rating} from '@agnos-ui/react-bootstrap/components/rating';
import HeartFill from 'bootstrap-icons/icons/heart-fill.svg?react';

const RatingDemo = () => (
	<Rating
		rating={3.64}
		readonly={true}
		maxRating={5}
		className="rating-readonly"
		star={({fill}: StarContext) => {
			const starClassname = ['star'];
			if (fill === 100) {
				starClassname.push('full');
			}
			const styles = {
				width: `${fill}%`,
			};
			return (
				<span className={starClassname.join(' ')}>
					<span className="half" style={styles}>
						<HeartFill />
					</span>
					<span>
						<HeartFill />
					</span>
				</span>
			);
		}}
		ariaLabel="readonly rating"
	/>
);
export default RatingDemo;

// svelte/demo/src/app/samples/rating/Readonly.route.svelte
<script lang="ts">
	import {Rating} from '@agnos-ui/svelte/components/rating';
	import heartFill from 'bootstrap-icons/icons/heart-fill.svg?raw';
	import '@agnos-ui/common/samples/rating/readonly.scss';
</script>

<Rating className="rating-readonly" rating={3.64} readonly={true} maxRating={5} ariaLabel="readonly rating">
	<span slot="star" let:fill let:index class="star" class:full={fill === 100}>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		<span class="half" style:width={fill + '%'}>{@html heartFill}</span>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		<span>{@html heartFill}</span>
	</span>
</Rating>
