// angular/demo/bootstrap/src/app/samples/pagination/hash.route.ts
import {AgnosUIAngularModule, toAngularSignal} from '@agnos-ui/angular-bootstrap';
import {hash$} from '@agnos-ui/common/samples/utils/hashUtil';
import {Component, computed} from '@angular/core';
@Component({
	imports: [AgnosUIAngularModule],
	template: `
		<p>A pagination with hrefs provided for each pagination element:</p>
		<p>
			Page hash: <small>{{ '#' + hash() }}</small>
		</p>
		<nav
			auPagination
			auCollectionSize="60"
			auBoundaryLinks="true"
			[auPage]="pageNumber()"
			[auPageLink]="pageLink"
			(auPageChange)="pageChange($event)"
			auAriaLabel="Page navigation with customized hrefs"
		></nav>
	`,
})
export default class HashPaginationComponent {
	hash = toAngularSignal(hash$);

	pageNumber = computed(() => +(this.hash().split('#')[1] ?? 4));

	pageLink = (currentPage: number) => `#${this.hash().split('#')[0]}#${currentPage}`;

	pageChange = (currentPage: number) => (location.hash = `#${this.hash().split('#')[0]}#${currentPage}`);
}

// svelte/demo/src/bootstrap/samples/pagination/Hash.route.svelte
<script lang="ts">
	import {Pagination} from '@agnos-ui/svelte-bootstrap/components/pagination';

	import {hash$} from '@agnos-ui/common/samples/utils/hashUtil';

	$: page = +($hash$.split('#')[1] ?? 4);

	const pageLink = (currentPage: number) => `#${$hash$.split('#')[0]}#${currentPage}`;

	const pageChange = (pageNumber: number) => (location.hash = `#${$hash$.split('#')[0]}#${pageNumber}`);
</script>

<p>A pagination with hrefs provided for each pagination element:</p>
<p>
	Page hash: <small>{'#' + $hash$}</small>
</p>
<Pagination {page} collectionSize={60} boundaryLinks ariaLabel="Page navigation with customized hrefs" {pageLink} onPageChange={pageChange}
></Pagination>
