// svelte/demo/App.svelte
<script lang="ts">
	import {computed} from '@amadeus-it-group/tansu';
	import {hash$} from '@agnos-ui/common/utils';

	import 'bootstrap/dist/css/bootstrap.css';
	import '@agnos-ui/common/demo.scss';
	import '@agnos-ui/common/samples/links.scss';
	import Lazy from './Lazy.svelte';

	const componentRegExp = /samples\/([^/]*)\/([^/]*).route.svelte/;
	function replacePattern(components: Record<string, any>) {
		const directComponents: Record<string, any> = {};
		for (const [key, component] of Object.entries(components)) {
			const matches = key.match(componentRegExp);
			if (matches) {
				directComponents[`/${matches[1]}/${matches[2]}`.toLowerCase()] = component;
			}
		}
		return directComponents;
	}
	const components = replacePattern(import.meta.glob('./samples/*/*.route.svelte'));

	const component$ = computed(() => {
		const hash = hash$();
		return hash
			? async () => {
					const componentLoader = components[hash.split('#')[0].split('?')[0]];
					if (componentLoader) {
						const component = await componentLoader();
						if (window.parent) {
							window.parent.postMessage({type: 'sampleload'});
						}
						return component;
					} else {
						return import('./Page404.svelte');
					}
			  }
			: undefined;
	});
</script>

<div class="container p-3">
	{#if $component$}
		<Lazy component={$component$} />
	{:else}
		<h3>Samples:</h3>
		<div class="sample-links">
			{#each Object.keys(components) as url}
				<div><a href={'#' + url}>{url}</a></div>
			{/each}
		</div>
	{/if}
</div>

// react/demo/src/common/App.tsx
import {Outlet, RouterProvider, createHashRouter} from 'react-router-dom';

import '@agnos-ui/common/demo.scss';
import '@agnos-ui/common/samples/links.scss';

const App = (props: {components: Record<string, any>}) => {
	const componentRegExp = /samples\/([^/]*)\/([^/]*).route.tsx/;
	function replacePattern(components: Record<string, any>) {
		const directComponents: Record<string, any> = {};
		for (const [key, component] of Object.entries(components)) {
			const matches = key.match(componentRegExp);
			if (matches) {
				directComponents[`${matches[1]}/${matches[2]}`.toLowerCase()] = component;
			}
		}
		return directComponents;
	}
	const components = replacePattern(props.components);
	const lazyLinks = async () => {
		const Links = (await import('../common/Links')).default;
		return {
			Component: () => Links({links: Object.keys(components)}),
		};
	};

	const router = createHashRouter([
		{
			path: '/',
			lazy: lazyLinks,
		},
		{
			path: '*',
			element: <Outlet />,
			children: [
				{path: '', lazy: lazyLinks},
				...Object.entries(components).map(([path, component]) => ({
					path,
					lazy: async () => {
						const Component = await component();
						if (window.parent) {
							window.parent.postMessage({type: 'sampleload'});
						}
						return {Component};
					},
				})),
				{
					path: '*',
					lazy: async () => ({Component: ((await import('../common/Page404')) as any).default}),
				},
			],
		},
	]);
	return <RouterProvider router={router} />;
};

export default App;
