// svelte/lib/src/select/Select.svelte
<script lang="ts" context="module">
	import type {SelectProps as Props, SelectWidget, SelectSlots as Slots} from '@agnos-ui/svelte-headless';
	import {Slot, callWidgetFactory, createSelect} from '@agnos-ui/svelte-headless';
</script>

<script lang="ts">
	type Item = $$Generic; // eslint-disable-line no-undef
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props<Item>>; // eslint-disable-line @typescript-eslint/no-unused-vars
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Slots = Slots<Item>; // eslint-disable-line @typescript-eslint/no-unused-vars

	export let open: boolean | undefined = false;
	export let filterText: string | undefined = undefined;
	export let selected: Item[] | undefined = undefined;

	const widget = callWidgetFactory<SelectWidget<Item>>({
		factory: createSelect,
		widgetName: 'select',
		$$slots,
		events: {
			onOpenChange: function (isOpen: boolean): void {
				open = isOpen;
			},
			onSelectedChange: (newSelection) => {
				selected = newSelection;
			},
			onFilterTextChange: (value) => {
				filterText = value;
			},
		},
	});
	const {
		stores: {
			id$,
			ariaLabel$,
			badgeClassName$,
			className$,
			filterText$,
			highlighted$,
			menuClassName$,
			menuItemClassName$,
			open$,
			placement$,
			selectedContexts$,
			slotBadgeLabel$,
			slotItem$,
			visibleItems$,
		},
		state$,
		actions: {onInputKeydown, onInput},
		directives: {floatingDirective, hasFocusDirective, referenceDirective},
	} = widget;
	$: widget.patchChangedProps($$props);
</script>

<div use:referenceDirective class="au-select dropdown border border-1 p-1 mb-3 d-block {$className$}">
	<!-- svelte-ignore a11y-role-has-required-aria-props -->
	<div use:hasFocusDirective role="combobox" class="d-flex align-items-center flex-wrap" aria-haspopup="listbox" aria-expanded={$open$}>
		{#each $selectedContexts$ as itemContext (itemContext.id)}
			<div class={`au-select-badge me-1 ${$badgeClassName$}`}>
				<Slot slotContent={$slotBadgeLabel$} props={{state: $state$, widget, itemContext}} let:component let:props>
					<slot slot="slot" name="badgeLabel" let:props {...props} />
					<svelte:component this={component} {...props}>
						<slot name="badgeLabel" slot="badgeLabel" let:itemContext let:state let:widget {itemContext} {state} {widget} />
						<slot name="item" slot="item" let:itemContext let:state let:widget {itemContext} {state} {widget} />
					</svelte:component>
				</Slot>
			</div>
		{/each}
		<input
			id={$id$}
			aria-label={$ariaLabel$}
			type="text"
			class="au-select-input flex-grow-1 border-0"
			value={$filterText$}
			aria-autocomplete="list"
			autoCorrect="off"
			autoCapitalize="none"
			autoComplete="off"
			on:keydown={onInputKeydown}
			on:input={onInput}
		/>
	</div>
	{#if $open$ && $visibleItems$.length > 0}
		<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
		<ul
			use:hasFocusDirective
			use:floatingDirective
			class="dropdown-menu show {$menuClassName$}"
			data-popper-placement={$placement$}
			on:mousedown|preventDefault
		>
			{#each $visibleItems$ as itemContext (itemContext.id)}
				<!-- svelte-ignore a11y-click-events-have-key-events -->
				<li
					class={`au-select-item dropdown-item position-relative ${$menuItemClassName$}`}
					class:bg-light={itemContext === $highlighted$}
					class:selected={itemContext.selected}
					on:click={() => widget.api.toggleItem(itemContext.item)}
				>
					<Slot slotContent={$slotItem$} props={{state: $state$, widget, itemContext}} let:component let:props>
						<slot slot="slot" name="item" let:props {...props} />
						<svelte:component this={component} {...props}>
							<slot name="badgeLabel" slot="badgeLabel" let:itemContext let:state let:widget {itemContext} {state} {widget} />
							<slot name="item" slot="item" let:itemContext let:state let:widget {itemContext} {state} {widget} />
						</svelte:component>
					</Slot>
				</li>
			{/each}
		</ul>
	{/if}
</div>

// react/lib/src/Select.tsx
import type {SelectContext, SelectItemContext, SelectProps, SelectWidget} from '@agnos-ui/react-headless';
import {Slot, createSelect, toSlotContextWidget, useDirective, useDirectives, useWidgetWithConfig} from '@agnos-ui/react-headless';
import type {SyntheticEvent} from 'react';

function preventDefault(e: SyntheticEvent) {
	e.preventDefault();
}

function DefaultBadge<Item>(slotContext: SelectItemContext<Item>) {
	return <>{'' + slotContext.itemContext.item}</>;
}

function DefaultItem<Item>(slotContext: SelectItemContext<Item>) {
	return <>{'' + slotContext.itemContext.item}</>;
}

function Badges<Item>({slotContext}: {slotContext: SelectContext<Item>}) {
	const badges = [];
	const state = slotContext.state;
	for (const itemContext of slotContext.state.selectedContexts) {
		badges.push(
			<div key={itemContext.id} className={`au-select-badge me-1 ${state.badgeClassName}`}>
				<Slot slotContent={state.slotBadgeLabel} props={{...slotContext, itemContext}}></Slot>
			</div>,
		);
	}

	return badges.length ? <>{badges}</> : null;
}

function Rows<Item>({slotContext}: {slotContext: SelectContext<Item>}) {
	const {widget, state} = slotContext;
	const highlighted = state.highlighted;
	return (
		<>
			{state.visibleItems.map((itemContext) => {
				const {id} = itemContext;
				const classname = ['au-select-item dropdown-item position-relative'];
				if (itemContext === highlighted) {
					classname.push('bg-light');
				}
				if (itemContext.selected) {
					classname.push('selected');
				}
				return (
					<li key={id} className={classname.join(' ')} onClick={() => widget.api.toggleItem(itemContext.item)}>
						<Slot slotContent={state.slotItem} props={{...slotContext, itemContext}}></Slot>
					</li>
				);
			})}
		</>
	);
}

const defaultConfig: Partial<SelectProps<any>> = {
	slotBadgeLabel: DefaultBadge,
	slotItem: DefaultItem,
};

export function Select<Item>(props: Partial<SelectProps<Item>>) {
	const [state, widget] = useWidgetWithConfig<SelectWidget<Item>>(createSelect, props, 'select', defaultConfig);
	const slotContext: SelectContext<Item> = {state, widget: toSlotContextWidget(widget)};
	const {id, ariaLabel, visibleItems, filterText, open, className, menuClassName, placement} = state;

	const {
		directives: {floatingDirective, hasFocusDirective, referenceDirective},
	} = widget;
	const refSetContainer = useDirective(referenceDirective);
	const refSetInput = useDirective(hasFocusDirective);
	const refSetMenu = useDirectives([hasFocusDirective, floatingDirective]);
	return (
		<div ref={refSetContainer} className={`au-select dropdown border border-1 p-1 mb-3 d-block ${className}`}>
			<div ref={refSetInput} role="combobox" className="d-flex align-items-center flex-wrap" aria-haspopup="listbox" aria-expanded={open}>
				<Badges slotContext={slotContext}></Badges>
				<input
					id={id}
					aria-label={ariaLabel}
					className="au-select-input flex-grow-1 border-0"
					type="text"
					value={filterText}
					aria-autocomplete="list"
					autoCorrect="off"
					autoCapitalize="none"
					autoComplete="off"
					onKeyDown={widget.actions.onInputKeydown}
					onInput={widget.actions.onInput}
				/>
			</div>
			{open && visibleItems.length > 0 && (
				<ul ref={refSetMenu} className={`dropdown-menu show ${menuClassName}`} data-popper-placement={placement} onMouseDown={preventDefault}>
					<Rows slotContext={slotContext}></Rows>
				</ul>
			)}
		</div>
	);
}
