// svelte/lib/src/components/pagination/Pagination.svelte
<script lang="ts" context="module">
	import type {PaginationProps as Props, PaginationSlots as Slots} from '@agnos-ui/svelte-headless/components/pagination';
	import {createPagination} from '@agnos-ui/svelte-headless/components/pagination';
	import {toSlotContextWidget} from '@agnos-ui/svelte-headless/types';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	import PaginationDefaultPages from './PaginationDefaultPages.svelte';

	const defaultConfig: Partial<Props> = {
		slotPages: PaginationDefaultPages,
	};
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Slots = Slots; // eslint-disable-line @typescript-eslint/no-unused-vars

	/**
	 *  The current page.
	 *
	 *  Page numbers start with `1`.
	 */
	export let page: Props['page'] | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createPagination,
		widgetName: 'pagination',
		$$slots,
		defaultConfig,
		events: {
			onPageChange: (value: number) => {
				page = value;
			},
		},
	});

	const {
		stores: {
			size$,
			page$,
			boundaryLinks$,
			directionLinks$,
			nextDisabled$,
			previousDisabled$,
			ariaLabel$,
			ariaFirstLabel$,
			ariaPreviousLabel$,
			ariaNextLabel$,
			ariaLastLabel$,
			className$,
			slotFirst$,
			slotPrevious$,
			slotNext$,
			slotLast$,
			slotPages$,
		},
		state$,
		actions: {first, previous, next, last},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);

	$: sizeClass = $size$ ? `pagination-${$size$}` : ''; // $size$ === 'sm' ? 'pagination-sm' : $size$ === 'lg' ? 'pagination-lg' : '';
	$: slotContext = {widget: toSlotContextWidget(widget), state: $state$};
</script>

<!-- Should we put nav here ? how to custom the class of ul in this case ?-->
<nav aria-label={$ariaLabel$}>
	<ul class="au-pagination pagination {sizeClass} {$className$}">
		{#if $boundaryLinks$}
			<li class="page-item" class:disabled={$previousDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaFirstLabel$}
					class="page-link au-first"
					href="#"
					on:click|preventDefault={() => first()}
					tabindex={$previousDisabled$ ? -1 : undefined}
					aria-disabled={$previousDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotFirst$} props={slotContext} let:component let:props>
							<slot slot="slot" name="first" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		{#if $directionLinks$}
			<li class="page-item" class:disabled={$previousDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaPreviousLabel$}
					class="page-link au-previous"
					href="#"
					on:click|preventDefault={() => previous()}
					tabindex={$previousDisabled$ ? -1 : undefined}
					aria-disabled={$previousDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotPrevious$} props={slotContext} let:component let:props>
							<slot slot="slot" name="previous" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		<Slot slotContent={$slotPages$} props={slotContext} let:component let:props>
			<slot slot="slot" name="pages" let:props {...props} />
			<svelte:component this={component} {...props}>
				<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
				<slot name="first" slot="first" let:state let:widget {state} {widget} />
				<slot name="last" slot="last" let:state let:widget {state} {widget} />
				<slot name="next" slot="next" let:state let:widget {state} {widget} />
				<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
				<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
				<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
			</svelte:component>
		</Slot>
		{#if $directionLinks$}
			<li class="page-item" class:disabled={$nextDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaNextLabel$}
					class="page-link au-next"
					href="#"
					on:click|preventDefault={() => next()}
					tabindex={$nextDisabled$ ? -1 : undefined}
					aria-disabled={$nextDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotNext$} props={slotContext} let:component let:props>
							<slot slot="slot" name="next" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		{#if $boundaryLinks$}
			<li class="page-item" class:disabled={$nextDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaLastLabel$}
					class="page-link au-last"
					href="#"
					on:click|preventDefault={() => last()}
					tabindex={$nextDisabled$ ? -1 : undefined}
					aria-disabled={$nextDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotLast$} props={slotContext} let:component let:props>
							<slot slot="slot" name="last" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
	</ul>
	<div aria-live="polite" class="visually-hidden">
		{`Current page is ${$page$}`}
	</div>
</nav>

// react/bootstrap/src/components/pagination/pagination.tsx
import {useWidgetWithConfig} from '../../config';
import {Slot} from '@agnos-ui/react-headless/slot';
import type {AdaptSlotContentProps, AdaptWidgetSlots, WidgetFactory, WidgetProps, WidgetState} from '@agnos-ui/react-headless/types';
import {toSlotContextWidget} from '@agnos-ui/react-headless/types';
import classNames from 'classnames';
import {NavButton, PageItem} from './pageItem';
import {createPagination as coreCreatePagination} from '@agnos-ui/core-bootstrap/components/pagination';

export * from '@agnos-ui/core-bootstrap/components/pagination';

export type PaginationWidget = AdaptWidgetSlots<import('@agnos-ui/core-bootstrap/components/pagination').PaginationWidget>;
export type PaginationProps = WidgetProps<PaginationWidget>;
export type PaginationState = WidgetState<PaginationWidget>;
export type PaginationContext = AdaptSlotContentProps<import('@agnos-ui/core-bootstrap/components/pagination').PaginationContext>;
export type PaginationNumberContext = AdaptSlotContentProps<import('@agnos-ui/core-bootstrap/components/pagination').PaginationNumberContext>;
export const createPagination: WidgetFactory<PaginationWidget> = coreCreatePagination as any;

export * from './pageItem';

export function DefaultPages(slotContext: PaginationContext) {
	const {widget, state} = slotContext;
	const jsxPages = [];
	for (let i = 0; i < state.pages.length; i++) {
		if (state.pages[i] === -1) {
			jsxPages.push(
				<li className="page-item disabled" key={'Ellipsis' + i}>
					<div className="page-link au-ellipsis" aria-hidden="true">
						<Slot slotContent={state.slotEllipsis} props={slotContext}></Slot>
					</div>
					<span className="visually-hidden">{state.ariaEllipsisLabel}</span>
				</li>,
			);
		} else {
			jsxPages.push(
				<PageItem
					key={state.pages[i]}
					disabled={state.disabled}
					active={state.pages[i] === state.page}
					activeLabel={state.activeLabel}
					directive={widget.directives['pageLink']}
					page={state.pages[i]}
				>
					<Slot slotContent={state.slotNumberLabel} props={{...slotContext, displayedPage: state.pages[i]}}></Slot>
				</PageItem>,
			);
		}
	}
	return jsxPages.length ? <>{jsxPages}</> : null;
}

const defaultConfig: Partial<PaginationProps> = {
	slotPages: DefaultPages,
	slotStructure: DefaultStructure,
};

export function DefaultStructure(slotContext: PaginationContext) {
	const {widget, state} = slotContext;
	const ItemsBefore = [];
	const ItemsAfter = [];

	if (state.boundaryLinks) {
		ItemsBefore.push(
			<NavButton key={'first'} disabled={state.previousDisabled} directive={widget.directives['pageFirst']}>
				<Slot slotContent={state.slotFirst} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.directionLinks) {
		ItemsBefore.push(
			<NavButton key={'prev'} disabled={state.previousDisabled} directive={widget.directives['pagePrev']}>
				<Slot slotContent={state.slotPrevious} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.directionLinks) {
		ItemsAfter.push(
			<NavButton key={'next'} disabled={state.nextDisabled} directive={widget.directives['pageNext']}>
				<Slot slotContent={state.slotNext} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.boundaryLinks) {
		ItemsAfter.push(
			<NavButton key={'last'} disabled={state.nextDisabled} directive={widget.directives['pageLast']}>
				<Slot slotContent={state.slotLast} props={slotContext}></Slot>
			</NavButton>,
		);
	}

	return (
		<>
			<ul className={classNames('au-pagination', 'pagination', state.size ? `pagination-${state.size}` : '', state.className)}>
				{ItemsBefore}
				<Slot slotContent={state.slotPages} props={slotContext}></Slot>
				{ItemsAfter}
			</ul>
			<div aria-live="polite" className="visually-hidden">
				{state.page && `Current page is ${state.page}`}
			</div>
		</>
	);
}

// TODO discuss the extension of the props to the HTML UL one for react ?
export function Pagination(props: Partial<PaginationProps>) {
	const [state, widget] = useWidgetWithConfig(createPagination, props, 'pagination', defaultConfig);
	const slotContext: PaginationContext = {state, widget: toSlotContextWidget(widget)};

	return (
		<nav aria-label={state.ariaLabel}>
			<Slot slotContent={state.slotStructure} props={slotContext} />
		</nav>
	);
}
