// angular/demo/bootstrap/src/app/samples/carousel/rtl.route.ts
import {CarouselComponent, CarouselSlideDirective} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';

@Component({
	imports: [CarouselComponent, CarouselSlideDirective],
	template: `
		<div auCarousel [auSlidesData]="photos" auDirection="rtl">
			<ng-template auCarouselSlide let-src="src">
				<img class="w-100" alt="random picsum" [style.aspect-ratio]="1.8 / 1" [src]="src" />
			</ng-template>
		</div>
	`,
})
export default class RtlCarouselComponent {
	readonly photos = [944, 1011, 984].map((n) => ({id: `carousel-rtl-${n}`, src: `https://picsum.photos/id/${n}/900/500`}));
}

// svelte/demo/src/bootstrap/samples/carousel/Rtl.route.svelte
<script lang="ts">
	import {Carousel} from '@agnos-ui/svelte-bootstrap/components/carousel';

	type Photo = {id: string; src: string};
	const prefixId = $props.id();

	const photos: Photo[] = [944, 1011, 984].map((n) => ({id: `${prefixId}-${n}`, src: `https://picsum.photos/id/${n}/900/500`}));
</script>

<Carousel slidesData={photos} direction="rtl">
	{#snippet slide({src}: Photo)}
		<img class="w-100" alt="random picsum" {src} style="aspect-ratio: 1.8 / 1;" />
	{/snippet}
</Carousel>
