// react/demo/src/bootstrap/samples/carousel/Rtl.route.tsx
import {Carousel, type CarouselSlideContext} from '@agnos-ui/react-bootstrap/components/carousel';
import {useCallback, useId, useMemo} from 'react';

type Photo = {id: string; src: string};

const CarouselRtlDemo = () => {
	const prefixId = useId();
	const photos: Photo[] = useMemo(
		() => [944, 1011, 984].map((n) => ({id: `${prefixId}-${n}`, src: `https://picsum.photos/id/${n}/900/500`})),
		[prefixId],
	);
	const slide = useCallback(
		({src}: CarouselSlideContext<Photo>) => <img className="w-100" alt="random picsum" style={{aspectRatio: '1.8 / 1'}} src={src} />,
		[],
	);
	return <Carousel direction="rtl" slidesData={photos} slide={slide} />;
};
export default CarouselRtlDemo;

// svelte/demo/src/bootstrap/samples/carousel/Rtl.route.svelte
<script lang="ts">
	import {Carousel} from '@agnos-ui/svelte-bootstrap/components/carousel';

	type Photo = {id: string; src: string};
	const prefixId = $props.id();

	const photos: Photo[] = [944, 1011, 984].map((n) => ({id: `${prefixId}-${n}`, src: `https://picsum.photos/id/${n}/900/500`}));
</script>

<Carousel slidesData={photos} direction="rtl">
	{#snippet slide({src}: Photo)}
		<img class="w-100" alt="random picsum" {src} style="aspect-ratio: 1.8 / 1;" />
	{/snippet}
</Carousel>
