// svelte/demo/src/daisyui/samples/pagination/Pagination.svelte
<script lang="ts">
	import type {PaginationProps} from '@agnos-ui/svelte-headless/components/pagination';
	import {createPagination} from '@agnos-ui/svelte-headless/components/pagination';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {page = $bindable(), ...props}: Partial<PaginationProps> = $props();

	const widget = callWidgetFactory({
		factory: createPagination,
		widgetName: 'pagination',
		props: {...props, page},
		events: {
			onPageChange: (value: number) => {
				page = value;
			},
		},
	});

	const {
		stores: {
			boundaryLinks$,
			directionLinks$,
			nextDisabled$,
			previousDisabled$,
			ariaLabel$,
			ariaFirstLabel$,
			ariaPreviousLabel$,
			ariaNextLabel$,
			ariaLastLabel$,
			ariaLiveLabelText$,
			className$,
		},
		state$,
		actions: {first, previous, next, last},
	} = widget;

	$effect(() => widget.patchChangedProps({...props, page}));
</script>

<nav aria-label={$ariaLabel$}>
	<div class="join {$className$}">
		{#if $boundaryLinks$}
			<button
				class="join-item btn btn-outline"
				aria-label={$ariaFirstLabel$}
				onclick={() => first()}
				disabled={$previousDisabled$}
				aria-disabled={$previousDisabled$ ? 'true' : null}
				tabindex={$previousDisabled$ ? -1 : undefined}
			>
				<span aria-hidden="true"> « </span>
			</button>
		{/if}
		{#if $directionLinks$}
			<button
				class="join-item btn btn-outline"
				disabled={$previousDisabled$}
				aria-label={$ariaPreviousLabel$}
				onclick={() => previous()}
				tabindex={$previousDisabled$ ? -1 : undefined}
				aria-disabled={$previousDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> ‹ </span>
			</button>
		{/if}
		{#each $state$.pages as page}
			<button
				class="join-item btn btn-outline"
				class:btn-active={page === $state$.page}
				aria-current={page === $state$.page ? 'page' : null}
				tabindex={page === -1 ? -1 : $state$.disabled ? -1 : undefined}
				onclick={page === -1 ? () => {} : () => widget.actions.select(page)}
				disabled={page === -1 || $state$.disabled}
				>{page}
				{#if $state$.page === page}<span class="sr-only">{$state$.activeLabel}</span>{/if}
			</button>
		{/each}
		{#if $directionLinks$}
			<button
				class="join-item btn btn-outline"
				disabled={$nextDisabled$}
				aria-label={$ariaNextLabel$}
				onclick={() => next()}
				tabindex={$nextDisabled$ ? -1 : undefined}
				aria-disabled={$nextDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> › </span>
			</button>
		{/if}
		{#if $boundaryLinks$}
			<button
				class="join-item btn btn-outline"
				aria-label={$ariaLastLabel$}
				onclick={() => last()}
				disabled={$nextDisabled$}
				tabindex={$nextDisabled$ ? -1 : undefined}
				aria-disabled={$nextDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> » </span>
			</button>
		{/if}
	</div>
	<div aria-live="polite" class="sr-only">
		{`${$ariaLiveLabelText$}`}
	</div>
</nav>

// angular/demo/daisyui/src/app/samples/pagination/pagination.component.ts
import {
	BaseWidgetDirective,
	type PaginationProps,
	type PaginationWidget,
	auBooleanAttribute,
	auNumberAttribute,
	callWidgetFactory,
	createPagination,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output} from '@angular/core';

@Component({
	selector: 'app-pagination',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './pagination.component.html',
})
export class PaginationComponent extends BaseWidgetDirective<PaginationWidget> {
	@Input() ariaPageLabel?: PaginationProps['ariaPageLabel'];
	@Input() ariaLabel?: PaginationProps['ariaLabel'];
	@Input() activeLabel?: PaginationProps['activeLabel'];
	@Input() ariaFirstLabel?: PaginationProps['ariaFirstLabel'];
	@Input() ariaPreviousLabel?: PaginationProps['ariaPreviousLabel'];
	@Input() ariaNextLabel?: PaginationProps['ariaNextLabel'];
	@Input() ariaLastLabel?: PaginationProps['ariaLastLabel'];
	@Input() ariaEllipsisLabel?: PaginationProps['ariaEllipsisLabel'];
	@Input() pageLink?: PaginationProps['pageLink'];
	@Input({transform: auBooleanAttribute}) disabled?: PaginationProps['disabled'];
	@Input({transform: auBooleanAttribute}) boundaryLinks?: PaginationProps['boundaryLinks'];
	@Input({transform: auBooleanAttribute}) directionLinks?: PaginationProps['directionLinks'];
	@Input({transform: auNumberAttribute}) collectionSize?: PaginationProps['collectionSize'];
	@Input({transform: auNumberAttribute}) page?: PaginationProps['page'];
	@Input({transform: auNumberAttribute}) pageSize?: PaginationProps['pageSize'];
	@Input() size?: PaginationProps['size'];
	@Input() pagesFactory?: PaginationProps['pagesFactory'];
	@Input() className?: PaginationProps['className'];
	@Output() pageChange = new EventEmitter<number>();

	readonly _widget = callWidgetFactory({
		factory: createPagination,
		widgetName: 'pagination',
		events: {
			onPageChange: (page: number) => this.pageChange.emit(page),
		},
	});
}

<nav [attr.aria-label]="state().ariaLabel">
	<div class="join" [class]="state().className">
		@if (state().boundaryLinks) {
			<button
				class="join-item btn btn-outline"
				[attr.aria-label]="state().ariaFirstLabel"
				(click)="widget.actions.first()"
				[disabled]="state().previousDisabled"
				[attr.aria-disabled]="state().previousDisabled ? 'true' : null"
				[attr.tabindex]="state().previousDisabled ? -1 : undefined"
			>
				<span aria-hidden="true"> « </span>
			</button>
		}
		@if (state().directionLinks) {
			<button
				class="join-item btn btn-outline"
				[attr.aria-label]="state().ariaPreviousLabel"
				(click)="widget.actions.previous()"
				[disabled]="state().previousDisabled"
				[attr.aria-disabled]="state().previousDisabled ? 'true' : null"
				[attr.tabindex]="state().previousDisabled ? -1 : undefined"
			>
				<span aria-hidden="true"> ‹ </span>
			</button>
		}
		@for (page of state().pages; track page; let i = $index) {
			<button
				class="join-item btn btn-outline"
				[class.btn-active]="page === state().page"
				[attr.aria-current]="page === state().page ? 'page' : null"
				[attr.tabindex]="state().disabled ? -1 : undefined"
				[class.disabled]="state().disabled"
				(click)="widget.actions.select(page)"
			>
				{{ page }}
				@if (state().page === page) {
					<span class="sr-only">{{ state().activeLabel }}</span>
				}
			</button>
		}
		@if (state().directionLinks) {
			<button
				class="join-item btn btn-outline"
				[attr.aria-label]="state().ariaNextLabel"
				(click)="widget.actions.next()"
				[disabled]="state().nextDisabled"
				[attr.aria-disabled]="state().nextDisabled ? 'true' : null"
				[attr.tabindex]="state().nextDisabled ? -1 : undefined"
			>
				<span aria-hidden="true"> › </span>
			</button>
		}
		@if (state().boundaryLinks) {
			<button
				class="join-item btn btn-outline"
				[attr.aria-label]="state().ariaLastLabel"
				(click)="widget.actions.last()"
				[disabled]="state().nextDisabled"
				[attr.aria-disabled]="state().nextDisabled ? 'true' : null"
				[attr.tabindex]="state().nextDisabled ? -1 : undefined"
			>
				<span aria-hidden="true"> » </span>
			</button>
		}
	</div>
	<div aria-live="polite" class="sr-only">Current page is {{ state().page }}</div>
</nav>
