// svelte/demo/src/bootstrap/samples/configuration/Success.svelte
<script lang="ts">
	import {Alert} from '@agnos-ui/svelte/components/alert';
	import {createWidgetsDefaultConfig} from '@agnos-ui/svelte/config';

	createWidgetsDefaultConfig().set({alert: {type: 'success'}});
</script>

<Alert>Alert not dismissible and of type success, type overriden by child config</Alert>

// angular/demo/src/app/samples/configuration/success.component.ts
import {AlertComponent, provideWidgetsConfig} from '@agnos-ui/angular';
import {Component} from '@angular/core';

@Component({
	standalone: true,
	selector: 'app-success',
	imports: [AlertComponent],
	providers: [provideWidgetsConfig((config) => ({...config, alert: {...config.alert, type: 'success'}}))],
	template: ` <au-component auAlert>Alert not dismissible and of type success, type overriden by child config</au-component> `,
})
export default class SuccessComponent {}
