// svelte/demo/samples/floatingUI/FloatingUI.route.svelte
<script lang="ts">
	import '@agnos-ui/common/samples/floatingui/floatingui.scss';
	import {createFloatingUI, floatingUI} from '@agnos-ui/svelte-headless/services';

	const {
		directives: {floatingDirective, referenceDirective, arrowDirective},
		stores: {placement$, middlewareData$},
	} = createFloatingUI({
		props: {
			arrowOptions: {
				padding: 6,
			},
			computePositionOptions: {
				middleware: [
					floatingUI.offset(10),
					floatingUI.autoPlacement(),
					floatingUI.shift({
						padding: 5,
					}),
					floatingUI.hide(),
				],
			},
		},
	});

	let displayPopover = true;
	const toggleButton = () => {
		displayPopover = !displayPopover;
	};

	const scrollToMiddle = (element: HTMLElement) => {
		element.scrollTo({left: 326, top: 420});
	};
</script>

<div class="position-relative overflow-auto border border-primary-subtle demo-floatingui" use:scrollToMiddle>
	<button use:referenceDirective type="button" class="btn btn-primary" on:click={toggleButton}>Toggle popover</button>
	{#if displayPopover}
		<div
			use:floatingDirective
			data-popper-placement={$placement$}
			class="popover bs-popover-auto position-absolute"
			class:invisible={$middlewareData$?.hide?.referenceHidden}
			role="tooltip"
		>
			<div class="popover-arrow position-absolute" use:arrowDirective></div>
			<div class="popover-body text-center">This is a sample popover</div>
		</div>
	{/if}
</div>

// react/demo/app/samples/floatingUI/FloatingUI.route.tsx
import '@agnos-ui/common/samples/floatingui/floatingui.scss';
import {createFloatingUI, floatingUI} from '@agnos-ui/react-headless/services';
import {useDirective, useObservable} from '@agnos-ui/react-headless/utils';
import {useMemo, useState} from 'react';

const scrollToMiddle = (element: HTMLElement) => {
	element.scrollTo({left: 326, top: 420});
};

const FloatingUI = () => {
	const [displayPopover, setDisplayPopover] = useState(true);
	const floatingUIInstance = useMemo(
		() =>
			createFloatingUI({
				props: {
					arrowOptions: {
						padding: 6,
					},
					computePositionOptions: {
						middleware: [
							floatingUI.offset(10),
							floatingUI.autoPlacement(),
							floatingUI.shift({
								padding: 5,
							}),
							floatingUI.hide(),
						],
					},
				},
			}),
		[],
	);
	const floatingUIState = useObservable(floatingUIInstance.state$);
	const refContainer = useDirective(scrollToMiddle);
	const refReference = useDirective(floatingUIInstance.directives.referenceDirective);
	const refFloating = useDirective(floatingUIInstance.directives.floatingDirective);
	const refArrow = useDirective(floatingUIInstance.directives.arrowDirective);

	return (
		<div ref={refContainer} className="position-relative overflow-auto border border-primary-subtle demo-floatingui">
			<button ref={refReference} type="button" className="btn btn-primary" onClick={() => setDisplayPopover(!displayPopover)}>
				Toggle popover
			</button>
			{displayPopover ? (
				<div
					ref={refFloating}
					data-popper-placement={floatingUIState.placement}
					className={`popover bs-popover-auto position-absolute ${floatingUIState.middlewareData?.hide?.referenceHidden ? 'invisible' : ''}`}
					role="tooltip"
				>
					<div className="popover-arrow position-absolute" ref={refArrow}></div>
					<div className="popover-body text-center">This is a sample popover</div>
				</div>
			) : null}
		</div>
	);
};
export default FloatingUI;
