// svelte/demo/src/app/samples/toast/Dynamic.route.svelte
<script lang="ts">
	import {Toast} from '@agnos-ui/svelte/components/toast';
	import type {ToastProps} from '@agnos-ui/svelte/components/toast';
	import {writable} from 'svelte/store';

	enum ToastPositions {
		topLeft = 'top-0 start-0',
		topCenter = 'top-0 start-50 translate-middle-x',
		topRight = 'top-0 end-0',
		middleLeft = 'top-50 start-0 translate-middle-y',
		middleCenter = 'top-50 start-50 translate-middle',
		middleRight = 'top-50 end-0 translate-middle-y',
		bottomLeft = 'bottom-0 start-0',
		bottomCenter = 'bottom-0 start-50 translate-middle-x',
		bottomRight = 'bottom-0 end-0',
	}

	const positions = Object.entries(ToastPositions).map((entry) => {
		return {
			value: entry[1],
			label: entry[0],
		};
	});
	let position = ToastPositions.topLeft;

	function createToasts() {
		const {subscribe, update} = writable(new Map(Object.values(ToastPositions).map((entry) => [entry as string, [] as Partial<ToastProps>[]])));
		return {
			subscribe,
			add: (toast: Partial<ToastProps>) =>
				update((toasts) => {
					toasts.get(toast.className!)?.push(toast);
					return toasts;
				}),
			remove: (toast: Partial<ToastProps>) =>
				update((toasts) => {
					toasts.set(
						toast.className!,
						toasts.get(toast.className!)!.filter((t) => t !== toast),
					);
					return toasts;
				}),
		};
	}

	export const toasts$ = createToasts();
</script>

<p class="mb-2">To position toast wherever you want you should have a <code>toast-container</code> with a custom position defined by CSS classes.</p>
<p class="mb-2">To <strong>stack</strong> toasts vertically, put them in the same container.</p>
<div class="d-flex justify-content-between">
	<div class="d-flex form-group align-items-center">
		<label class="me-3" for="positionSelect">Position: </label>
		<select id="positionSelect" class="form-select w-auto" bind:value={position}>
			{#each positions as { value, label }}
				<option {value}> {label}</option>
			{/each}
		</select>
		<button
			class="btn btn-primary addToast ms-2"
			on:click={() => toasts$.add({autohide: true, delay: 3000, className: position, slotDefault: 'Simple toast', slotHeader: 'I am header'})}
			>Show toast</button
		>
	</div>
</div>

<div class="d-flex position-relative mt-2 w-100" aria-live="polite" aria-atomic="true" style="height: 500px; background-color: gray;">
	{#each $toasts$.entries() as [position, toasts]}
		<div class={`toast-container p-3 ${position}`}>
			{#each toasts as toast}
				{@const {dismissible, animationOnInit, animation, slotDefault, slotHeader} = toast}
				<Toast {dismissible} {animationOnInit} {animation} {slotDefault} {slotHeader} onHidden={() => toasts$.remove(toast)} />
			{/each}
		</div>
	{/each}
</div>

// angular/demo/src/app/samples/toast/dynamic.route.ts
import type {ToastProps} from '@agnos-ui/angular';
import {AgnosUIAngularModule, ToastComponent} from '@agnos-ui/angular';
import {Component, Injectable, inject} from '@angular/core';
import {FormsModule} from '@angular/forms';

export enum ToastPositions {
	topLeft = 'top-0 start-0',
	topCenter = 'top-0 start-50 translate-middle-x',
	topRight = 'top-0 end-0',
	middleLeft = 'top-50 start-0 translate-middle-y',
	middleCenter = 'top-50 start-50 translate-middle',
	middleRight = 'top-50 end-0 translate-middle-y',
	bottomLeft = 'bottom-0 start-0',
	bottomCenter = 'bottom-0 start-50 translate-middle-x',
	bottomRight = 'bottom-0 end-0',
}

@Injectable({providedIn: 'root'})
class ToastService {
	toastMap: Map<string, Partial<ToastProps>[]> = new Map(Object.values(ToastPositions).map((entry) => [entry, []]));

	add(toast: Partial<ToastProps>) {
		this.toastMap.get(toast.className!)?.push(toast);
	}

	remove(toast: Partial<ToastProps>) {
		this.toastMap.set(
			toast.className!,
			this.toastMap.get(toast.className!)!.filter((t) => t !== toast),
		);
	}
}

@Component({
	selector: 'app-toast-container',
	standalone: true,
	imports: [ToastComponent],
	template: ` <div class="d-flex position-relative mt-2 w-100" aria-live="polite" aria-atomic="true" style="height: 500px; background-color: gray;">
		@for (position of toastContainerService.toastMap.keys(); track position) {
			<div class="toast-container p-3 {{ position }}">
				@for (toast of toastContainerService.toastMap.get(position); track toast) {
					<au-component auToast (auHidden)="removeToast(toast)" auSlotHeader="I am header" [auAutoHide]="toast.autoHide" [auDelay]="toast.delay"
						>Simple toast</au-component
					>
				}
			</div>
		}
	</div>`,
})
class ToastContainerComponent {
	readonly toastContainerService = inject(ToastService);

	removeToast(toast: Partial<ToastProps>) {
		this.toastContainerService.remove(toast);
	}
}

@Component({
	standalone: true,
	imports: [AgnosUIAngularModule, ToastContainerComponent, FormsModule],
	template: `
		<p class="mb-2">
			To position toast wherever you want you should have a <code>toast-container</code> with a custom position defined by CSS classes.
		</p>
		<p class="mb-2">To <strong>stack</strong> toasts vertically, put them in the same container.</p>
		<div class="d-flex justify-content-between">
			<div class="d-flex form-group align-items-center">
				<label class="me-3" for="positionSelect">Position: </label>
				<select id="positionSelect" class="form-select w-auto" [(ngModel)]="position">
					@for (position of positionList; track position) {
						<option [value]="position.value">{{ position.label }}</option>
					}
				</select>
				<button class="btn btn-primary addToast ms-2" (click)="addToast()">Show toast</button>
			</div>
		</div>

		<app-toast-container />
	`,
})
export default class DynamicToastComponent {
	readonly toastContainerService = inject(ToastService);

	positionList = Object.entries(ToastPositions).map((entry) => {
		return {
			value: entry[1],
			label: entry[0],
		};
	});

	position = this.positionList[0].value;

	addToast() {
		this.toastContainerService.add({autoHide: true, delay: 3000, className: this.position});
	}
}
