// angular/demo/src/app/samples/alert/dynamic.route.ts
import {AlertComponent} from '@agnos-ui/angular';
import type {AlertProps} from '@agnos-ui/angular';
import {NgFor} from '@angular/common';
import {Component, Injectable} from '@angular/core';

@Injectable({providedIn: 'root'})
class AlertContainerService {
	alerts: Partial<AlertProps>[] = [];
	add(alert: Partial<AlertProps>) {
		this.alerts.push(alert);
	}

	remove(type: Partial<AlertProps>) {
		this.alerts = this.alerts.filter((al) => al !== type);
	}

	clear() {
		this.alerts = [];
	}
}

@Component({
	selector: 'app-alert-child',
	standalone: true,
	imports: [AlertComponent, NgFor],
	template: `
		<au-alert
			*ngFor="let alert of alertContainerService.alerts"
			[animation]="alert.animation"
			[animationOnInit]="alert.animationOnInit"
			[dismissible]="alert.dismissible"
			[type]="alert.type"
			[slotDefault]="alert.slotDefault"
			(hidden)="removeAlert(alert)"
		>
		</au-alert>
	`,
})
class ChildComponent {
	constructor(readonly alertContainerService: AlertContainerService) {}

	removeAlert(type: Partial<AlertProps>) {
		this.alertContainerService.remove(type);
	}
}

@Component({
	standalone: true,
	imports: [ChildComponent],
	template: `
		<button class="btn btn-primary addError me-1" (click)="addError()">Add error</button>
		<button class="btn btn-primary addInfo me-1" (click)="addInfo()">Add info</button>
		<button class="btn btn-primary addWarning me-1" (click)="addWarning()">Add warning</button>
		<br />
		<div class="alertCount mb-3">Alerts in the service: {{ alertContainerService.alerts.length }}</div>
		<app-alert-child />
	`,
})
export default class ParentComponent {
	constructor(readonly alertContainerService: AlertContainerService) {}

	addError() {
		this.alertContainerService.add({type: 'danger', slotDefault: 'Error', dismissible: true, animation: true});
	}

	addWarning() {
		this.alertContainerService.add({type: 'warning', slotDefault: 'Warning', dismissible: true, animation: true});
	}

	addInfo() {
		this.alertContainerService.add({type: 'info', slotDefault: 'Info', dismissible: true, animation: true});
	}
}

// svelte/demo/samples/alert/Dynamic.route.svelte
<script lang="ts">
	import {Alert} from '@agnos-ui/svelte';
	import type {AlertProps} from '@agnos-ui/core';
	import {writable} from 'svelte/store';

	function createAlerts() {
		const {subscribe, set, update} = writable([] as Partial<AlertProps>[]);

		return {
			subscribe,
			add: (alert: Partial<AlertProps>) => update((alerts) => [...alerts, alert]),
			remove: (alert: Partial<AlertProps>) => update((alerts) => alerts.filter((a) => a !== alert)),
			reset: () => set([]),
		};
	}

	export const alerts$ = createAlerts();
</script>

<button class="btn btn-primary addError me-1" on:click={() => alerts$.add({type: 'danger', slotDefault: 'Error', dismissible: true, animation: true})}
	>Add error</button
>

<button class="btn btn-primary addInfo me-1" on:click={() => alerts$.add({type: 'info', slotDefault: 'Info', dismissible: true, animation: true})}
	>Add info</button
>

<button
	class="btn btn-primary addWarning me-1"
	on:click={() => alerts$.add({type: 'warning', slotDefault: 'Warning', dismissible: true, animation: true})}>Add warning</button
>

<br />
<div class="alertCount mb-3">Alerts in the service: {$alerts$.length}</div>
{#each $alerts$ as alert (alert)}
	{@const {dismissible, animationOnInit, animation, type, slotDefault} = alert}

	<Alert {dismissible} {animationOnInit} {animation} {type} {slotDefault} on:hidden={() => alerts$.remove(alert)} />
{/each}
