// svelte/demo/src/app/samples/slider/FullCustom.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte/components/slider';
	import CoffeeSlider from './CoffeeSlider.svelte';

	let sliderControl = [50];

	import '@agnos-ui/common/samples/slider/custom.scss';
</script>

<h2>Fully custom slider</h2>

<Slider
	min={0}
	max={100}
	stepSize={1}
	bind:values={sliderControl}
	vertical
	className="custom-slider"
	slotStructure={CoffeeSlider}
	slotLabel={null}
	slotHandle={null}
/>

// react/demo/src/bootstrap/samples/slider/FullCustom.route.tsx
import {Slider} from '@agnos-ui/react/components/slider';
import {useState} from 'react';
import '@agnos-ui/common/samples/slider/custom.scss';
import CustomSliderComponent from './CoffeeSlider';

const FullCustomSliderDemo = () => {
	const [sliderControl, setSliderControl] = useState([50]);

	return (
		<>
			<h2>Fully custom slider</h2>
			<Slider
				min={0}
				max={100}
				stepSize={1}
				values={sliderControl}
				onValuesChange={setSliderControl}
				slotStructure={CustomSliderComponent}
				vertical
				className="custom-slider"
			/>
		</>
	);
};
export default FullCustomSliderDemo;
