// svelte/demo/src/bootstrap/samples/slider/FullCustom.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';
	import CoffeeSlider from './CoffeeSlider.svelte';

	let sliderControl = [50];

	import '@agnos-ui/common/samples/slider/custom.scss';
</script>

<h2>Fully custom slider</h2>

<Slider min={0} max={100} stepSize={1} bind:values={sliderControl} vertical className="custom-slider" structure={CoffeeSlider} />

// react/demo/src/bootstrap/samples/slider/FullCustom.route.tsx
import {Slider} from '@agnos-ui/react-bootstrap/components/slider';
import {useState} from 'react';
import '@agnos-ui/common/samples/slider/custom.scss';
import {CoffeeSlider} from './CoffeeSlider';

export default () => {
	const [sliderControl, setSliderControl] = useState([50]);

	return (
		<Slider
			min={0}
			max={100}
			stepSize={1}
			values={sliderControl}
			onValuesChange={setSliderControl}
			structure={CoffeeSlider}
			vertical
			className="custom-slider"
		/>
	);
};
