// svelte/demo/src/bootstrap/samples/slider/Range.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';

	let sliderControl = [10, 40, 50, 60, 90];
	let sliderValues = [10, 40];
</script>

<h3>Slider with form control</h3>
<Slider min={0} max={100} stepSize={1} bind:values={sliderControl} />
Form control values: {sliderControl?.join(', ')}
<hr />

<h3>Slider with values</h3>
<Slider min={0} max={100} stepSize={1} bind:values={sliderValues} />
Values: {sliderValues.join(', ')}

// react/demo/src/bootstrap/samples/slider/Range.route.tsx
import {Slider} from '@agnos-ui/react-bootstrap/components/slider';
import {useState} from 'react';

export default () => {
	const [sliderControl, setSliderControl] = useState([10, 40, 50, 60, 90]);
	const [sliderValues, setSliderValues] = useState([10, 40]);

	return (
		<>
			<h3>Slider with form control</h3>
			<Slider min={0} max={100} stepSize={1} values={sliderControl} onValuesChange={setSliderControl} />
			Form control values: {sliderControl?.join(', ')}
			<hr />
			<h3>Slider with values</h3>
			<Slider min={0} max={100} stepSize={1} values={sliderValues} onValuesChange={setSliderValues} />
			Values: {sliderValues.join(', ')}
		</>
	);
};
