// svelte/demo/src/app/samples/slots/Headless.route.svelte
<script lang="ts">
	import '@agnos-ui/common/samples/rating/custom.scss';
	import RatingReadonly from './RatingReadonly.svelte';
</script>

<div>The readonly rating without slot:</div>
<RatingReadonly rating={7} maxRating={10} />

<div class="mt-2">Using a slot to customize the display:</div>
<RatingReadonly rating={7} maxRating={10} className="rating-custom">
	<span slot="star" let:index let:fill class="star" class:filled={fill === 100} class:bad={index < 3}>&#9733;</span>
</RatingReadonly>

// angular/demo/bootstrap/src/app/samples/slots/headless.route.ts
import {Component, ViewEncapsulation} from '@angular/core';
import {RatingReadonlyComponent, RatingReadonlyStarDirective} from './rating-readonly.component';

@Component({
	standalone: true,
	imports: [RatingReadonlyComponent, RatingReadonlyStarDirective],
	encapsulation: ViewEncapsulation.None,
	template: `
		<div>The readonly rating without slot:</div>
		<app-rating-readonly [rating]="7" [maxRating]="10" />

		<div class="mt-2">Using a slot to customize the display:</div>
		<app-rating-readonly className="rating-custom" [rating]="7" [maxRating]="10">
			<ng-template appRatingStar let-fill="fill" let-index="index">
				<span class="star" [class.filled]="fill === 100" [class.bad]="index < 3">&#9733;</span>
			</ng-template>
		</app-rating-readonly>
	`,
	styles: "@import '@agnos-ui/common/samples/rating/custom.scss';",
})
export default class SlotsHeadlessComponent {}
