// svelte/demo/src/bootstrap/samples/slots/Usage.route.svelte
<script lang="ts">
	import {Alert} from '@agnos-ui/svelte-bootstrap/components/alert';
</script>

<Alert type="primary" dismissible={false}>Label provided by slot</Alert>
<Alert type="secondary" dismissible={false} children="Label provided by property" />
<Alert type="info" dismissible={false} children="When both prop and slot are provided, the prop's content will take precedence."
	>This content is ignored.</Alert
>

// angular/demo/bootstrap/src/app/samples/slots/usage.route.ts
import {AlertComponent} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';

@Component({
	imports: [AlertComponent],
	template: `
		<au-component auAlert auType="primary" [auDismissible]="false"> Label provided by slot </au-component>
		<au-component auAlert auType="secondary" [auDismissible]="false" auChildren="Label provided by property" />
		<au-component
			auAlert
			auType="info"
			[auDismissible]="false"
			auChildren="When both prop and slot are provided, the prop's content will take precedence."
		>
			This content is ignored.
		</au-component>
	`,
})
export default class SlotsUsageComponent {}
