// react/lib/src/components/toast/toast.tsx
import type {ToastContext, ToastProps} from '@agnos-ui/react-headless/components/toast';
import {createToast} from '@agnos-ui/react-headless/components/toast';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {Slot} from '@agnos-ui/react-headless/slot';
import {useDirectives} from '@agnos-ui/react-headless/utils/directive';
import type {PropsWithChildren} from 'react';
import {forwardRef, useImperativeHandle} from 'react';

export * from '@agnos-ui/react-headless/components/toast';

const DefaultSlotStructure = (slotContext: ToastContext) => (
	<>
		{slotContext.state.slotHeader ? (
			<div className="toast-header">
				<Slot slotContent={slotContext.state.slotHeader} props={slotContext}></Slot>
				{slotContext.state.dismissible ? (
					<button
						type="button"
						className="btn-close me-0 ms-auto"
						onClick={slotContext.widget.api.close}
						aria-label={slotContext.state.ariaCloseButtonLabel}
					></button>
				) : null}
			</div>
		) : null}

		<div className="toast-body">
			<Slot slotContent={slotContext.state.slotDefault} props={slotContext}></Slot>
		</div>
		{slotContext.state.dismissible && !slotContext.state.slotHeader ? (
			<button
				type="button"
				className="btn-close btn-close-white me-2 m-auto"
				onClick={slotContext.widget.api.close}
				aria-label={slotContext.state.ariaCloseButtonLabel}
			></button>
		) : null}
	</>
);

const defaultConfig: Partial<ToastProps> = {
	slotStructure: DefaultSlotStructure,
};

export const Toast = forwardRef(function Toast(props: PropsWithChildren<Partial<ToastProps>>, ref) {
	const [state, widget] = useWidgetWithConfig(createToast, props, 'toast', {...defaultConfig, slotDefault: props.children});
	const refToast = useDirectives([widget.directives.transitionDirective, widget.directives.autohideDirective]);
	useImperativeHandle(ref, () => widget.api, []);
	const slotContext = {
		state,
		widget,
	};

	return (
		<>
			{state.hidden ? null : (
				<div
					className={`au-toast toast ${state.className} ${state.dismissible ? 'toast-dismissible' : ''} ${!state.slotHeader ? 'd-flex' : ''}`}
					role="alert"
					ref={refToast}
					aria-atomic="true"
				>
					<Slot slotContent={state.slotStructure} props={slotContext}></Slot>
				</div>
			)}
		</>
	);
});

// svelte/lib/src/components/toast/Toast.svelte
<script lang="ts" context="module">
	import type {ToastProps as Props, ToastSlots as Slots} from '@agnos-ui/svelte-headless/components/toast';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {createToast} from '@agnos-ui/svelte-headless/components/toast';
	import {callWidgetFactory} from '../../config';
	import ToastDefaultStructure from './ToastDefaultStructure.svelte';

	const defaultConfig: Partial<Props> = {
		slotStructure: ToastDefaultStructure,
	};
</script>

<script lang="ts">
	type $$Props = Partial<Props>;
	type $$Slots = Slots;

	const widget = callWidgetFactory({
		factory: createToast,
		widgetName: 'toast',
		$$slots,
		$$props,
		defaultConfig,
		events: {
			onVisibleChange: (event) => {
				visible = event;
			},
		},
	});
	export let visible: boolean | undefined = undefined;
	export const api = widget.api;

	const {
		stores: {slotStructure$, hidden$},
		directives: {transitionDirective, autoHideDirective},
		state$,
	} = widget;

	$: widget.patchChangedProps($$props);
	$: slotContext = {widget, state: $state$};
</script>

{#if !$hidden$}
	<div
		class="au-toast toast {$state$.className}"
		class:toast-dismissible={$state$.dismissible}
		class:d-flex={!$state$.slotHeader}
		role="alert"
		aria-atomic="true"
		use:transitionDirective
		use:autoHideDirective
	>
		<Slot slotContent={$slotStructure$} props={slotContext} let:component let:props>
			<svelte:fragment slot="slot" let:props><slot name="structure" {...props} /></svelte:fragment>
			<svelte:component this={component} {...props}>
				<svelte:fragment let:state let:widget><slot {state} {widget} /></svelte:fragment>
				<svelte:fragment slot="header" let:state let:widget><slot name="header" {state} {widget} /></svelte:fragment>
				<svelte:fragment slot="structure" let:state let:widget><slot name="structure" {state} {widget} /></svelte:fragment>
			</svelte:component>
		</Slot>
	</div>
{/if}
