// svelte/demo/samples/slider/Vertical.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte';

	let sliderControl = [10, 40];
	let sliderControlRange = [40];
</script>

<div class="d-flex" style="height: 350px">
	<div class="col-6" style="height: 300px">
		<Slider min={0} max={100} stepSize={1} vertical={true} bind:values={sliderControl} className="my-0" />
		<div class="mt-3">Form control values: {sliderControl?.join(', ')}</div>
	</div>
	<div class="col-6" style="height: 300px">
		<Slider min={0} max={100} stepSize={1} vertical={true} bind:values={sliderControlRange} className="my-0" />
		<div class="mt-3">From control value: {sliderControlRange?.join(', ')}</div>
	</div>
</div>

// angular/demo/src/app/samples/slider/vertical.route.ts
import {AgnosUIAngularModule} from '@agnos-ui/angular';
import {Component} from '@angular/core';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';

@Component({
	standalone: true,
	imports: [AgnosUIAngularModule, ReactiveFormsModule, FormsModule],
	template: `
		<h2>Vertical slider</h2>
		<div class="d-flex" style="height: 350px">
			<div class="col-6" style="height: 300px">
				<au-component auSlider [auMin]="0" [auMax]="100" [auStepSize]="1" [auVertical]="true" [formControl]="sliderControl"></au-component>
				Form control values: {{ sliderControl.value?.join(', ') }}
			</div>
			<div class="col-6" style="height: 300px">
				<au-component auSlider [auMin]="0" [auMax]="100" [auStepSize]="1" [auVertical]="true" [formControl]="sliderControlRange"></au-component>
				From control value: {{ sliderControlRange.value }}
			</div>
		</div>
	`,
})
export default class VerticalSliderComponent {
	sliderControl = new FormControl([10, 40]);
	sliderControlRange = new FormControl([40]);
}
