// react/demo/src/app/samples/select/Custom.route.tsx
import {abortPrevious, debounce} from '@agnos-ui/common/samples/utils/debounce';
import type {SelectItemContext} from '@agnos-ui/react/components/select';
import {Select} from '@agnos-ui/react/components/select';
import React, {useCallback, useState} from 'react';

import '@agnos-ui/common/samples/select/custom.scss';

const basePageUrl = 'https://en.wikipedia.org/?curid=';

interface WikiResult {
	pageid: number;
	title: string;
	snippet: string;
}

const compareFn = new Intl.Collator('en').compare;

function getHtmlText(html: string) {
	const template = document.createElement('div');
	template.innerHTML = html;
	return template.innerText;
}

const itemIdFn = (item: WikiResult) => 'page-' + item.pageid;

const SlotBadgeLabel = ({itemContext, widget}: SelectItemContext<WikiResult>) => {
	return (
		<>
			<a href={basePageUrl + itemContext.item.pageid} target="_blank" rel="noreferrer">
				{itemContext.item.title}
			</a>
			<button
				type="button"
				className="btn-close ms-1 wiki-btn-close"
				aria-label="Close"
				onClick={(e) => widget.actions.onRemoveBadgeClick(e as any, itemContext.item)}
			></button>
		</>
	);
};

const SlotItem = ({itemContext}: SelectItemContext<WikiResult>) => {
	const item = itemContext.item;
	return (
		<>
			<div className="fw-bold">{item.title}</div>
			<div className="text-wrap wiki-desc">{item.snippet}</div>
		</>
	);
};

const navSelector = (node: HTMLElement) => node.querySelectorAll('a,button,input') as NodeListOf<HTMLSpanElement | HTMLInputElement>;
const Custom = () => {
	const [items, setItems] = useState([] as WikiResult[]);
	const [selected, setSelected] = useState([] as WikiResult[]);

	const [, setFilterText] = useState(undefined as string | undefined);
	const onFilterTextChange = useCallback(
		debounce(
			abortPrevious(async (signal: AbortSignal, text: string) => {
				setFilterText(text);
				const response = await fetch(
					'https://en.wikipedia.org/w/api.php?action=query&list=search&prop=info&inprop=url&utf8=&format=json&origin=*&srlimit=5&srsearch=' + text,
					{signal},
				);
				const result = await response.json();
				setItems(result.query?.search.map((item: WikiResult) => ({...item, snippet: getHtmlText(item.snippet)})) ?? []);
			}),
			200,
		),
		[],
	);

	const onSelectedChange = useCallback((selected: WikiResult[]) => {
		setSelected((selected || []).sort((a, b) => compareFn(a.title, b.title)));
	}, []);

	return (
		<div className="custom-select my-auto mb-3">
			<Select
				items={items}
				itemIdFn={itemIdFn}
				navSelector={navSelector}
				onFilterTextChange={onFilterTextChange}
				onSelectedChange={onSelectedChange}
				slotBadgeLabel={SlotBadgeLabel}
				slotItem={SlotItem}
				badgeClassName="badge text-bg-light d-flex align-items-center"
			/>
			<span className="fw-bold">Selection: </span>
			{selected.map((item) => (
				<React.Fragment key={itemIdFn(item)}>
					<a href={`${basePageUrl}${item.pageid}`} className="pe-2">
						{item.title}
					</a>
				</React.Fragment>
			))}
			{!selected.length && <>none</>}
		</div>
	);
};
export default Custom;

// svelte/demo/src/bootstrap/samples/select/Custom.route.svelte
<script lang="ts">
	import {abortPrevious, debounce} from '@agnos-ui/common/samples/utils/debounce';
	import {Select} from '@agnos-ui/svelte-bootstrap/components/select';

	import '@agnos-ui/common/samples/select/custom.scss';

	const basePageUrl = 'https://en.wikipedia.org/?curid=';

	interface WikiResult {
		pageid: number;
		title: string;
		snippet: string;
	}
	let items: WikiResult[] = [];
	let selected: WikiResult[] = [];

	const itemIdFn = (item: WikiResult) => {
		return 'page-' + item.pageid;
	};

	function getHtmlText(html: string) {
		const template = document.createElement('div');
		template.innerHTML = html;
		return template.innerText;
	}

	const onFilterTextChange = debounce(
		abortPrevious(async (signal: AbortSignal, text: string) => {
			const response = await fetch(
				'https://en.wikipedia.org/w/api.php?action=query&list=search&prop=info&inprop=url&utf8=&format=json&origin=*&srlimit=5&srsearch=' + text,
				{signal},
			);
			const result = await response.json();
			items = result.query?.search.map((item: WikiResult) => ({...item, snippet: getHtmlText(item.snippet)})) ?? [];
		}),
		200,
	);

	const compareFn = new Intl.Collator('en').compare;
	function onSelectedChange(items: WikiResult[]) {
		selected = (<WikiResult[]>(items || [])).sort((a, b) => compareFn(a.title, b.title));
	}

	const navSelector = (node: HTMLElement) => node.querySelectorAll<HTMLSpanElement | HTMLInputElement>('a,button,input');
</script>

<div class="custom-select my-auto mb-3">
	<Select {items} {itemIdFn} {onFilterTextChange} {onSelectedChange} {navSelector} badgeClassName="badge text-bg-light d-flex align-items-center">
		<svelte:fragment slot="badgeLabel" let:itemContext let:widget>
			<a href={`${basePageUrl}${itemContext.item.pageid}`} target="_blank" rel="noreferrer">{itemContext.item.title}</a>
			<button
				type="button"
				class="btn-close ms-1 wiki-btn-close"
				aria-label="Close"
				on:click={(e) => widget.actions.onRemoveBadgeClick(e, itemContext.item)}
			></button>
		</svelte:fragment>
		<label for={'' + itemContext.id} slot="slotItem" let:itemContext>
			{@const item = itemContext.item}
			<div class="fw-bold">{item.title}</div>
			<div class="text-wrap wiki-desc">{item.snippet}</div>
		</label>
	</Select>

	<span class="fw-bold">Selection: </span>
	{#each selected as item}
		<a href={`${basePageUrl}${item.pageid}`} class="pe-2">{item.title}</a>
	{:else}
		none
	{/each}
</div>
