// react/demo/src/bootstrap/samples/slider/CoffeeSlider.tsx
import {useDirective} from '@agnos-ui/react-bootstrap/utils/directive';
import type {SliderContext} from '@agnos-ui/react-bootstrap/components/slider';

const CustomSliderComponent = ({state, directives}: SliderContext) => {
	return (
		<>
			<div className="position-relative cup-container">
				<div className="cup">
					<div className="cup-fill-parent">
						<div className="cup-fill" style={{height: `${state.progressDisplayOptions[0].height}%`}}>
							{state.progressDisplayOptions[0].height >= 50 ? (
								<>
									<div className="bubble bubble-1"></div>
									<div className="bubble bubble-2"></div>
									<div className="bubble bubble-3"></div>
								</>
							) : null}
						</div>
					</div>
				</div>
			</div>
			<button className="coffee-indicator" {...useDirective(directives.handleDirective, {item: state.sortedHandles[0]})}>
				{'' + state.sortedHandles[0].value}
			</button>
		</>
	);
};

export default CustomSliderComponent;

// angular/demo/bootstrap/src/app/samples/slider/coffee-slider.component.ts
import type {SliderWidget} from '@agnos-ui/angular-bootstrap';
import {SlotComponent, UseDirective} from '@agnos-ui/angular-bootstrap';
import {ChangeDetectionStrategy, Component, ViewEncapsulation} from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: {
		style: 'display: contents;',
	},
	imports: [UseDirective],
	template: `
		<div class="cup-container position-relative">
			<div class="cup">
				<div class="cup-fill-parent">
					<div class="cup-fill" [style.height.%]="state.progressDisplayOptions()[0].height">
						@if (state.progressDisplayOptions()[0].height >= 50) {
							<div class="bubble bubble-1"></div>
							<div class="bubble bubble-2"></div>
							<div class="bubble bubble-3"></div>
						}
					</div>
				</div>
			</div>
		</div>
		<button class="coffee-indicator" [auUse]="[directives.handleDirective, {item: state.sortedHandles()[0]}]">
			{{ '' + state.sortedHandles()[0].value }}
		</button>
	`,
	encapsulation: ViewEncapsulation.None,
})
export default class CoffeeSliderComponent extends SlotComponent<SliderWidget> {}
