// svelte/demo/src/bootstrap/samples/slider/Custom.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';
	import CustomHandle from './CustomHandle.svelte';

	let sliderCustomLabelControl = [70];
	let sliderCustomHandleControl = [50];

	import '@agnos-ui/common/samples/slider/custom.scss';
</script>

<h3>Slider with custom labels</h3>
<Slider
	min={0}
	max={100}
	stepSize={1}
	bind:values={sliderCustomLabelControl}
	label={({value}) => '' + value + '%'}
	className="au-custom-slider-container"
/>
<hr />
<h3>Slider with custom handle</h3>
<Slider min={0} max={100} stepSize={1} bind:values={sliderCustomHandleControl} handle={CustomHandle} className="au-custom-slider-container" />

// angular/demo/bootstrap/src/app/samples/slider/custom.route.ts
import {SliderComponent, SliderLabelDirective} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';
import {FormControl, ReactiveFormsModule} from '@angular/forms';
import CustomHandleSliderComponent from './custom-handle.component';

@Component({
	imports: [SliderComponent, SliderLabelDirective, ReactiveFormsModule],
	template: `
		<h5>Slider with custom labels</h5>
		<div auSlider auMin="0" auMax="100" auStepSize="1" [formControl]="sliderCustomLabelControl" auClassName="au-custom-slider-container">
			<ng-template auSliderLabel let-value="value">{{ value }}%</ng-template>
		</div>
		<hr />

		<h5>Slider with custom handle</h5>
		<div
			auSlider
			auMin="0"
			auMax="100"
			auStepSize="1"
			[formControl]="sliderCustomHandleControl"
			auClassName="au-custom-slider-container"
			[auHandle]="sliderCustomSlotHandle"
		></div>
	`,
	styles: "@use '@agnos-ui/common/samples/slider/custom.scss';",
})
export default class CustomSliderComponent {
	readonly sliderCustomSlotHandle = CustomHandleSliderComponent;

	sliderCustomLabelControl = new FormControl([70]);
	sliderCustomHandleControl = new FormControl([50]);
}
