// svelte/demo/src/bootstrap/samples/slider/Range.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';

	let sliderControl = [10, 40, 50, 60, 90];
	let sliderValues = [10, 40];
</script>

<h3>Slider with form control</h3>
<Slider min={0} max={100} stepSize={1} bind:values={sliderControl} />
Form control values: {sliderControl?.join(', ')}
<hr />

<h3>Slider with values</h3>
<Slider min={0} max={100} stepSize={1} bind:values={sliderValues} />
Values: {sliderValues.join(', ')}

// angular/demo/bootstrap/src/app/samples/slider/range.route.ts
import {AgnosUIAngularModule} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';

@Component({
	standalone: true,
	imports: [AgnosUIAngularModule, ReactiveFormsModule, FormsModule],
	template: `
		<h2>Slider with form control</h2>
		<div auSlider auMin="0" auMax="100" auStepSize="1" [formControl]="sliderControl"></div>
		Form control values: {{ sliderControl.value?.join(', ') }}
		<hr />

		<h2>Slider with values</h2>
		<div auSlider auMin="0" auMax="100" auStepSize="1" [(auValues)]="sliderValues"></div>
		Values: {{ sliderValues.join(', ') }}
	`,
})
export default class RangeSliderComponent {
	sliderControl = new FormControl([10, 40, 50, 60, 90]);
	sliderValues = [10, 40];
}
