// react/lib/pagination/Pagination.tsx
import type {PaginationContext, PaginationProps} from '@agnos-ui/react-headless';
import {Slot, createPagination, toSlotContextWidget, useWidgetWithConfig} from '@agnos-ui/react-headless';
import classNames from 'classnames';
import {NavButton, PageItem} from './PageItem';

export function DefaultPages(slotContext: PaginationContext) {
	const {widget, state} = slotContext;
	const jsxPages = [];
	for (let i = 0; i < state.pages.length; i++) {
		if (widget.api.isEllipsis(state.pages[i])) {
			jsxPages.push(
				<NavButton disabled={true} key={'Ellipsis' + i} tabIndex={-1} className={'au-ellipsis'}>
					<Slot slotContent={state.slotEllipsis} props={slotContext}></Slot>
				</NavButton>,
			);
		} else {
			jsxPages.push(
				<PageItem
					key={state.pages[i]}
					className={'au-page'}
					disabled={state.disabled}
					active={state.pages[i] === state.page}
					onClick={(e) => {
						widget.actions.select(state.pages[i]);
						e.preventDefault();
					}}
					ariaLabel={state.pagesLabel[i]}
					activeLabel={state.activeLabel}
				>
					<Slot slotContent={state.slotNumberLabel} props={{...slotContext, displayedPage: state.pages[i]}}></Slot>
				</PageItem>,
			);
		}
	}
	return jsxPages.length ? <>{jsxPages}</> : null;
}

const defaultConfig: Partial<PaginationProps> = {
	slotPages: DefaultPages,
};

// TODO discuss the extension of the props to the HTML UL one for react ?
export function Pagination(props: Partial<PaginationProps>) {
	const [state, widget] = useWidgetWithConfig(createPagination, props, 'pagination', defaultConfig);
	const slotContext: PaginationContext = {state, widget: toSlotContextWidget(widget)};
	const ItemsBefore = [];
	const ItemsAfter = [];

	if (state.boundaryLinks) {
		ItemsBefore.push(
			<NavButton
				key={'first'}
				className={'au-first'}
				ariaLabel={state.ariaFirstLabel}
				onClick={(e) => {
					widget.actions.first();
					e.preventDefault();
				}}
				disabled={state.previousDisabled}
			>
				<Slot slotContent={state.slotFirst} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.directionLinks) {
		ItemsBefore.push(
			<NavButton
				key={'prev'}
				className={'au-previous'}
				ariaLabel={state.ariaPreviousLabel}
				onClick={(e) => {
					widget.actions.previous();
					e.preventDefault();
				}}
				disabled={state.previousDisabled}
			>
				<Slot slotContent={state.slotPrevious} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.directionLinks) {
		ItemsAfter.push(
			<NavButton
				key={'next'}
				className={'au-next'}
				ariaLabel={state.ariaNextLabel}
				onClick={(e) => {
					widget.actions.next();
					e.preventDefault();
				}}
				disabled={state.nextDisabled}
			>
				<Slot slotContent={state.slotNext} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	if (state.boundaryLinks) {
		ItemsAfter.push(
			<NavButton
				key={'last'}
				className={'au-last'}
				ariaLabel={state.ariaLastLabel}
				onClick={(e) => {
					widget.actions.last();
					e.preventDefault();
				}}
				disabled={state.nextDisabled}
			>
				<Slot slotContent={state.slotLast} props={slotContext}></Slot>
			</NavButton>,
		);
	}
	return (
		<nav aria-label={state.ariaLabel}>
			<ul className={classNames('au-pagination', 'pagination', state.size ? `pagination-${state.size}` : '', state.className)}>
				{ItemsBefore}
				<Slot slotContent={state.slotPages} props={slotContext}></Slot>
				{ItemsAfter}
			</ul>
			<div aria-live="polite" className="visually-hidden">
				{state.page && `Current page is ${state.page}`}
			</div>
		</nav>
	);
}

// svelte/lib/src/pagination/Pagination.svelte
<script lang="ts" context="module">
	import type {PaginationProps as Props, PaginationSlots as Slots} from '@agnos-ui/svelte-headless';
	import {Slot, callWidgetFactory, createPagination, toSlotContextWidget} from '@agnos-ui/svelte-headless';
	import PaginationDefaultPages from './PaginationDefaultPages.svelte';

	const defaultConfig: Partial<Props> = {
		slotPages: PaginationDefaultPages,
	};
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Slots = Slots; // eslint-disable-line @typescript-eslint/no-unused-vars

	/**
	 *  The current page.
	 *
	 *  Page numbers start with `1`.
	 */
	export let page: Props['page'] | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createPagination,
		widgetName: 'pagination',
		$$slots,
		defaultConfig,
		events: {
			onPageChange: (value: number) => {
				page = value;
			},
		},
	});

	const {
		stores: {
			size$,
			page$,
			boundaryLinks$,
			directionLinks$,
			nextDisabled$,
			previousDisabled$,
			ariaLabel$,
			ariaFirstLabel$,
			ariaPreviousLabel$,
			ariaNextLabel$,
			ariaLastLabel$,
			className$,
			slotFirst$,
			slotPrevious$,
			slotNext$,
			slotLast$,
			slotPages$,
		},
		state$,
		actions: {first, previous, next, last},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);

	$: sizeClass = $size$ ? `pagination-${$size$}` : ''; // $size$ === 'sm' ? 'pagination-sm' : $size$ === 'lg' ? 'pagination-lg' : '';
	$: slotContext = {widget: toSlotContextWidget(widget), state: $state$};
</script>

<!-- Should we put nav here ? how to custom the class of ul in this case ?-->
<nav aria-label={$ariaLabel$}>
	<ul class="au-pagination pagination {sizeClass} {$className$}">
		{#if $boundaryLinks$}
			<li class="page-item" class:disabled={$previousDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaFirstLabel$}
					class="page-link au-first"
					href="#"
					on:click|preventDefault={() => first()}
					tabindex={$previousDisabled$ ? -1 : undefined}
					aria-disabled={$previousDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotFirst$} props={slotContext} let:component let:props>
							<slot slot="slot" name="first" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		{#if $directionLinks$}
			<li class="page-item" class:disabled={$previousDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaPreviousLabel$}
					class="page-link au-previous"
					href="#"
					on:click|preventDefault={() => previous()}
					tabindex={$previousDisabled$ ? -1 : undefined}
					aria-disabled={$previousDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotPrevious$} props={slotContext} let:component let:props>
							<slot slot="slot" name="previous" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		<Slot slotContent={$slotPages$} props={slotContext} let:component let:props>
			<slot slot="slot" name="pages" let:props {...props} />
			<svelte:component this={component} {...props}>
				<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
				<slot name="first" slot="first" let:state let:widget {state} {widget} />
				<slot name="last" slot="last" let:state let:widget {state} {widget} />
				<slot name="next" slot="next" let:state let:widget {state} {widget} />
				<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
				<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
				<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
			</svelte:component>
		</Slot>
		{#if $directionLinks$}
			<li class="page-item" class:disabled={$nextDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaNextLabel$}
					class="page-link au-next"
					href="#"
					on:click|preventDefault={() => next()}
					tabindex={$nextDisabled$ ? -1 : undefined}
					aria-disabled={$nextDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotNext$} props={slotContext} let:component let:props>
							<slot slot="slot" name="next" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
		{#if $boundaryLinks$}
			<li class="page-item" class:disabled={$nextDisabled$}>
				<!-- svelte-ignore a11y-invalid-attribute -->
				<a
					aria-label={$ariaLastLabel$}
					class="page-link au-last"
					href="#"
					on:click|preventDefault={() => last()}
					tabindex={$nextDisabled$ ? -1 : undefined}
					aria-disabled={$nextDisabled$ ? 'true' : null}
				>
					<span aria-hidden="true">
						<Slot slotContent={$slotLast$} props={slotContext} let:component let:props>
							<slot slot="slot" name="last" let:props {...props} />
							<svelte:component this={component} {...props}>
								<slot name="ellipsis" slot="ellipsis" let:state let:widget {state} {widget} />
								<slot name="first" slot="first" let:state let:widget {state} {widget} />
								<slot name="last" slot="last" let:state let:widget {state} {widget} />
								<slot name="next" slot="next" let:state let:widget {state} {widget} />
								<slot name="numberLabel" slot="numberLabel" let:displayedPage let:state let:widget {displayedPage} {state} {widget} />
								<slot name="pages" slot="pages" let:state let:widget {state} {widget} />
								<slot name="previous" slot="previous" let:state let:widget {state} {widget} />
							</svelte:component>
						</Slot>
					</span>
				</a>
			</li>
		{/if}
	</ul>
	<div aria-live="polite" class="visually-hidden">
		{`Current page is ${$page$}`}
	</div>
</nav>
