// angular/demo/src/app/samples/transition/collapse.component.ts
import {ChangeDetectionStrategy, Component, Input, booleanAttribute} from '@angular/core';
import {UseDirective, collapseVerticalTransition, createTransition, toAngularSignal} from '@agnos-ui/angular';

@Component({
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective],
	selector: 'app-collapse',
	template: `
		<div class="card">
			<div class="card-header p-0">
				<button
					type="button"
					id="collapse-toggle"
					(click)="transition.api.toggle()"
					class="btn toggle-button"
					aria-controls="collapse-content"
					[attr.aria-expanded]="state().visible"
				>
					{{ headerText }}
					<span class="ms-1 collapse-icon" [class.expanded]="state().visible">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 100 100">
							<rect class="horizontal" x="20" y="45" width="60" height="10" fill="currentColor" />
							<rect class="vertical" x="45" y="20" width="10" height="60" fill="currentColor" />
						</svg>
					</span>
				</button>
			</div>
			@if (!state().hidden) {
				<div [auUse]="transition.directives.directive" [auUseParams]="{visible: expanded}" id="collapse-content">
					<div class="card-body">
						<ng-content />
					</div>
				</div>
			}
		</div>
	`,
	styles: "@import '@agnos-ui/common/samples/transition/collapse.scss';",
})
export default class CollapseComponent {
	readonly transition = createTransition({
		props: {
			transition: collapseVerticalTransition,
		},
	});
	readonly state = toAngularSignal(this.transition.state$);

	@Input()
	headerText: string;

	@Input({transform: booleanAttribute})
	expanded = false;
}

// react/demo/src/bootstrap/samples/transition/Collapse.tsx
import {useMemo, type PropsWithChildren} from 'react';
import {createTransition, collapseVerticalTransition} from '@agnos-ui/react-bootstrap/transitions';
import {useDirective, useObservable} from '@agnos-ui/react-bootstrap/utils';
import type {Directive} from '@agnos-ui/react-bootstrap/types';
import '@agnos-ui/common/samples/transition/collapse.scss';
import CollapseIcon from '@agnos-ui/common/samples/transition/collapseButton.svg?react';

const CollapseContent = ({directive, children}: PropsWithChildren<{directive: Directive}>) => (
	<div id="collapse-content" {...useDirective(directive)}>
		<div className="card-body">{children}</div>
	</div>
);

const Collapse = ({expanded, headerText, children}: PropsWithChildren<{expanded?: boolean; headerText: string}>) => {
	const {
		state$,
		directives: {directive},
		api: {toggle},
	} = useMemo(
		() =>
			createTransition({
				props: {
					visible: expanded,
					transition: collapseVerticalTransition,
				},
			}),
		[],
	);
	const state = useObservable(state$);

	return (
		<div className="card">
			<div className="card-header p-0">
				<button
					type="button"
					id="collapse-toggle"
					onClick={() => toggle()}
					className="btn toggle-button"
					aria-controls="collapse-content"
					aria-expanded={state.visible || undefined}
				>
					{headerText}
					<span className={'ms-1 collapse-icon' + (state.visible ? ' expanded' : '')}>
						<CollapseIcon />
					</span>
				</button>
			</div>
			{!state.hidden && <CollapseContent directive={directive}>{children}</CollapseContent>}
		</div>
	);
};
export default Collapse;
