// angular/demo/bootstrap/src/app/samples/transition/flip.component.ts
import {Component, input} from '@angular/core';
import {UseDirective, createSimpleClassTransition, createTransition} from '@agnos-ui/angular-bootstrap';

@Component({
	imports: [UseDirective],
	selector: 'app-flip',
	template: `
		<div class="flip-card">
			<div class="flip-card-inner" [auUse]="transition.directives.directive">
				<div class="flip-card-front">
					<ng-content />
					<button class="btn btn-outline-secondary" (click)="transition.api.hide()">Hide again.</button>
				</div>
				<div class="flip-card-back">
					<button class="btn btn-outline-primary" (click)="transition.api.show()">{{ hiddenText() }}</button>
				</div>
			</div>
		</div>
	`,
	styles: "@use '@agnos-ui/common/samples/transition/flip.scss';",
})
export default class FlipComponent {
	readonly transition = createTransition({
		props: {
			visible: false,
			transition: createSimpleClassTransition({hideClasses: ['hide'], animationPendingHideClasses: ['hide']}),
		},
	});
	readonly hiddenText = input('');
}

// react/demo/src/bootstrap/samples/transition/Flip.tsx
import {useMemo, type PropsWithChildren} from 'react';
import {createSimpleClassTransition, createTransition} from '@agnos-ui/react-bootstrap/transitions';
import {useDirective} from '@agnos-ui/react-bootstrap/utils';
import '@agnos-ui/common/samples/transition/flip.scss';

const Flip = ({hiddenText, children}: PropsWithChildren<{hiddenText: string}>) => {
	const {
		directives: {directive},
		api: {hide, show},
	} = useMemo(
		() =>
			createTransition({
				props: {
					visible: false,
					transition: createSimpleClassTransition({hideClasses: ['hide'], animationPendingHideClasses: ['hide']}),
				},
			}),
		[],
	);

	return (
		<div className="flip-card">
			<div className="flip-card-inner" {...useDirective(directive)}>
				<div className="flip-card-front">
					{children}
					<button className="btn btn-outline-secondary" onClick={() => hide()}>
						Hide again.
					</button>
				</div>
				<div className="flip-card-back">
					<button className="btn btn-outline-primary" onClick={() => show()}>
						{hiddenText}
					</button>
				</div>
			</div>
		</div>
	);
};
export default Flip;
