// svelte/demo/src/daisyui/samples/slider/Slider.svelte
<script lang="ts">
	import {createSlider, type SliderProps} from '@agnos-ui/svelte-headless/components/slider';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {values = $bindable(), ...props}: Partial<Pick<SliderProps, 'min' | 'max' | 'values' | 'stepSize' | 'className'>> = $props();

	const {
		state,
		directives: {sliderDirective, clickableAreaDirective, handleEventsDirective},
	} = callWidgetFactory(createSlider, {
		get props() {
			return {...props, values};
		},
		events: {
			onValuesChange: (value: number[]) => {
				values = value;
			},
		},
	});
</script>

<input
	type="range"
	use:sliderDirective
	use:clickableAreaDirective
	use:handleEventsDirective={{item: {id: 0}}}
	min={state.min}
	max={state.max}
	value={state.sortedHandles[0].value}
	step={state.stepSize}
	class="range touch-none"
	aria-label={state.sortedHandles[0].ariaLabel}
/>

// react/demo/src/daisyui/samples/slider/Slider.tsx
import {type SliderProps, createSlider} from '@agnos-ui/react-headless/components/slider';
import {useWidget} from '@agnos-ui/react-headless/config';
import {useDirectives} from '@agnos-ui/react-headless/utils/directive';

export function Slider(props: Partial<Pick<SliderProps, 'min' | 'max' | 'values' | 'stepSize' | 'className' | 'onValuesChange'>>) {
	const {
		state,
		directives: {sliderDirective, clickableAreaDirective, handleEventsDirective},
	} = useWidget(createSlider, props);

	return (
		<input
			type="range"
			min={state.min}
			max={state.max}
			value={state.sortedHandles[0].value}
			onChange={() => null}
			step={state.stepSize}
			className="range"
			aria-label={state.sortedHandles[0].ariaLabel}
			{...useDirectives([sliderDirective, undefined], [clickableAreaDirective, undefined], [handleEventsDirective, {item: {id: 0}}])}
		/>
	);
}
