// svelte/bootstrap/src/components/toast/Toaster.svelte
<script lang="ts" module>
	const toaster = new ToasterService();
	const {addToast, removeToast, eventsDirective} = toaster;
	export {addToast};
</script>

<script lang="ts">
	import Toast from './Toast.svelte';
	import type {ToasterProps} from '@agnos-ui/svelte-headless/components/toast';
	import {ToasterService} from './toasterService';
	let {duration, position, limit, pauseOnHover, dismissible, closeAll, closeAllLabel}: ToasterProps = $props();
	$effect(() => {
		toaster.options.current = {duration, position, limit, pauseOnHover, dismissible, closeAll, closeAllLabel};
	});
</script>

<div class="au-toaster" aria-live="polite" aria-atomic="true">
	<div class={`au-toaster-container toast-container ${toaster.options.current.position}`}>
		{#if toaster.options.current.closeAll && toaster.toasts.current.length > 1}
			<div class="d-flex position-relative align-items-end pb-2">
				<button class="btn btn-secondary me-0 ms-auto pe-auto" onclick={() => toaster.closeAll()}
					>{toaster.options.current.closeAllLabel || 'Close all'}</button
				>
			</div>
		{/if}
		{#each toaster.toasts.current as { id, props: { className, visible, structure, children, header, dismissible, ariaCloseButtonLabel, animated, animatedOnInit, onShown, onHidden, onVisibleChange, transition } } (id)}
			<div use:eventsDirective={id}>
				<Toast
					{animated}
					{animatedOnInit}
					autoHide={false}
					{className}
					dismissible={dismissible ?? toaster.options.current.dismissible}
					{ariaCloseButtonLabel}
					{structure}
					{children}
					{header}
					{onShown}
					onHidden={() => {
						removeToast(id);
						if (onHidden) onHidden();
					}}
					{onVisibleChange}
					{visible}
					{transition}
				/>
			</div>
		{/each}
	</div>
</div>

// react/bootstrap/src/services/toaster.tsx
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import type {ToasterProps} from '@agnos-ui/react-headless/services/toaster';
import {ToasterProvider as ToasterProviderHeadless, useToaster as useToasterHeadless} from '@agnos-ui/react-headless/services/toaster';
import type {ToastProps} from '../components/toast/toast.gen';
import {Toast} from '../components/toast';
import {defaultToasterProps} from '@agnos-ui/react-headless/services/toaster';
export {defaultToasterProps};

interface ToastToasterProps extends Partial<ToastProps> {
	id: number;
	toaster: ReturnType<typeof useToaster>;
}

function ToastToaster({
	id,
	className,
	visible,
	structure,
	children,
	header,
	dismissible,
	ariaCloseButtonLabel,
	animated,
	animatedOnInit,
	onShown,
	onHidden,
	onVisibleChange,
	transition,
	toaster,
}: ToastToasterProps) {
	return (
		<div {...useDirective(toaster.eventsDirective, id)}>
			<Toast
				animated={animated}
				animatedOnInit={animatedOnInit}
				autoHide={false}
				className={className}
				dismissible={dismissible ?? toaster.options.dismissible}
				ariaCloseButtonLabel={ariaCloseButtonLabel}
				structure={structure}
				header={header}
				onShown={onShown}
				onHidden={() => {
					toaster.removeToast(id);
					if (onHidden) onHidden();
				}}
				onVisibleChange={onVisibleChange}
				visible={visible}
				transition={transition}
			>
				{children}
			</Toast>
		</div>
	);
}
/**
 * Toaster component that displays a list of toast notifications.
 *
 * This component uses the `useToaster` hook to manage the state of the toasts.
 * It renders a container with a list of toasts and an optional "Close all" button
 * if the `closeAll` option is enabled and there is more than one toast.
 *
 * @returns The rendered Toaster component.
 */
export function ToasterContainer() {
	const toaster = useToaster();
	return (
		<div className="au-toaster" aria-live="polite" aria-atomic="true">
			<div className={`au-toaster-container toast-container ${toaster.options.position}`}>
				{toaster.options.closeAll && toaster.toasts.length > 1 && (
					<div className="d-flex position-relative align-items-end pb-2">
						<button className="btn btn-secondary me-0 ms-auto pe-auto" onClick={() => toaster.closeAll()}>
							{toaster.options.closeAllLabel || 'Close all'}
						</button>
					</div>
				)}
				{toaster.toasts.map(({id, props}) => {
					return <ToastToaster key={id} id={id} {...props} toaster={toaster} />;
				})}
			</div>
		</div>
	);
}

/**
 * ToasterProvider component to provide toaster context to its children.
 * @param props - The properties object.
 * @param [props.options] - Optional toaster properties.
 * @param props.children - The children components.
 * @returns The ToasterProvider component.
 */
export const ToasterProvider = ({options, children}: {options: ToasterProps; children: React.ReactNode}) => {
	return (
		<ToasterProviderHeadless<Partial<ToastProps>> options={options}>
			{children}
			<ToasterContainer />
		</ToasterProviderHeadless>
	);
};

/**
 * Custom hook to use the toaster context.
 * @returns The toaster context.
 */
export const useToaster = () => {
	return useToasterHeadless<Partial<ToastProps>>();
};
