// svelte/demo/src/daisyui/samples/carousel/Slide.svelte
<script lang="ts">
	import type {Snippet} from 'svelte';
	import {getCarouselApiContext} from './carousel';
	import type {CarouselSlideProps} from '@agnos-ui/svelte-headless/components/carousel';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	const id = $props.id();
	let {children, ...slideProps}: Partial<CarouselSlideProps> & {children: Snippet} = $props();

	const {registerSlide} = getCarouselApiContext();
	const {
		directives: {root},
	} = callWidgetFactory({
		factory: registerSlide,
		get props() {
			return {...slideProps};
		},
		defaultConfig: {
			id,
		},
		enablePatchChanged: true,
	});
</script>

<div class="basis-full shrink-0 grow-0" use:root>
	{@render children()}
</div>

// angular/demo/daisyui/src/app/samples/carousel/slide.component.ts
import type {CarouselSlideWidget} from '@agnos-ui/angular-headless';
import {BaseWidgetDirective, callWidgetFactory, useDirectiveForHost} from '@agnos-ui/angular-headless';
import {Directive, inject} from '@angular/core';
import {CarouselComponent} from './carousel.component';

@Directive({
	selector: 'div[appSlide]',
	host: {
		class: 'basis-full shrink-0 grow-0',
	},
})
export class SlideDirective extends BaseWidgetDirective<CarouselSlideWidget> {
	constructor() {
		super(
			callWidgetFactory({
				factory: (arg) => inject(CarouselComponent).api.registerSlide(arg),
				afterInit: (widget) => {
					useDirectiveForHost(widget.directives.root);
				},
			}),
		);
	}
}
