// react/lib/Progressbar.tsx
import {type PropsWithChildren} from 'react';
import type {ProgressbarContext, ProgressbarProps} from '@agnos-ui/react-headless';
import {Slot, createProgressbar, toSlotContextWidget, useWidgetWithConfig} from '@agnos-ui/react-headless';

function DefaultSlotContent(slotContext: ProgressbarContext) {
	const classList = ['progress-bar'];
	if (slotContext.state.striped) {
		classList.push('progress-bar-striped');
	}
	if (slotContext.state.animated) {
		classList.push('progress-bar-animated');
	}
	if (slotContext.state.className) {
		classList.push(slotContext.state.className);
	}
	return (
		<div className="progress" style={{height: slotContext.state.height}}>
			<div className={classList.join(' ')} style={{width: `${slotContext.state.percentage}%`}}>
				<Slot slotContent={slotContext.state.slotDefault} props={slotContext} />
			</div>
		</div>
	);
}

const defaultConfig: Partial<ProgressbarProps> = {
	slotContent: DefaultSlotContent,
};

export const Progressbar = (props: PropsWithChildren<Partial<ProgressbarProps>>) => {
	const [state, widget] = useWidgetWithConfig(createProgressbar, props, 'progressbar', {...defaultConfig, slotDefault: props.children});
	const slotContext: ProgressbarContext = {state, widget: toSlotContextWidget(widget)};
	return (
		<div
			role="progressbar"
			aria-label={state.ariaLabel || undefined}
			aria-valuenow={state.value}
			aria-valuemin={state.min}
			aria-valuemax={state.max}
			aria-valuetext={state.ariaValueText}
		>
			<Slot slotContent={state.slotContent} props={slotContext} />
		</div>
	);
};

// svelte/lib/src/progressbar/Progressbar.svelte
<script lang="ts" context="module">
	import type {ProgressbarProps as Props, ProgressbarSlots as Slots} from '@agnos-ui/svelte-headless';
	import {Slot, callWidgetFactory, createProgressbar} from '@agnos-ui/svelte-headless';
	import ProgressbarDefaultContent from './ProgressbarDefaultContent.svelte';
	const defaultConfig: Partial<Props> = {
		slotContent: ProgressbarDefaultContent,
	};
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars
	type $$Slots = Slots; // eslint-disable-line @typescript-eslint/no-unused-vars
	export const widget = callWidgetFactory({factory: createProgressbar, widgetName: 'progressbar', $$slots, defaultConfig, events: {}});
	const {
		stores: {slotContent$, ariaLabel$, value$, min$, max$, ariaValueText$},
		state$,
	} = widget;

	$: widget.patchChangedProps($$props);

	$: slotContext = {widget, state: $state$};
</script>

<div
	role="progressbar"
	aria-label={$ariaLabel$ || undefined}
	aria-valuenow={$value$}
	aria-valuemin={$min$}
	aria-valuemax={$max$}
	aria-valuetext={$ariaValueText$}
>
	<Slot slotContent={$slotContent$} props={slotContext} let:component let:props>
		<slot slot="slot" name="content" let:props {...props} />
		<svelte:component this={component} {...props}>
			<svelte:fragment let:state let:widget><slot {state} {widget} /></svelte:fragment>
			<slot name="content" slot="content" let:state let:widget {state} {widget} />
		</svelte:component>
	</Slot>
</div>
