// angular/headless/src/utils/stores.ts
import type {ReadableSignal} from '@amadeus-it-group/tansu';
import type {Signal} from '@angular/core';
import {DestroyRef, inject, signal} from '@angular/core';
import {ZoneWrapper} from './zone';

export * from '@agnos-ui/core/utils/stores';

/**
 * Convert a tansu readable signal into an Angular signal.
 *
 * Note that as it uses Angular's `inject`, this can only be called at component construction time.
 *
 * @param tansuSignal - a tansu readable signal
 * @returns an angular signal
 */
export const toAngularSignal = <T>(tansuSignal: ReadableSignal<T>): Signal<T> => {
	const zoneWrapper = inject(ZoneWrapper);
	const res = signal(undefined as any as T);
	const subscription = zoneWrapper.outsideNgZone(tansuSignal.subscribe)((value) => {
		res.set(value);
		zoneWrapper.planNgZoneRun();
	});
	inject(DestroyRef).onDestroy(zoneWrapper.outsideNgZone(subscription));
	return res;
};

// react/headless/src/utils/stores.ts
import {findChangedProperties} from '@agnos-ui/core/utils/stores';
import type {ReadableSignal, WritableSignal} from '@amadeus-it-group/tansu';
import {asReadable, writable} from '@amadeus-it-group/tansu';
import {useEffect, useMemo, useRef, useState} from 'react';

export * from '@agnos-ui/core/utils/stores';

/**
 * Observe a readable store inside of a react component.
 *
 * @param store$ - the readable store
 * @returns the observed value of the store
 */
export function useObservable<T>(store$: ReadableSignal<T>) {
	const [value, setValue] = useState(() => store$());

	useEffect(() => {
		return store$.subscribe((arg) => {
			// We're passing an update function to setValue here instead of just doing setValue(arg) so that
			// if arg is a function, it is properly used as the value instead of being called as an update function
			setValue(() => arg);
		});
	}, [store$]);

	return value;
}

const propsEqual = <T extends object>(a: T, b: T) => !findChangedProperties(a, b);

/**
 * Turn react props into readable stores.
 *
 * @param props - the props
 * @returns the readable stores
 */
export const usePropsAsStore = <T extends object>(props?: Partial<T>): ReadableSignal<Partial<T>> => {
	const storeRef = useRef<WritableSignal<Partial<T>>>();
	if (!storeRef.current) {
		storeRef.current = writable({...props}, {equal: propsEqual});
	}
	useEffect(() => {
		storeRef.current!.set({...props});
	}, [props]);

	return useMemo(() => asReadable(storeRef.current!), [storeRef.current!]);
};
