// svelte/demo/src/app/samples/transition/InnerComponent.svelte
<script context="module" lang="ts">
	import {writable} from '@amadeus-it-group/tansu';
	import type {TransitionFn} from '@agnos-ui/svelte/services/transitions/baseTransitions';
	import {createTransition} from '@agnos-ui/svelte/services/transitions/baseTransitions';
	import {collapseHorizontalTransition, collapseVerticalTransition, fadeTransition} from '@agnos-ui/svelte/services/transitions/bootstrap';

	const paramTransition$ = writable(collapseVerticalTransition);
	const paramAnimation$ = writable(true);
	const paramAnimationOnInit$ = writable(false);
	const paramVisible$ = writable(true);
	const paramRemoveFromDom$ = writable(true);
</script>

<script lang="ts">
	const {
		stores: {visible$, transitioning$, shown$, hidden$},
		api: {toggle},
		directives: {directive},
		patch,
	} = createTransition({
		props: {
			animationOnInit: paramAnimationOnInit$,
			animation: paramAnimation$,
			visible: paramVisible$,
		},
	});

	const checkBoxVisible$ = {
		subscribe: visible$.subscribe,
		set: (value: boolean) => patch({visible: value}),
	};

	const changeTransition = (newTransition: TransitionFn) => {
		// Make sure the element is removed from the DOM
		// so that it does not keep state from the previous transition
		void toggle(false, false);
		$paramRemoveFromDom$ = true;
		$paramTransition$ = newTransition;
	};
</script>

<div class="transition-inner">
	<div class="h6 mt-2">Transition:</div>
	<div>
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === collapseVerticalTransition}
			on:click={() => changeTransition(collapseVerticalTransition)}>Vertical collapse</button
		>
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === collapseHorizontalTransition}
			on:click={() => changeTransition(collapseHorizontalTransition)}>Horizontal collapse</button
		>
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === fadeTransition}
			on:click={() => changeTransition(fadeTransition)}>Fade</button
		>
	</div>
	<div class="h6 mt-2">Other properties:</div>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramAnimation$} />Animation</label>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramAnimationOnInit$} />Animation on init</label>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramRemoveFromDom$} />Remove from DOM</label>
	<label class="form-check mb-2"><input type="checkbox" class="form-check-input" bind:checked={$checkBoxVisible$} />Visible</label>

	<div class="d-flex flex-wrap gap-2">
		<button type="button" class="btn btn-outline-primary" on:click={() => toggle()}>Toggle</button>
		<button type="button" class="btn btn-outline-primary" on:click={() => toggle(undefined, true)}>Toggle with animation</button>
		<button type="button" class="btn btn-outline-primary" on:click={() => toggle(undefined, false)}>Toggle without animation</button>
	</div>

	<ul class="mt-2">
		<li>visible = {$visible$}</li>
		<li>transitioning = {$transitioning$}</li>
		<li>shown = {$shown$}</li>
		<li>hidden = {$hidden$}</li>
	</ul>

	{#if !$paramRemoveFromDom$ || !$hidden$}
		<div use:directive={{transition: $paramTransition$, animation: $paramAnimation$}} style="max-width: 300px;">
			<div class="card" style="width: 300px;">
				<div class="card-body">You can collapse this card by clicking Toggle</div>
			</div>
		</div>
	{/if}
</div>

// react/demo/src/app/samples/transition/InnerComponent.tsx
import {writable} from '@amadeus-it-group/tansu';
import type {TransitionFn} from '@agnos-ui/react/services/transitions/baseTransitions';
import {collapseHorizontalTransition, collapseVerticalTransition, fadeTransition} from '@agnos-ui/react/services/transitions/bootstrap';
import {createTransition} from '@agnos-ui/react/services/transitions/baseTransitions';
import {useDirective} from '@agnos-ui/react/utils/directive';
import {useObservable} from '@agnos-ui/react/utils/stores';
import {useWidget} from '@agnos-ui/react/utils/widget';

const paramTransition$ = writable(collapseVerticalTransition);
const paramAnimation$ = writable(true);
const paramAnimationOnInit$ = writable(false);
const paramVisible$ = writable(true);
const paramRemoveFromDom$ = writable(true);

const InnerComponent = () => {
	const paramTransition = useObservable(paramTransition$);
	const paramAnimation = useObservable(paramAnimation$);
	const paramAnimationOnInit = useObservable(paramAnimationOnInit$);
	const paramRemoveFromDom = useObservable(paramRemoveFromDom$);
	const [transitionState, transitionWidget] = useWidget(
		createTransition,
		{},
		{
			props: {
				transition: paramTransition$,
				animation: paramAnimation$,
				animationOnInit: paramAnimationOnInit$,
				visible: paramVisible$,
			},
		},
	);
	const transitionRef = useDirective(transitionWidget.directives.directive);

	const changeTransition = (newTransition: TransitionFn) => {
		// Make sure the element is removed from the DOM
		// so that it does not keep state from the previous transition
		void transitionWidget.api.toggle(false, false);
		paramRemoveFromDom$.set(true);
		paramTransition$.set(newTransition);
	};

	return (
		<>
			<div className="transition-inner">
				<div className="h6 mt-2">Transition:</div>
				<div className="d-flex flex-wrap gap-2">
					<button
						type="button"
						className={`btn btn-sm btn-outline-secondary ${paramTransition === collapseVerticalTransition ? 'active' : ''}`}
						onClick={() => changeTransition(collapseVerticalTransition)}
					>
						Vertical collapse
					</button>
					<button
						type="button"
						className={`btn btn-sm btn-outline-secondary ${paramTransition === collapseHorizontalTransition ? 'active' : ''}`}
						onClick={() => changeTransition(collapseHorizontalTransition)}
					>
						Horizontal collapse
					</button>
					<button
						type="button"
						className={`btn btn-sm btn-outline-secondary ${paramTransition === fadeTransition ? 'active' : ''}`}
						onClick={() => changeTransition(fadeTransition)}
					>
						Fade
					</button>
				</div>
				<div className="h6 mt-2">Other properties:</div>
				<label className="form-check">
					<input type="checkbox" className="form-check-input" checked={paramAnimation} onChange={() => paramAnimation$.set(!paramAnimation)} />
					Animation
				</label>
				<label className="form-check">
					<input
						type="checkbox"
						className="form-check-input"
						checked={paramAnimationOnInit}
						onChange={() => paramAnimationOnInit$.set(!paramAnimationOnInit)}
					/>
					Animation on init
				</label>
				<label className="form-check">
					<input
						type="checkbox"
						className="form-check-input"
						checked={paramRemoveFromDom}
						onChange={() => paramRemoveFromDom$.set(!paramRemoveFromDom)}
					/>
					Remove from DOM
				</label>
				<label className="form-check mb-2">
					<input
						type="checkbox"
						className="form-check-input"
						checked={transitionState.visible}
						onChange={() => transitionWidget.patch({visible: !transitionState.visible})}
					/>
					Visible
				</label>

				<div className="d-flex flex-wrap gap-2">
					<button type="button" className="btn btn-outline-primary" onClick={() => transitionWidget.api.toggle()}>
						Toggle
					</button>
					<button type="button" className="btn btn-outline-primary" onClick={() => transitionWidget.api.toggle(undefined, true)}>
						Toggle with animation
					</button>
					<button type="button" className="btn btn-outline-primary" onClick={() => transitionWidget.api.toggle(undefined, false)}>
						Toggle without animation
					</button>
				</div>
				<ul className="mt-2">
					<li>visible = {transitionState.visible + ''}</li>
					<li>transitioning = {transitionState.transitioning + ''}</li>
					<li>shown = {transitionState.shown + ''}</li>
					<li>hidden = {transitionState.hidden + ''}</li>
				</ul>

				{paramRemoveFromDom && transitionState.hidden ? null : (
					<div ref={transitionRef} style={{maxWidth: '300px'}}>
						<div className="card" style={{width: '300px'}}>
							<div className="card-body">You can collapse this card by clicking Toggle</div>
						</div>
					</div>
				)}
			</div>
		</>
	);
};
export default InnerComponent;
