// react/demo/src/daisyui/samples/pagination/Pagination.tsx
import {type PaginationProps, createPagination} from '@agnos-ui/react-headless/components/pagination';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import clsx from 'clsx';

export function Pagination(props: Partial<PaginationProps>) {
	const {
		state,
		api: {first, last, next, previous, select},
	} = useWidgetWithConfig(createPagination, props, 'pagination');

	return (
		<nav aria-label={state.ariaLabel}>
			<div className={clsx('join', state.className)}>
				{state.boundaryLinks && (
					<button
						className="join-item btn"
						aria-label={state.ariaFirstLabel}
						onClick={() => first()}
						disabled={state.previousDisabled}
						aria-disabled={state.previousDisabled ? 'true' : undefined}
						tabIndex={state.previousDisabled ? -1 : undefined}
					>
						<span aria-hidden="true"> « </span>
					</button>
				)}
				{state.directionLinks && (
					<button
						className="join-item btn"
						disabled={state.previousDisabled}
						aria-label={state.ariaPreviousLabel}
						onClick={() => previous()}
						tabIndex={state.previousDisabled ? -1 : undefined}
						aria-disabled={state.previousDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> ‹ </span>
					</button>
				)}
				{state.pages.map((page) => (
					<button
						key={page}
						className={clsx('join-item', 'btn', page === state.page && 'btn-active')}
						aria-current={page === state.page ? 'page' : undefined}
						tabIndex={page === -1 ? -1 : state.disabled ? -1 : undefined}
						onClick={page === -1 ? () => {} : () => select(page)}
						disabled={page === -1 || state.disabled}
					>
						{page}
						{state.page === page && <span className="sr-only">{state.activeLabel}</span>}
					</button>
				))}
				{state.directionLinks && (
					<button
						className="join-item btn"
						disabled={state.nextDisabled}
						aria-label={state.ariaNextLabel}
						onClick={() => next()}
						tabIndex={state.nextDisabled ? -1 : undefined}
						aria-disabled={state.nextDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> › </span>
					</button>
				)}
				{state.boundaryLinks && (
					<button
						className="join-item btn"
						aria-label={state.ariaLastLabel}
						onClick={() => last()}
						disabled={state.nextDisabled}
						tabIndex={state.nextDisabled ? -1 : undefined}
						aria-disabled={state.nextDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> » </span>
					</button>
				)}
			</div>
			<div aria-live="polite" className="sr-only">
				{`${state.ariaLiveLabelText}`}
			</div>
		</nav>
	);
}

// svelte/demo/src/daisyui/samples/pagination/Pagination.svelte
<script lang="ts">
	import type {PaginationProps} from '@agnos-ui/svelte-headless/components/pagination';
	import {createPagination} from '@agnos-ui/svelte-headless/components/pagination';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let {page = $bindable(), ...props}: Partial<PaginationProps> = $props();

	const {
		state,
		api: {first, previous, next, last, select},
	} = callWidgetFactory(createPagination, {
		get props() {
			return {...props, page};
		},
		events: {
			onPageChange: (value: number) => {
				page = value;
			},
		},
	});
</script>

<nav aria-label={state.ariaLabel}>
	<div class="join {state.className}">
		{#if state.boundaryLinks}
			<button
				class="join-item btn"
				aria-label={state.ariaFirstLabel}
				onclick={() => first()}
				disabled={state.previousDisabled}
				aria-disabled={state.previousDisabled ? 'true' : null}
				tabindex={state.previousDisabled ? -1 : undefined}
			>
				<span aria-hidden="true"> « </span>
			</button>
		{/if}
		{#if state.directionLinks}
			<button
				class="join-item btn"
				disabled={state.previousDisabled}
				aria-label={state.ariaPreviousLabel}
				onclick={() => previous()}
				tabindex={state.previousDisabled ? -1 : undefined}
				aria-disabled={state.previousDisabled ? 'true' : null}
			>
				<span aria-hidden="true"> ‹ </span>
			</button>
		{/if}
		{#each state.pages as page}
			<button
				class={['join-item btn', page === state.page && 'btn-active']}
				aria-current={page === state.page ? 'page' : null}
				tabindex={page === -1 ? -1 : state.disabled ? -1 : undefined}
				onclick={page === -1 ? () => {} : () => select(page)}
				disabled={page === -1 || state.disabled}
				>{page}
				{#if state.page === page}<span class="sr-only">{state.activeLabel}</span>{/if}
			</button>
		{/each}
		{#if state.directionLinks}
			<button
				class="join-item btn"
				disabled={state.nextDisabled}
				aria-label={state.ariaNextLabel}
				onclick={() => next()}
				tabindex={state.nextDisabled ? -1 : undefined}
				aria-disabled={state.nextDisabled ? 'true' : null}
			>
				<span aria-hidden="true"> › </span>
			</button>
		{/if}
		{#if state.boundaryLinks}
			<button
				class="join-item btn"
				aria-label={state.ariaLastLabel}
				onclick={() => last()}
				disabled={state.nextDisabled}
				tabindex={state.nextDisabled ? -1 : undefined}
				aria-disabled={state.nextDisabled ? 'true' : null}
			>
				<span aria-hidden="true"> » </span>
			</button>
		{/if}
	</div>
	<div aria-live="polite" class="sr-only">
		{`${state.ariaLiveLabelText}`}
	</div>
</nav>
