// svelte/lib/src/components/rating/Rating.svelte
<script lang="ts" context="module">
	import type {RatingProps as Props, RatingSlots as Slots} from '@agnos-ui/svelte-headless/components/rating';
	import {createRating} from '@agnos-ui/svelte-headless/components/rating';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Slots = Slots; // eslint-disable-line @typescript-eslint/no-unused-vars

	export let rating: number | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		$$slots,
		$$props,
		events: {
			onRatingChange: (value: number) => {
				rating = value;
			},
		},
	});

	const {
		stores: {
			tabindex$,
			maxRating$,
			visibleRating$,
			ariaValueText$,
			readonly$,
			disabled$,
			isInteractive$,
			stars$,
			className$,
			slotStar$,
			ariaLabel$,
			ariaLabelledBy$,
		},
		actions: {handleKey, leave, hover, click},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);
</script>

<div
	role="slider"
	class="d-inline-flex au-rating {$className$}"
	tabindex={$tabindex$}
	aria-valuemin={0}
	aria-valuemax={$maxRating$}
	aria-valuenow={$visibleRating$}
	aria-valuetext={$ariaValueText$}
	aria-readonly={$readonly$ || undefined}
	aria-disabled={$disabled$ || undefined}
	aria-label={$ariaLabel$ || undefined}
	aria-labelledby={$ariaLabelledBy$ || undefined}
	on:keydown={handleKey}
	on:mouseleave={leave}
>
	<!-- on:blur={onTouched} ?? -->
	{#each $stars$ as { fill, index }}
		<span class="visually-hidden">({index < $visibleRating$ ? '*' : ' '})</span>
		<!-- svelte-ignore a11y-click-events-have-key-events -->
		<!-- svelte-ignore a11y-no-static-element-interactions -->
		<span
			class="au-rating-star"
			style:cursor={$isInteractive$ ? 'pointer' : 'default'}
			on:mouseenter={() => hover(index + 1)}
			on:click={() => click(index + 1)}
		>
			<Slot slotContent={$slotStar$} props={{fill, index}} let:component let:props>
				<slot slot="slot" name="star" let:props {...props} />
				<svelte:component this={component} {...props} />
			</Slot>
		</span>
	{/each}
</div>

// react/lib/Rating.tsx
import {Slot} from '@agnos-ui/react-headless/Slot';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {createRating, type RatingProps} from '@agnos-ui/react-headless/rating';
import React from 'react';

export * from '@agnos-ui/react-headless/rating';

export function Rating(props: Partial<RatingProps>) {
	const [
		{tabindex, maxRating, visibleRating, ariaValueText, readonly, disabled, isInteractive, stars, className, slotStar, ariaLabel, ariaLabelledBy},
		widget,
	] = useWidgetWithConfig(createRating, props, 'rating');

	const starStyle = {
		cursor: isInteractive ? 'pointer' : 'default',
	};

	return (
		<div
			role="slider"
			className={`d-inline-flex au-rating ${className}`}
			tabIndex={tabindex}
			aria-valuemin={0}
			aria-valuemax={maxRating}
			aria-valuenow={visibleRating}
			aria-valuetext={ariaValueText}
			aria-readonly={readonly || undefined}
			aria-disabled={disabled || undefined}
			aria-label={ariaLabel || undefined}
			aria-labelledby={ariaLabelledBy || undefined}
			onKeyDown={(e) => widget.actions.handleKey(e as unknown as KeyboardEvent)}
			onMouseLeave={widget.actions.leave}
		>
			{stars.map((star) => (
				<React.Fragment key={star.index}>
					<span className="visually-hidden">({star.index < visibleRating ? '*' : ' '})</span>
					<span
						className="au-rating-star"
						style={starStyle}
						onMouseEnter={() => widget.actions.hover(star.index + 1)}
						onClick={() => widget.actions.click(star.index + 1)}
					>
						<Slot slotContent={slotStar} props={star}></Slot>
					</span>
				</React.Fragment>
			))}
		</div>
	);
}
