// angular/demo/daisyui/src/app/samples/progressbar/progressbar.component.ts
import {
	BaseWidgetDirective,
	auNumberAttribute,
	callWidgetFactory,
	type ProgressbarWidget,
	createProgressbar,
	type ProgressbarProps,
	UseDirective,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';

@Component({
	selector: 'app-progressbar',
	standalone: true,
	imports: [UseDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<progress
		class="progress"
		[class]="state().className"
		[auUse]="widget.directives.ariaDirective"
		[attr.value]="state().value"
		[attr.max]="state().max"
	></progress>`,
})
export class ProgressbarComponent extends BaseWidgetDirective<ProgressbarWidget> {
	@Input({transform: auNumberAttribute}) max?: ProgressbarProps['max'];
	@Input({transform: auNumberAttribute}) value?: ProgressbarProps['value'];
	@Input() ariaLabel?: ProgressbarProps['ariaLabel'];
	@Input() className?: ProgressbarProps['className'];
	@Input() ariaValueTextFn?: ProgressbarProps['ariaValueTextFn'];

	readonly _widget = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
	});
}

// react/demo/src/daisyui/samples/progressbar/Progressbar.tsx
import {type ProgressbarProps, createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';

export function Progressbar(props: Partial<Pick<ProgressbarProps, 'max' | 'ariaLabel' | 'value' | 'className' | 'ariaValueTextFn'>>) {
	const [state, widget] = useWidgetWithConfig(createProgressbar, props, 'progressbar');
	return (
		<progress
			className={classNames('progress', state.className)}
			value={state.value}
			max={state.max}
			{...useDirective(widget.directives.ariaDirective)}
		/>
	);
}
