// svelte/demo/src/daisyui/samples/progressbar/Progressbar.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	let props: Partial<Omit<ProgressbarProps, 'min'>> = $props();

	const {
		state,
		directives: {ariaDirective},
	} = callWidgetFactory(createProgressbar, {
		props,
	});
</script>

<progress use:ariaDirective class="progress {state.className}" value={state.value} max={state.max}></progress>

// react/demo/src/daisyui/samples/progressbar/Progressbar.tsx
import {type ProgressbarProps, createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import classNames from 'classnames';

export function Progressbar(props: Partial<Omit<ProgressbarProps, 'min'>>) {
	const {state, directives} = useWidgetWithConfig(createProgressbar, props, 'progressbar');
	return (
		<progress className={classNames('progress', state.className)} value={state.value} max={state.max} {...useDirective(directives.ariaDirective)} />
	);
}
