// svelte/demo/src/bootstrap/samples/tree/Basic.route.svelte
<script lang="ts">
	import {Tree, type TreeItem} from '@agnos-ui/svelte-bootstrap/components/tree';

	const nodes: TreeItem[] = [
		{
			label: 'Node 1',
			isExpanded: true,
			children: [
				{
					label: 'Node 1.1',
					children: [
						{
							label: 'Node 1.1.1',
						},
					],
				},
				{
					label: 'Node 1.2',
					children: [
						{
							label: 'Node 1.2.1',
						},
					],
				},
			],
		},
	];
</script>

<Tree {nodes} />

// angular/demo/bootstrap/src/app/samples/tree/basic.route.ts
import {TreeComponent, type TreeItem} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';

@Component({
	template: ` <au-component auTree [auNodes]="nodes" /> `,
	imports: [TreeComponent],
})
export default class BasicTreeComponent {
	readonly nodes: TreeItem[] = [
		{
			label: 'Node 1',
			isExpanded: true,
			children: [
				{
					label: 'Node 1.1',
					children: [
						{
							label: 'Node 1.1.1',
						},
					],
				},
				{
					label: 'Node 1.2',
					children: [
						{
							label: 'Node 1.2.1',
						},
					],
				},
			],
		},
	];
}
