// angular/demo/daisyui/src/app/samples/progressbar/radial-progress.component.ts
import {
	BaseWidgetDirective,
	auNumberAttribute,
	callWidgetFactory,
	type ProgressbarWidget,
	createProgressbar,
	type ProgressbarProps,
	UseDirective,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, Input} from '@angular/core';

@Component({
	selector: 'app-radial-progress',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective],
	template: ` <div
		class="radial-progress"
		[class]="state().className"
		[style.--thickness]="'0.4rem'"
		[style.--value]="state().percentage"
		[auUse]="widget.directives.ariaDirective"
	>
		{{ percentFormat.format(state().percentage / 100) }}
	</div>`,
})
export class RadialProgressComponent extends BaseWidgetDirective<ProgressbarWidget> {
	@Input({transform: auNumberAttribute}) min?: ProgressbarProps['min'];
	@Input({transform: auNumberAttribute}) max?: ProgressbarProps['max'];
	@Input({transform: auNumberAttribute}) value?: ProgressbarProps['value'];
	@Input() ariaLabel?: ProgressbarProps['ariaLabel'];
	@Input() className?: ProgressbarProps['className'];
	@Input() ariaValueTextFn?: ProgressbarProps['ariaValueTextFn'];

	readonly _widget = callWidgetFactory({
		factory: createProgressbar,
		widgetName: 'progressbar',
		defaultConfig: {},
		events: {},
	});
	readonly percentFormat = new Intl.NumberFormat('default', {
		style: 'percent',
		minimumFractionDigits: 0,
		maximumFractionDigits: 1,
	});
}

// svelte/demo/src/daisyui/samples/progressbar/RadialProgress.svelte
<script lang="ts">
	import {createProgressbar, type ProgressbarProps as Props} from '@agnos-ui/svelte-headless/components/progressbar';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	type $$Props = Partial<Pick<Props, 'min' | 'max' | 'ariaLabel' | 'value' | 'className' | 'ariaValueTextFn'>>;

	const widget = callWidgetFactory({factory: createProgressbar, widgetName: 'progressbar', $$slots: {}, $$props, events: {}});
	export const api = widget.api;

	const {
		stores: {className$, percentage$},
		directives: {ariaDirective},
	} = widget;
	$: widget.patchChangedProps($$props);

	const percentFormat = new Intl.NumberFormat('default', {
		style: 'percent',
		minimumFractionDigits: 0,
		maximumFractionDigits: 1,
	});
</script>

<div use:ariaDirective class="radial-progress {$className$}" style="--thickness: 0.4rem; --value:{$percentage$};">
	{percentFormat.format($percentage$ / 100)}
</div>
