// react/demo/app/samples/progressbar/Custom.route.tsx
import type {AdaptSlotContentProps, ProgressbarContext} from '@agnos-ui/react';
import {Progressbar} from '@agnos-ui/react';
import {useEffect, useState} from 'react';
import '@agnos-ui/common/samples/progressbar/custom.scss';

const CustomContent = ({state}: AdaptSlotContentProps<ProgressbarContext>) => (
	<div className="position-relative" style={{height: '300px'}}>
		<div className="cup">
			<div className="cup-fill-parent">
				<div className="cup-fill" style={{height: `${1.7 * state.percentage}px`}}>
					{state.percentage >= 50 ? (
						<>
							<div className="bubble bubble-1"></div>
							<div className="bubble bubble-2"></div>
							<div className="bubble bubble-3"></div>
						</>
					) : null}
				</div>
			</div>
		</div>
	</div>
);

const CustomDemo = () => {
	const [value, setValue] = useState(0);
	const [running, setRunning] = useState(false);
	useEffect(() => {
		const interval = setInterval(() => {
			if (running && value < 100) {
				setValue(value + 10);
			}
		}, 500);
		return () => clearInterval(interval);
	}, [running, value]);
	const start = () => {
		setRunning(true);
	};
	const toggle = () => {
		setRunning(!running);
	};
	const reset = () => {
		setValue(0);
		setRunning(false);
	};

	return (
		<div className="d-flex align-items-center flex-wrap">
			<div style={{width: '350px'}}>
				<Progressbar value={value} slotContent={CustomContent} />
			</div>
			<div className="d-flex flex-column justify-content-evenly h-100 ms-5">
				<div className="btn-group" role="group">
					<button className="btn btn-outline-primary" disabled={value > 0} onClick={start}>
						Start
					</button>
					<button className="btn btn-outline-primary" disabled={value === 0 || value >= 100} onClick={toggle}>
						{running ? 'Pause' : 'Resume'}
					</button>
					<button className="btn btn-outline-primary" disabled={value === 0} onClick={reset}>
						Reset
					</button>
				</div>
				<p className="mt-3">
					<span>{value === 0 ? 'Need to wake up.' : value < 100 ? `Retrieving coffee... ${value}%` : 'Ready to work !'}</span>
				</p>
			</div>
		</div>
	);
};
export default CustomDemo;

// angular/demo/src/app/samples/progressbar/custom.route.ts
import {ProgressbarComponent, ProgressbarContentDirective} from '@agnos-ui/angular';
import {NgIf} from '@angular/common';
import type {OnDestroy} from '@angular/core';
import {Component} from '@angular/core';
import type {Subscription} from 'rxjs';
import {interval, takeWhile} from 'rxjs';

@Component({
	standalone: true,
	imports: [ProgressbarComponent, ProgressbarContentDirective, NgIf],
	template: `
		<div class="d-flex align-items-center flex-wrap">
			<div style="width: 350px">
				<div au-progressbar #progressbar [value]="value">
					<ng-template auProgressbarContent let-state="state">
						<div class="position-relative" style="height: 300px">
							<div class="cup">
								<div class="cup-fill-parent">
									<div class="cup-fill" [style.height.px]="value * 1.7">
										<div class="bubble bubble-1" *ngIf="value >= 50"></div>
										<div class="bubble bubble-2" *ngIf="value >= 50"></div>
										<div class="bubble bubble-3" *ngIf="value >= 50"></div>
									</div>
								</div>
							</div>
						</div>
					</ng-template>
				</div>
			</div>
			<div class="d-flex flex-column justify-content-evenly h-100 ms-5">
				<div class="btn-group" role="group">
					<button class="btn btn-outline-primary" (click)="start()" [disabled]="progressbar.state().started">Start</button>
					<button
						class="btn btn-outline-primary"
						[disabled]="!progressbar.state().started || progressbar.state().finished"
						(click)="toggleProgress()"
					>
						{{ subscription ? 'Pause' : 'Resume' }}
					</button>
					<button class="btn btn-outline-primary" [disabled]="!progressbar.state().started" (click)="stop(true)">Reset</button>
				</div>
				<p class="mt-3">
					<span>{{ value === 0 ? 'Need to wake up.' : value < 100 ? 'Retrieving coffee... ' + value + '%' : 'Ready to work !' }}</span>
				</p>
			</div>
		</div>
	`,
	styles: ["@import '@agnos-ui/common/samples/progressbar/custom.scss';"],
})
export default class DefaultProgressBarComponent implements OnDestroy {
	value = 0;
	subscription: Subscription | undefined;

	start() {
		if (!this.subscription) {
			this.subscription = interval(500)
				.pipe(takeWhile(() => this.value < 100))
				.subscribe(() => {
					this.value += 10;
				});
		}
	}
	stop(reset = false) {
		this.subscription?.unsubscribe();
		this.subscription = undefined;
		if (reset) {
			this.value = 0;
		}
	}
	toggleProgress() {
		if (this.subscription) {
			this.stop();
		} else {
			this.start();
		}
	}
	ngOnDestroy() {
		this.stop();
	}
}
