// svelte/demo/src/bootstrap/samples/accordion/TogglePanels.route.svelte
<script lang="ts">
	import {Accordion, AccordionItem} from '@agnos-ui/svelte-bootstrap/components/accordion';
	import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';

	let accordion: Accordion;
	let secondAccordionItem: AccordionItem;
</script>

<Accordion bind:this={accordion}>
	<AccordionItem id="first" header="First panel">{BODY}</AccordionItem>
	<AccordionItem id="second" header="Second panel" bind:this={secondAccordionItem}>{BODY}</AccordionItem>
</Accordion>
<hr />
<div class="d-flex flex-wrap gap-2">
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.toggle('first')}>Toggle first</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => secondAccordionItem.api.toggle()}>Toggle second</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.expandAll()}>Expand all</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.collapseAll()}>Collapse all</button>
</div>

// react/demo/src/bootstrap/samples/accordion/TogglePanels.route.tsx
import type {AccordionApi, AccordionItemApi} from '@agnos-ui/react-bootstrap/components/accordion';
import {Accordion, AccordionItem} from '@agnos-ui/react-bootstrap/components/accordion';
import {useRef} from 'react';
import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';

export default () => {
	const refAccordion = useRef<AccordionApi>(null);
	const refSecondPanel = useRef<AccordionItemApi>(null);
	return (
		<>
			<Accordion ref={refAccordion}>
				<AccordionItem header="First panel" id={'first'}>
					{BODY}
				</AccordionItem>
				<AccordionItem header="Second panel" id={'second'} ref={refSecondPanel}>
					{BODY}
				</AccordionItem>
			</Accordion>
			<hr />
			<div className="d-flex flex-wrap gap-2">
				<button className="btn btn-sm btn-outline-primary" onClick={() => refAccordion.current?.toggle('first')}>
					Toggle first
				</button>
				<button className="btn btn-sm btn-outline-primary" onClick={() => refSecondPanel.current?.toggle()}>
					Toggle second
				</button>
				<button className="btn btn-sm btn-outline-primary" onClick={() => refAccordion.current?.expandAll()}>
					Expand all
				</button>
				<button className="btn btn-sm btn-outline-primary" onClick={() => refAccordion.current?.collapseAll()}>
					Collapse all
				</button>
			</div>
		</>
	);
};
