// svelte/demo/src/bootstrap/samples/transition/Transition.route.svelte
<script lang="ts">
	import InnerComponent from './InnerComponent.svelte';

	let showComponent = true;
</script>

<div class="demo-transition mb-3">
	<button id="toggle-component" class="btn btn-outline-secondary" on:click={() => (showComponent = !showComponent)}>Toggle component</button>
	{#if showComponent}
		<InnerComponent />
	{/if}
</div>

// angular/demo/bootstrap/src/app/samples/transition/transition.route.ts
import {Component, signal} from '@angular/core';
import {InnerComponent} from './innerComponent.component';

@Component({
	imports: [InnerComponent],
	template: `
		<div class="demo-transition mb-3">
			<button id="toggle-component" class="btn btn-outline-secondary" (click)="showComponent.update((val) => !val)">Toggle component</button>
			@if (showComponent()) {
				<app-transition-inner />
			}
		</div>
	`,
})
export default class TransitionComponent {
	readonly showComponent = signal(true);
}
