// svelte/demo/src/bootstrap/samples/carousel/AutoplayNavigation.svelte
<script lang="ts" generics="SlideData extends {id: string;}">
	import type {CarouselContext} from '@agnos-ui/svelte-bootstrap/components/carousel';

	import playSvg from 'bootstrap-icons/icons/play-fill.svg?raw';
	import pauseSvg from 'bootstrap-icons/icons/pause-fill.svg?raw';
	import {on} from 'svelte/events';

	let {state: cState, directives, api, isPlaying = $bindable()}: CarouselContext<SlideData> & {isPlaying: boolean} = $props();

	const onpointerdown = (e: PointerEvent) => {
		e.preventDefault();
	};
	const notouchstart = (node: HTMLDivElement) => ({
		destroy: on(node, 'touchstart', (e: TouchEvent) => {
			e.stopPropagation();
		}),
	});
	const onclick = () => {
		if (isPlaying) {
			api.plugins()!.autoplay.stop();
		} else {
			api.plugins()!.autoplay.play();
		}
	};

	let progressbar: HTMLDivElement;

	$effect(() => {
		if (cState.initialized) {
			api
				.emblaApi()!
				.on('autoplay:play', () => {
					isPlaying = true;
				})
				.on('autoplay:stop', () => {
					isPlaying = false;
				})
				.on('autoplay:timerset', (api) => {
					progressbar.style.transition = 'none';
					progressbar.style.width = '0%';
					window.requestAnimationFrame(() => {
						window.setTimeout(() => {
							progressbar.style.transition = `width ${api.plugins().autoplay.timeUntilNext()}ms linear`;
							progressbar.style.width = '100%';
						});
					});
				})
				.on('autoplay:timerstopped', () => {
					progressbar.style.transition = 'none';
					progressbar.style.width = '0%';
				});
		}
	});
</script>

<div class="navigation">
	<div class="d-flex bg-light rounded-4 py-1 px-2" {onpointerdown} use:notouchstart>
		<button
			type="button"
			class="btn btn-sm btn-outline-primary rounded-5 d-flex align-items-center"
			{onclick}
			aria-label={isPlaying ? 'Pause rotation of slides' : 'Play rotation of slides'}
		>
			{@html isPlaying ? pauseSvg : playSvg}
		</button>
	</div>
	<div class="d-flex bg-light rounded-4 py-1 px-3 align-items-center" {onpointerdown} use:notouchstart>
		<div class="pagination pagination-sm align-items-center" use:directives.tabList>
			{#each cState.slidesData as slideData, index (slideData.id)}
				<div class="page-item">
					<button
						type="button"
						class={['page-link', cState.selectedScrollSnap === index && 'active']}
						use:directives.tabIndicator={{index, id: slideData.id}}
					>
						{index + 1}
					</button>
				</div>
			{/each}
		</div>
	</div>
</div>
<div class={['progress-container', 'd-none', 'd-sm-flex', !isPlaying && 'opacity-0']} aria-hidden="true">
	<div class="bg-light rounded-4 py-1 px-3 w-100 d-flex align-items-center">
		<div class="progress w-100">
			<div class="autoplay-progress-bar progress-bar" bind:this={progressbar}></div>
		</div>
	</div>
</div>

// angular/demo/bootstrap/src/app/samples/carousel/autoplay-navigation.component.ts
import {UseDirective, type CarouselContext} from '@agnos-ui/angular-bootstrap';
import type {ElementRef} from '@angular/core';
import {Component, effect, inject, input, output, signal, viewChild} from '@angular/core';
import playSvg from 'bootstrap-icons/icons/play-fill.svg';
import pauseSvg from 'bootstrap-icons/icons/pause-fill.svg';
import {DomSanitizer} from '@angular/platform-browser';

@Component({
	selector: 'app-autoplay-navigation',
	template: `
		<div class="navigation">
			<div class="d-flex bg-light rounded-4 py-1 px-2" (pointerdown)="$event.preventDefault()" (touchstart)="$event.stopPropagation()">
				<button
					type="button"
					class="btn btn-sm btn-outline-primary rounded-5 d-flex align-items-center"
					(click)="onClick()"
					[attr.aria-label]="isPlaying() ? 'Pause rotation of slides' : 'Play rotation of slides'"
					[innerHTML]="isPlaying() ? pauseSvg : playSvg"
				></button>
			</div>
			<div
				class="d-flex bg-light rounded-4 py-1 px-3 align-items-center"
				(pointerdown)="$event.preventDefault()"
				(touchstart)="$event.stopPropagation()"
			>
				<div class="pagination pagination-sm align-items-center" [auUse]="directives().tabList">
					@for (slideData of state().slidesData(); track slideData.id; let index = $index) {
						<div class="page-item">
							<button
								type="button"
								class="page-link"
								[class.active]="state().selectedScrollSnap() === index"
								[auUse]="[directives().tabIndicator, {index, id: slideData.id}]"
							>
								{{ index + 1 }}
							</button>
						</div>
					}
				</div>
			</div>
		</div>
		<div class="progress-container d-none d-sm-flex" [class.opacity-0]="!isPlaying()" aria-hidden="true">
			<div class="bg-light rounded-4 py-1 px-3 w-100 d-flex align-items-center">
				<div class="progress w-100">
					<div class="autoplay-progress-bar progress-bar" #progressbar></div>
				</div>
			</div>
		</div>
	`,
	imports: [UseDirective],
})
export class AutoplayNavigationComponent {
	readonly state = input.required<CarouselContext<any>['state']>();
	readonly api = input.required<CarouselContext<any>['api']>();
	readonly directives = input.required<CarouselContext<any>['directives']>();
	readonly playingChange = output<boolean>();

	readonly sanitizer = inject(DomSanitizer);

	readonly playSvg = this.sanitizer.bypassSecurityTrustHtml(playSvg);
	readonly pauseSvg = this.sanitizer.bypassSecurityTrustHtml(pauseSvg);

	readonly progressbar = viewChild.required<ElementRef<HTMLDivElement>>('progressbar');

	readonly isPlaying = signal(true);

	onClick() {
		if (this.isPlaying()) {
			this.api().plugins()!.autoplay.stop();
		} else {
			this.api().plugins()!.autoplay.play();
		}
	}

	launchProgressbar() {
		this.progressbar().nativeElement.style.transition = 'none';
		this.progressbar().nativeElement.style.width = '0%';
		window.requestAnimationFrame(() => {
			window.setTimeout(() => {
				this.progressbar().nativeElement.style.transition = `width ${this.api().plugins()!.autoplay.timeUntilNext()}ms linear`;
				this.progressbar().nativeElement.style.width = '100%';
			});
		});
	}

	constructor() {
		effect(() => {
			if (this.state().initialized()) {
				this.api()
					.emblaApi()!
					.on('autoplay:play', () => {
						this.isPlaying.set(true);
						this.playingChange.emit(true);
					})
					.on('autoplay:stop', () => {
						this.isPlaying.set(false);
						this.playingChange.emit(false);
					})
					.on('autoplay:timerset', () => {
						this.launchProgressbar();
					})
					.on('autoplay:timerstopped', () => {
						this.progressbar().nativeElement.style.transition = 'none';
						this.progressbar().nativeElement.style.width = '0%';
					});
				this.launchProgressbar();
			}
		});
	}
}
