// react/demo/src/bootstrap/samples/progressbar/Coffee.tsx
import type {ProgressbarContext} from '@agnos-ui/react-bootstrap/components/progressbar';

export const Coffee = ({state}: ProgressbarContext) => (
	<div className="position-relative" style={{height: '300px'}}>
		<div className="cup">
			<div className="cup-fill-parent">
				<div className="cup-fill" style={{height: `${1.7 * state.percentage}px`}}>
					{state.percentage >= 50 ? (
						<>
							<div className="bubble bubble-1"></div>
							<div className="bubble bubble-2"></div>
							<div className="bubble bubble-3"></div>
						</>
					) : null}
				</div>
			</div>
		</div>
	</div>
);

// svelte/demo/src/bootstrap/samples/progressbar/Coffee.svelte
<script lang="ts">
	import type {ProgressbarContext} from '@agnos-ui/svelte-bootstrap/components/progressbar';
	import '@agnos-ui/common/samples/progressbar/custom.scss';

	let {state}: ProgressbarContext = $props();
</script>

<div class="position-relative" style="height: 300px">
	<div class="cup">
		<div class="cup-fill-parent">
			<div class="cup-fill" style={`height: ${1.7 * state.percentage}px;`}>
				{#if state.percentage >= 50}
					<div class="bubble bubble-1"></div>
					<div class="bubble bubble-2"></div>
					<div class="bubble bubble-3"></div>
				{/if}
			</div>
		</div>
	</div>
</div>
