// react/demo/src/bootstrap/samples/modal/Component.route.tsx
import type {ModalContext} from '@agnos-ui/react/components/modal';
import {openModal} from '@agnos-ui/react/components/modal';

type ModalContent = {name: string};

const ModalBody = ({widget, state}: ModalContext<ModalContent>) => (
	<>
		<p>Hello, {state.contentData.name}!</p>
		<button type="button" className="btn btn-outline-primary" onClick={() => widget.api.close()}>
			Close
		</button>
	</>
);

const ComponentDemo = () => (
	<button
		type="button"
		className="btn btn-primary"
		onClick={() => openModal({slotTitle: 'Hi there!', slotDefault: ModalBody, contentData: {name: 'World'}})}
	>
		Launch demo modal
	</button>
);
export default ComponentDemo;

// svelte/demo/src/app/samples/modal/Component.route.svelte
<script lang="ts">
	import {openModal} from '@agnos-ui/svelte/components/modal';
	import ComponentModal from './ComponentModal.svelte';
	const launch = () => openModal({slotTitle: 'Hi there!', slotDefault: ComponentModal, contentData: {name: 'World'}});
</script>

<button type="button" class="btn btn-primary" on:click={() => launch()}>Launch demo modal</button>
