// react/demo/src/bootstrap/samples/slots/RatingReadonly.tsx
import type {RatingProps} from '@agnos-ui/react-bootstrap/components/rating';
import {createRating} from '@agnos-ui/react-bootstrap/components/rating';
import {Slot} from '@agnos-ui/react-bootstrap/slot';
import {useWidgetWithConfig} from '@agnos-ui/react-bootstrap/config';
import React from 'react';

export function RatingReadonly(props: Pick<Partial<RatingProps>, 'rating' | 'maxRating' | 'className' | 'star'>) {
	const [{className, stars, star: slotStar}] = useWidgetWithConfig(createRating, {...props, readonly: true}, 'rating');

	// applying the Slot is just a matter of retrieving the prop and using the provided AgnosUI Slot component.
	return (
		<div className={`d-inline-flex au-rating ${className}`}>
			{stars.map((star) => (
				<React.Fragment key={star.index}>
					<span className="au-rating-star">
						<Slot slotContent={slotStar} props={star}></Slot>
					</span>
				</React.Fragment>
			))}
		</div>
	);
}

// svelte/demo/src/bootstrap/samples/slots/RatingReadonly.svelte
<script lang="ts">
	import {createRating, type RatingProps, type RatingSlots} from '@agnos-ui/svelte-bootstrap/components/rating';
	import {Slot} from '@agnos-ui/svelte-bootstrap/slot';
	import {callWidgetFactory} from '@agnos-ui/svelte-bootstrap/config';

	type $$Props = Pick<Partial<RatingProps>, 'rating' | 'maxRating' | 'className' | 'slotStar'>;
	type $$Slots = RatingSlots;

	const widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		$$slots,
		$$props: {
			...$$props,
			readonly: true,
		},
		events: {
			onRatingChange: () => {},
		},
	});
	export const api = widget.api;

	const {
		stores: {stars$, className$, slotStar$},
	} = widget;
	$: widget.patchChangedProps($$props);
</script>

<div class="d-inline-flex au-rating {$className$}">
	{#each $stars$ as { fill, index }}
		<span class="au-rating-star">
			<!-- 
                Simply use the Slot component from @agnos-ui/svelte-headless.
                The api is currently a bit tricky, until Svelte 5 arrives with snippets.
            -->
			<Slot slotContent={$slotStar$} props={{fill, index}} let:component let:props>
				<svelte:fragment slot="slot" let:props><slot name="star" {...props} /></svelte:fragment>
				<svelte:component this={component} {...props} />
			</Slot>
		</span>
	{/each}
</div>
