// svelte/demo/samples/accordion/TogglePanels.route.svelte
<script context="module" lang="ts">
	import {Accordion, AccordionItem} from '@agnos-ui/svelte';
	import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';
</script>

<script lang="ts">
	let accordion: Accordion;
	let secondAccordionItem: AccordionItem;
</script>

<Accordion bind:this={accordion}>
	<AccordionItem itemId="first">
		<slot slot="itemHeader">First panel</slot>
		<slot slot="itemBody">{BODY}</slot>
	</AccordionItem>
	<AccordionItem itemId="second" bind:this={secondAccordionItem}>
		<slot slot="itemHeader">Second panel</slot>
		<slot slot="itemBody">{BODY}</slot>
	</AccordionItem>
</Accordion>
<hr />
<button class="btn btn-sm btn-outline-primary me-2" on:click={() => accordion.api.toggle('first')}>Toggle first</button>
<button class="btn btn-sm btn-outline-primary me-2" on:click={() => secondAccordionItem.api.toggle()}>Toggle second</button>
<button class="btn btn-sm btn-outline-primary me-2" on:click={() => accordion.api.expandAll()}>Expand all</button>
<button class="btn btn-sm btn-outline-primary me-2" on:click={() => accordion.api.collapseAll()}>Collapse all</button>

// react/demo/app/samples/accordion/TogglePanels.route.tsx
import {Accordion, AccordionItem} from '@agnos-ui/react';
import {useRef} from 'react';
import type {AccordionWidget, AccordionItemWidget} from '@agnos-ui/core';
import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';

const AccordionDemo = () => {
	const refAccordion = useRef<AccordionWidget['api']>();
	const refSecondPanel = useRef<AccordionItemWidget['api']>();
	return (
		<>
			<Accordion ref={refAccordion}>
				<AccordionItem slotItemHeader="First panel" slotItemBody={BODY} itemId={'first'} />
				<AccordionItem slotItemHeader="Second panel" slotItemBody={BODY} itemId={'second'} ref={refSecondPanel} />
			</Accordion>
			<hr />
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.toggle('first')}>
				Toggle first
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refSecondPanel.current?.toggle()}>
				Toggle second
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.expandAll()}>
				Expand all
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.collapseAll()}>
				Collapse all
			</button>
		</>
	);
};
export default AccordionDemo;
