// svelte/demo/samples/focustrack/Focustrack.route.svelte
<script lang="ts">
	import {activeElement$, createHasFocus} from '@agnos-ui/core';

	const {hasFocus$, directive} = createHasFocus();

	let activeElements: {tagName: string | undefined; id: string | undefined}[] = [];
	$: activeElements = [...activeElements, {tagName: $activeElement$?.tagName.toLowerCase(), id: $activeElement$?.id || undefined}];
</script>

<div class="demo-focustrack">
	<div use:directive class="my-2 p-2 border">
		<h5>Container</h5>
		<input class="form-control" type="text" placeholder="Focusable input" id="focusableInput" /><br />
		<input class="form-control" type="text" placeholder="Other focusable input" id="otherFocusableInput" />
	</div>
	<input class="form-control" type="text" placeholder="Disabled input" id="disabledInput" disabled /><br />
	<div class="form-check mb-2">
		<input class="form-check-input" type="checkbox" id="containerHasFocus" checked={$hasFocus$} disabled />
		<label class="form-check-label" for="containerHasFocus">Focus in container</label>
	</div>
	<label for="activeElement" class="form-label">Active element history:</label>
	<textarea class="form-control mb-2" id="activeElementHistory" readonly>{JSON.stringify(activeElements)}</textarea>
	<button class="btn btn-primary" on:click={() => (activeElements = [])}>Clear</button>
</div>

// react/demo/app/samples/focustrack/Focustrack.route.tsx
// import {useState} from "react";
import {activeElement$, createHasFocus} from '@agnos-ui/core';
import {useDirective, useObservable} from '@agnos-ui/react';
import {useState, useEffect} from 'react';

const Focustrack = () => {
	const [hasFocus] = useState(createHasFocus);
	const hasFocusState = useObservable(hasFocus.hasFocus$);
	const refSet = useDirective(hasFocus.directive);

	const activeElement = useObservable(activeElement$);
	const [activeElements, setActiveElements] = useState<any[]>([]);

	useEffect(() => {
		setActiveElements([...activeElements, {tagName: activeElement?.tagName.toLowerCase(), id: activeElement?.id || undefined}]);
	}, [activeElement]);

	return (
		<div className="demo-focustrack">
			<div ref={refSet} className="my-2 p-2 border">
				<h5>Container</h5>
				<input className="form-control" type="text" placeholder="Focusable input" id="focusableInput" />
				<br />
				<input className="form-control" type="text" placeholder="Other focusable input" id="otherFocusableInput" />
			</div>
			<input className="form-control" type="text" placeholder="Disabled input" id="disabledInput" disabled />
			<br />
			<div className="form-check mb-2">
				<input className="form-check-input" type="checkbox" id="containerHasFocus" checked={hasFocusState} disabled />
				<label className="form-check-label" htmlFor="containerHasFocus">
					Focus in container
				</label>
			</div>
			<label htmlFor="activeElement" className="form-label">
				Active element history:
			</label>
			<textarea className="form-control mb-2" id="activeElementHistory" value={JSON.stringify(activeElements)} readOnly />
			<button className="btn btn-primary" onClick={() => setActiveElements([])}>
				Clear
			</button>
		</div>
	);
};
export default Focustrack;
