// svelte/demo/src/bootstrap/samples/slider/Custom.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte/components/slider';
	import CustomHandle from './CustomHandle.svelte';

	let sliderCustomLabelControl = [70];
	let sliderCustomHandleControl = [50];

	import '@agnos-ui/common/samples/slider/custom.scss';
</script>

<h2>Slider with custom labels</h2>
<Slider
	min={0}
	max={100}
	stepSize={1}
	bind:values={sliderCustomLabelControl}
	slotLabel={({value}) => '' + value + '%'}
	className="au-custom-slider-container"
></Slider>
<hr />
<h2>Slider with custom handle</h2>
<Slider min={0} max={100} stepSize={1} bind:values={sliderCustomHandleControl} slotHandle={CustomHandle} className="au-custom-slider-container"
></Slider>

// react/demo/src/app/samples/slider/Custom.route.tsx
import {Slider} from '@agnos-ui/react/components/slider';
import {useState} from 'react';
import '@agnos-ui/common/samples/slider/custom.scss';
import CustomSlotHandle from './CustomHandle';

const CustomSliderDemo = () => {
	const [sliderCustomLabelControl, setSliderCustomLabelControl] = useState([70]);
	const [sliderCustomHandleControl, setSliderCustomHandleControl] = useState([50]);

	return (
		<>
			<h2>Slider with custom labels</h2>
			<Slider
				min={0}
				max={100}
				stepSize={1}
				values={sliderCustomLabelControl}
				onValuesChange={setSliderCustomLabelControl}
				slotLabel={({value}: {value: number}) => '' + value + '%'}
				className="au-custom-slider-container"
			/>
			<hr />
			<h2>Slider with custom handle</h2>
			<Slider
				min={0}
				max={100}
				stepSize={1}
				values={sliderCustomHandleControl}
				onValuesChange={setSliderCustomHandleControl}
				slotHandle={CustomSlotHandle}
				className="au-custom-slider-container"
			/>
		</>
	);
};
export default CustomSliderDemo;
