// react/demo/src/app/samples/accordion/TogglePanels.route.tsx
import type {AccordionApi, AccordionItemApi} from '@agnos-ui/react/components/accordion';
import {Accordion, AccordionItem} from '@agnos-ui/react/components/accordion';
import {useRef} from 'react';
import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';

const AccordionDemo = () => {
	const refAccordion = useRef<AccordionApi>();
	const refSecondPanel = useRef<AccordionItemApi>();
	return (
		<>
			<Accordion ref={refAccordion}>
				<AccordionItem slotItemHeader="First panel" slotItemBody={BODY} itemId={'first'} />
				<AccordionItem slotItemHeader="Second panel" slotItemBody={BODY} itemId={'second'} ref={refSecondPanel} />
			</Accordion>
			<hr />
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.toggle('first')}>
				Toggle first
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refSecondPanel.current?.toggle()}>
				Toggle second
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.expandAll()}>
				Expand all
			</button>
			<button className="btn btn-sm btn-outline-primary me-2" onClick={() => refAccordion.current?.collapseAll()}>
				Collapse all
			</button>
		</>
	);
};
export default AccordionDemo;

// svelte/demo/src/bootstrap/samples/accordion/TogglePanels.route.svelte
<script lang="ts">
	import {Accordion, AccordionItem} from '@agnos-ui/svelte-bootstrap/components/accordion';
	import BODY from '@agnos-ui/common/samples/accordion/body.txt?raw';

	let accordion: Accordion;
	let secondAccordionItem: AccordionItem;
</script>

<Accordion bind:this={accordion}>
	<AccordionItem itemId="first" slotItemHeader="First panel">
		{BODY}
	</AccordionItem>
	<AccordionItem itemId="second" bind:this={secondAccordionItem} slotItemHeader="Second panel">
		{BODY}
	</AccordionItem>
</Accordion>
<hr />
<div class="d-flex flex-wrap gap-2">
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.toggle('first')}>Toggle first</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => secondAccordionItem.api.toggle()}>Toggle second</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.expandAll()}>Expand all</button>
	<button class="btn btn-sm btn-outline-primary" onclick={() => accordion.api.collapseAll()}>Collapse all</button>
</div>
