// react/demo/src/app/samples/rating/Default.route.tsx
import {Rating} from '@agnos-ui/react/components/rating';
import {useState} from 'react';

const RatingDemo = () => {
	const [rating, setRating] = useState(3);
	const [hover, setHover] = useState(0);
	const [left, setLeft] = useState(0);

	return (
		<>
			<Rating rating={rating} onRatingChange={setRating} onHover={setHover} onLeave={setLeft} ariaLabel="rating" />
			<div>
				Current rate: <span id="defaultRating">{rating}</span>
				<br />
				Hovered: <span id="defaultHovered">{hover}</span>
				<br />
				Left: <span id="defaultLeft">{left}</span>
			</div>
		</>
	);
};
export default RatingDemo;

// svelte/demo/src/daisyui/samples/rating/Default.route.svelte
<script>
	import Rating from './Rating.svelte';

	let rating = 3;
	let hovered = 0;
	let left = 0;
</script>

<Rating bind:rating onHover={(e) => (hovered = e)} onLeave={(e) => (left = e)} />
<div>
	Current rate: <span id="defaultRating">{rating}</span><br />
	Hovered: <span id="defaultHovered">{hovered}</span><br />
	Left: <span id="defaultLeft">{left}</span>
</div>
