// angular/demo/daisyui/src/app/samples/rating/rating.component.ts
import type {RatingWidget, RatingProps} from '@agnos-ui/angular-headless';
import {BaseWidgetDirective, auNumberAttribute, callWidgetFactory, createRating} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output, forwardRef} from '@angular/core';
import type {ControlValueAccessor} from '@angular/forms';
import {NG_VALUE_ACCESSOR} from '@angular/forms';

@Component({
	selector: 'app-rating',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './rating.component.html',
	providers: [{provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => RatingComponent), multi: true}],
})
export class RatingComponent extends BaseWidgetDirective<RatingWidget> implements ControlValueAccessor {
	readonly _widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		events: {
			onHover: (event: any) => this.hover.emit(event),
			onLeave: (event: any) => this.leave.emit(event),
			onRatingChange: (rating: number) => {
				this.ratingChange.emit(rating);
				this.onChange(rating);
			},
		},
	});

	onChange = (_: any) => {};
	onTouched = () => {};

	// You can choose here the props from the core you want as inputs
	@Input({transform: auNumberAttribute}) maxRating: RatingProps['maxRating'];
	@Input({transform: auNumberAttribute}) rating: RatingProps['rating'];
	@Input() ariaLabel: RatingProps['ariaLabel'];
	@Input() className: RatingProps['className'];
	@Output() hover = new EventEmitter<number>();
	@Output() leave = new EventEmitter<number>();
	@Output() ratingChange = new EventEmitter<number>();

	writeValue(value: any): void {
		this._widget.patch({rating: value});
	}

	// Interface for usage within form with ControlValueAccessor system
	registerOnChange(fn: (value: any) => any): void {
		this.onChange = fn;
	}

	registerOnTouched(fn: () => any): void {
		this.onTouched = fn;
	}

	setDisabledState(disabled: boolean): void {
		this._widget.patch({disabled});
	}

	// API used in the template
	trackByIndex(index: number) {
		return index;
	}

	getAriaLabel(index: number) {
		return `${this._widget.stores.ariaLabel$()} star ${index + 1}`;
	}
}

<div class="rating" [class]="state().className">
	@for (item of state().stars; track trackByIndex(index); let index = $index) {
		<input
			(blur)="onTouched()"
			(mouseleave)="_widget.actions.leave()"
			(mouseenter)="_widget.actions.hover(index + 1)"
			(click)="_widget.actions.click(index + 1)"
			[style.cursor]="state().interactive ? 'pointer' : 'default'"
			type="radio"
			name="rating-1"
			class="mask mask-star"
			[attr.aria-label]="getAriaLabel(index)"
			[checked]="index + 1 === state().visibleRating ? true : null"
		/>
	}
</div>

// svelte/demo/src/daisyui/samples/rating/Rating.svelte
<script lang="ts">
	import {createRating, type RatingProps} from '@agnos-ui/svelte-headless/components/rating';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	// You can choose here the props (form the core) you want as input
	type $$Props = Pick<Partial<RatingProps>, 'rating' | 'maxRating' | 'className' | 'onHover' | 'onLeave' | 'ariaLabel'>;
	export let rating: number | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		$$props,
		events: {
			onRatingChange: (value: number) => {
				rating = value;
			},
		},
	});
	export const api = widget.api;

	const {
		stores: {visibleRating$, interactive$, stars$, className$, ariaLabel$},
		actions: {hover, click, leave},
	} = widget;
	$: widget.patchChangedProps($$props);
</script>

<div class="rating {$className$}">
	{#each $stars$ as { index } (index)}
		<input
			on:mouseleave={leave}
			on:mouseenter={() => hover(index + 1)}
			on:click={() => click(index + 1)}
			style:cursor={$interactive$ ? 'pointer' : 'default'}
			type="radio"
			name="rating-1"
			class="mask mask-star"
			aria-label={`${$ariaLabel$} star ${index + 1}`}
			checked={index + 1 === $visibleRating$}
		/>
	{/each}
</div>
