// react/demo/src/daisyui/samples/rating/Rating.tsx
import {type RatingProps, createRating} from '@agnos-ui/react-headless/components/rating';
import {useWidget} from '@agnos-ui/react-headless/config';
import clsx from 'clsx';

// You can choose here the props from the core you want as inputs
export function Rating(
	props: Pick<Partial<RatingProps>, 'rating' | 'maxRating' | 'className' | 'onHover' | 'onRatingChange' | 'onLeave' | 'ariaLabel'>,
) {
	const {
		state: {visibleRating, stars, className, ariaLabel},
		api,
	} = useWidget(createRating, props);

	return (
		<div className={clsx('rating', className)}>
			{stars.map(({index}) => (
				<input
					key={index}
					onMouseLeave={api.leave}
					onMouseEnter={() => api.setHoveredRating(index + 1)}
					onClick={() => api.setRating(index + 1)}
					// React throws a warning if an onChange is not provided.
					onChange={() => {}}
					type="radio"
					name="rating-1"
					className="mask mask-star-2 bg-orange-400"
					aria-label={`${ariaLabel} star ${index + 1}`}
					checked={index + 1 === visibleRating}
				/>
			))}
		</div>
	);
}

// svelte/demo/src/daisyui/samples/rating/Rating.svelte
<script lang="ts">
	import {createRating, type RatingProps} from '@agnos-ui/svelte-headless/components/rating';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	// You can choose here the props (form the core) you want as input
	let {rating = $bindable(), ...props}: Pick<Partial<RatingProps>, 'rating' | 'maxRating' | 'className' | 'onHover' | 'ariaLabel'> = $props();

	const {
		state,
		api: {setRating, setHoveredRating, leave},
	} = callWidgetFactory(createRating, {
		get props() {
			return {...props, rating};
		},
		events: {
			onRatingChange: (value: number) => {
				rating = value;
			},
		},
	});
</script>

<div class="rating {state.className}">
	{#each state.stars as { index } (index)}
		<input
			onmouseleave={leave}
			onmouseenter={() => setHoveredRating(index + 1)}
			onclick={() => setRating(index + 1)}
			type="radio"
			name="rating-1"
			class="mask mask-star-2 bg-orange-400"
			aria-label={`${state.ariaLabel} star ${index + 1}`}
			checked={index + 1 === state.visibleRating}
		/>
	{/each}
</div>
