// angular/demo/bootstrap/src/app/samples/progressbar/simpleCustom.route.ts
import {ProgressbarComponent} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';

@Component({
	imports: [ProgressbarComponent],
	template: `
		<div class="d-flex flex-column gap-2">
			<div>
				A progressbar using custom values for minimum and maximum:
				<div auProgressbar auMin="1" auMax="5" auValue="4" [auAriaValueTextFn]="valueText">Step 4 out of 5</div>
			</div>
			<div>
				A striped animated progress bar:
				<div auProgressbar auType="info" auValue="63" auStriped auAnimated></div>
			</div>
			<div>
				Changing the height:
				<div auProgressbar [auHeight]="'1.5rem'" auValue="47"></div>
			</div>
		</div>
	`,
})
export default class SimpleCustomProgressBarComponent {
	readonly valueText = (val: number, _min: number, max: number) => `Step ${val} out of ${max}`;
}

// react/demo/src/bootstrap/samples/progressbar/SimpleCustom.route.tsx
import {Progressbar} from '@agnos-ui/react-bootstrap/components/progressbar';

export default () => (
	<div className="d-flex flex-column gap-2">
		<div>
			A progressbar using custom values for minimum and maximum:
			<Progressbar min={1} max={5} value={4} ariaValueTextFn={(val, _min, max) => `Step ${val} out of ${max}`}>
				Step 4 out of 5
			</Progressbar>
		</div>
		<div>
			A striped animated progress bar:
			<Progressbar value={63} type="info" striped animated />
		</div>
		<div>
			Changing the height:
			<Progressbar height="1.5rem" value={47} />
		</div>
	</div>
);
