// svelte/demo/src/app/samples/rating/CustomTemplate.route.svelte
<script lang="ts">
	import '@agnos-ui/common/samples/rating/custom.scss';
	import {Rating} from '@agnos-ui/svelte';
</script>

<Rating className="rating-custom" rating={7} ariaLabel="custom rating">
	<span slot="star" let:index let:fill class="star" class:filled={fill === 100} class:bad={index < 3}>&#9733;</span>
</Rating>

// react/demo/app/samples/rating/CustomTemplate.route.tsx
import '@agnos-ui/common/samples/rating/custom.scss';
import {Rating} from '@agnos-ui/react/Rating';
import type {StarContext} from '@agnos-ui/react/Rating';

const CustomStar = ({fill, index}: StarContext) => {
	const starClassname = ['star'];
	if (fill === 100) {
		starClassname.push('filled');
	}
	if (index < 3) {
		starClassname.push('bad');
	}
	return <span className={starClassname.join(' ')}>&#9733;</span>;
};
const RatingDemo = () => <Rating className="rating-custom" rating={7} slotStar={CustomStar} ariaLabel="custom rating" />;
export default RatingDemo;
