// react/demo/app/samples/slider/Default.route.tsx
import {Slider} from '@agnos-ui/react/Slider';
import {useState} from 'react';

const DefaultSliderDemo = () => {
	const [sliderControl, setSliderControl] = useState([70]);
	const [disabledControl, setDisabledControl] = useState([60]);
	const [sliderValues, setSliderValues] = useState([20]);
	const [disabledToggle, setDisabledToggle] = useState(true);
	const [readonlyToggle, setReadonlyToggle] = useState(true);

	return (
		<>
			<h2>Slider with form control</h2>
			<Slider min={0} max={100} stepSize={1} values={sliderControl} onValuesChange={setSliderControl} />
			Form control value: {sliderControl.join(', ')}
			<hr />
			<h2>Slider with value</h2>
			<Slider min={0} max={100} stepSize={1} values={sliderValues} onValuesChange={setSliderValues} />
			Value: {sliderValues.join(', ')}
			<hr />
			<h2>Disabled slider</h2>
			<Slider
				min={0}
				max={100}
				stepSize={1}
				values={disabledControl}
				onValuesChange={setDisabledControl}
				disabled={disabledToggle}
				readonly={readonlyToggle}
			/>
			<div className="form-check form-switch">
				<input
					className="form-check-input"
					type="checkbox"
					role="switch"
					id="disabled"
					checked={disabledToggle}
					onChange={() => setDisabledToggle(!disabledToggle)}
				/>
				<label className="form-check-label" htmlFor="disabled">
					Disabled
				</label>
			</div>
			<div className="form-check form-switch">
				<input
					className="form-check-input"
					type="checkbox"
					role="switch"
					id="readonly"
					checked={readonlyToggle}
					onChange={() => setReadonlyToggle(!readonlyToggle)}
				/>
				<label className="form-check-label" htmlFor="readonly">
					Readonly
				</label>
			</div>
		</>
	);
};
export default DefaultSliderDemo;

// svelte/demo/src/bootstrap/samples/slider/Default.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte/components/slider';

	let sliderControl = [70];
	let disabledControl = [60];
	let sliderValues = [20];
	let disabledToggle = true;
	let readonlyToggle = true;
	let minMaxLabelToggle = true;
	let valueLabelToggle = true;
</script>

<h2>Slider with form control</h2>
<Slider min={0} max={100} stepSize={1} bind:values={sliderControl} showMinMaxLabels={minMaxLabelToggle} showValueLabels={valueLabelToggle} />
Form control value: {sliderControl.join(', ')}
<hr />

<h2>Slider with value</h2>
<Slider min={0} max={100} stepSize={1} bind:values={sliderValues} /> Value:
{sliderValues}
<hr />

<h2>Disabled slider</h2>
<Slider min={0} max={100} stepSize={1} bind:values={disabledControl} disabled={disabledToggle} readonly={readonlyToggle} />

<div class="form-check form-switch">
	<input class="form-check-input" type="checkbox" role="switch" id="disabled" bind:checked={disabledToggle} />
	<label class="form-check-label" for="disabled">Disabled</label>
</div>
<div class="form-check form-switch">
	<input class="form-check-input" type="checkbox" role="switch" id="readonly" bind:checked={readonlyToggle} />
	<label class="form-check-label" for="readonly">Readonly</label>
</div>
<div class="form-check form-switch">
	<input class="form-check-input" type="checkbox" role="switch" id="showMinMax" bind:checked={minMaxLabelToggle} />
	<label class="form-check-label" for="showMinMax">Min-Max label visibility</label>
</div>
<div class="form-check form-switch">
	<input class="form-check-input" type="checkbox" role="switch" id="showValues" bind:checked={valueLabelToggle} />
	<label class="form-check-label" for="showValues">Value label visibility</label>
</div>
