// angular/demo/bootstrap/src/app/samples/slider/ticks.route.ts
import {SliderComponent} from '@agnos-ui/angular-bootstrap';
import {Component, effect, signal} from '@angular/core';
import {FormControl, FormsModule, ReactiveFormsModule} from '@angular/forms';

@Component({
	imports: [SliderComponent, ReactiveFormsModule, FormsModule],
	template: `
		<h5>Ticks as steps</h5>
		<div auSlider auMin="0" auMax="100" auStepSize="25" [formControl]="sliderRangeControl" auShowTicks></div>

		<div class="form-check form-switch mb-2">
			<input class="form-check-input" type="checkbox" role="switch" id="disabled" [(ngModel)]="disabledToggle" />
			<label class="form-check-label" for="disabled">Disabled</label>
		</div>
		<h5>With intermediate steps</h5>
		<div auSlider auMin="0" auMax="100" auStepSize="1" [formControl]="sliderControl" auShowTicks auTickInterval="25"></div>
		<br />

		<h5>Without tick labels</h5>
		<div auSlider auMin="0" auMax="100" auStepSize="25" [formControl]="sliderRangeControlLabels" auShowTicks auShowTickValues="false"></div>
		<p>If <code>showTickValues</code> is set to <code>false</code> the min/max/current label display is automatically put to <code>true</code></p>
	`,
})
export default class TicksSliderComponent {
	readonly sliderControl = new FormControl([30]);

	readonly sliderRangeControl = new FormControl([30, 70]);
	readonly disabledToggle = signal(false);

	readonly sliderRangeControlLabels = new FormControl([30, 70]);

	constructor() {
		effect(() => {
			if (this.disabledToggle()) {
				this.sliderRangeControl.disable();
			} else {
				this.sliderRangeControl.enable();
			}
		});
	}
}

// svelte/demo/src/bootstrap/samples/slider/Ticks.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';

	let sliderControl = $state([30]);

	let sliderRangeControl = $state([30, 70]);
	let disabledToggle = $state(false);

	let sliderRangeControlLabels = $state([30, 70]);
</script>

<h2>Ticks as steps</h2>
<Slider min={0} max={100} stepSize={25} bind:values={sliderRangeControl} disabled={disabledToggle} showTicks />

<div class="form-check form-switch mb-2">
	<input class="form-check-input" type="checkbox" role="switch" id="disabled" bind:checked={disabledToggle} />
	<label class="form-check-label" for="disabled">Disabled</label>
</div>
<h2>With intermediate steps</h2>
<Slider min={0} max={100} stepSize={1} bind:values={sliderControl} showTicks tickInterval={25} />
<br />

<h2>Without tick labels</h2>
<Slider min={0} max={100} stepSize={25} bind:values={sliderRangeControlLabels} showTicks showTickValues={false} />
<p>If <code>showTickValues</code> is set to <code>false</code> the min/max/current label display is automatically put to <code>true</code></p>
