// react/demo/src/daisyui/samples/toast/Toast.tsx
import {createToast} from '@agnos-ui/react-headless/components/toast';
import type {ToastProps} from '@agnos-ui/react-headless/components/toast';
import {useWidget} from '@agnos-ui/react-headless/config';
import CloseIcon from '@agnos-ui/common/samples/common/close_icon.svg?react';
import {type PropsWithChildren} from 'react';

export const Toast = (
	props: PropsWithChildren<Partial<Pick<ToastProps, 'className' | 'visible' | 'dismissible' | 'ariaCloseButtonLabel' | 'onVisibleChange'>>>,
) => {
	const {state, api} = useWidget(createToast, props);
	return (
		<>
			{!state.hidden && (
				<div className={`alert ${state.className}`}>
					{props.children}
					{state.dismissible && (
						<button className="btn btn-circle btn-ghost btn-xs" onClick={api.close} aria-label={`${state.ariaCloseButtonLabel}`}>
							<CloseIcon />
						</button>
					)}
				</div>
			)}
		</>
	);
};

// svelte/demo/src/daisyui/samples/toast/Toast.svelte
<script lang="ts">
	import {createToast, type ToastProps as Props} from '@agnos-ui/svelte-headless/components/toast';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	import closeIconSvg from '@agnos-ui/common/samples/common/close_icon.svg?raw';
	import type {Snippet} from 'svelte';

	let {
		visible = $bindable(),
		children,
		...props
	}: Partial<Pick<Props, 'className' | 'visible' | 'dismissible' | 'ariaCloseButtonLabel'>> & {children: Snippet} = $props();

	const {state, api} = callWidgetFactory(createToast, {
		get props() {
			return {...props, visible};
		},
		events: {
			onVisibleChange: (event) => {
				visible = event;
			},
		},
	});
</script>

{#if !state.hidden}
	<div class="alert {state.className}">
		{@render children()}
		{#if state.dismissible}
			<button class="btn btn-circle btn-ghost btn-xs" onclick={api.close} aria-label={state.ariaCloseButtonLabel}>
				{@html closeIconSvg}
			</button>
		{/if}
	</div>
{/if}
