// angular/demo/daisyui/src/app/samples/toast/toast.component.ts
import {BaseWidgetDirective, type ToastWidget, type ToastProps, auBooleanAttribute, callWidgetFactory, createToast} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output, inject} from '@angular/core';
import closeIcon from '@agnos-ui/common/samples/common/close_icon.svg';
import {DomSanitizer} from '@angular/platform-browser';

@Component({
	selector: 'app-toast',
	template: `
		@if (!state().hidden) {
			<div class="alert {{ state().className }} flex">
				<ng-content />
				@if (state().dismissible) {
					<button
						class="btn btn-sm btn-circle btn-ghost"
						(click)="api.close()"
						[attr.aria-label]="state().ariaCloseButtonLabel"
						[innerHTML]="closeIcon"
					></button>
				}
			</div>
		}
	`,
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToastComponent extends BaseWidgetDirective<ToastWidget> {
	readonly closeIcon = inject(DomSanitizer).bypassSecurityTrustHtml(closeIcon);

	@Input({transform: auBooleanAttribute})
	visible?: ToastProps['visible'];
	@Input({transform: auBooleanAttribute})
	dismissible?: ToastProps['dismissible'];
	@Input() ariaCloseButtonLabel?: ToastProps['ariaCloseButtonLabel'];
	@Input() className?: ToastProps['className'];
	@Output() visibleChange = new EventEmitter<boolean>();
	@Output() hidden = new EventEmitter<void>();
	@Output() shown = new EventEmitter<void>();

	readonly _widget = callWidgetFactory({
		factory: createToast,
		widgetName: 'toast',
		events: {onVisibleChange: (event) => this.visibleChange.emit(event), onShown: () => this.shown.emit(), onHidden: () => this.hidden.emit()},
	});
}

// svelte/demo/src/daisyui/samples/toast/Toast.svelte
<script lang="ts">
	import {createToast, type ToastProps as Props} from '@agnos-ui/svelte-headless/components/toast';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	import closeIconSvg from '@agnos-ui/common/samples/common/close_icon.svg?raw';
	import type {Snippet} from 'svelte';

	let {
		visible = $bindable(),
		children,
		...props
	}: Partial<Pick<Props, 'className' | 'visible' | 'dismissible' | 'ariaCloseButtonLabel'>> & {children: Snippet} = $props();

	const {state, api} = callWidgetFactory({
		factory: createToast,
		widgetName: 'toast',
		get props() {
			return {...props, visible};
		},
		enablePatchChanged: true,
		events: {
			onVisibleChange: (event) => {
				visible = event;
			},
		},
	});
</script>

{#if !state.hidden}
	<div class="alert {state.className} flex">
		{@render children()}
		{#if state.dismissible}
			<button class="btn btn-sm btn-circle btn-ghost" onclick={api.close} aria-label={state.ariaCloseButtonLabel}>
				{@html closeIconSvg}
			</button>
		{/if}
	</div>
{/if}
