// react/demo/src/bootstrap/samples/modal/Stack.route.tsx
import type {ModalContext} from '@agnos-ui/react-bootstrap/components/modal';
import {openModal} from '@agnos-ui/react-bootstrap/components/modal';

const ModalBody = ({widget, state}: ModalContext<void>) => (
	<>
		This is a modal
		<br />
		<br />
		<button
			className="btn btn-outline-primary m-1"
			onClick={() => openModal({slotTitle: 'Other modal', slotDefault: ModalBody, container: state.modalElement})}
		>
			Launch other modal
		</button>
		<br />
		<button className="btn btn-outline-secondary m-1" onClick={() => widget.api.patch({backdrop: true})}>
			Enable backdrop
		</button>
		<button className="btn btn-outline-secondary m-1" onClick={() => widget.api.patch({backdrop: false})}>
			Disable backdrop
		</button>
		<br />
		<button className="btn btn-outline-secondary m-1" onClick={() => widget.api.close()}>
			Close
		</button>
	</>
);

const StackDemo = () => (
	<button className="btn btn-primary" onClick={() => openModal({slotTitle: 'First modal', className: 'modal-sm', slotDefault: ModalBody})}>
		Launch demo modal
	</button>
);
export default StackDemo;

// angular/demo/bootstrap/src/app/samples/modal/stack.route.ts
import {AgnosUIAngularModule, ModalService} from '@agnos-ui/angular-bootstrap';
import {Component, inject} from '@angular/core';

@Component({
	standalone: true,
	imports: [AgnosUIAngularModule],
	template: `
		<button class="btn btn-primary" (click)="modalService.open({slotTitle: 'First modal', className: 'modal-sm', slotDefault: recursiveModal})">
			Launch demo modal
		</button>
		<ng-template #recursiveModal let-widget="widget" let-state="state">
			This is a modal<br /><br />
			<button
				class="btn btn-outline-primary m-1"
				(click)="modalService.open({slotTitle: 'Other modal', slotDefault: recursiveModal, container: state.modalElement})"
			>
				Launch other modal</button
			><br />
			<button class="btn btn-outline-secondary m-1" (click)="widget.api.patch({backdrop: true})">Enable backdrop</button>
			<button class="btn btn-outline-secondary m-1" (click)="widget.api.patch({backdrop: false})">Disable backdrop</button><br />
			<button class="btn btn-outline-secondary m-1" (click)="widget.api.close()">Close</button>
		</ng-template>
	`,
})
export default class ModalDemoComponent {
	modalService = inject(ModalService);
}
