// react/demo/src/app/samples/slider/Right-to-left.route.tsx
import {Slider} from '@agnos-ui/react/components/slider';
import {useState} from 'react';

const RightToLeftDemo = () => {
	const [sliderControl, setSliderControl] = useState([30]);
	const [sliderRangeControl, setSliderRangeControl] = useState([30, 70]);
	const [sliderVerticalControl, setSliderVerticalControl] = useState([30]);
	const [sliderRangeVerticalControl, setSliderRangeVerticalControl] = useState([30, 70]);

	return (
		<>
			<h2>Horizontal slider</h2>
			<Slider min={0} max={100} stepSize={1} values={sliderControl} onValuesChange={setSliderControl} rtl={true} />
			<br />
			<Slider min={0} max={100} stepSize={1} values={sliderRangeControl} onValuesChange={setSliderRangeControl} rtl={true} />
			<h2>Vertical slider</h2>
			<div className="d-flex" style={{height: '350px'}}>
				<div className="col-6" style={{height: '300px'}}>
					<Slider
						min={0}
						max={100}
						rtl={true}
						stepSize={1}
						vertical={true}
						values={sliderVerticalControl}
						onValuesChange={setSliderVerticalControl}
						className="my-0"
					/>
				</div>
				<div className="col-6" style={{height: '300px'}}>
					<Slider
						min={0}
						max={100}
						rtl={true}
						stepSize={1}
						vertical={true}
						values={sliderRangeVerticalControl}
						onValuesChange={setSliderRangeVerticalControl}
						className="my-0"
					/>
				</div>
			</div>
		</>
	);
};
export default RightToLeftDemo;

// svelte/demo/src/app/samples/slider/Right-to-left.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte/components/slider';

	let sliderControl = [70];
	let sliderRangeControl = [30, 70];
	let sliderVerticalControl = [70];
	let sliderRangeVerticalControl = [30, 70];
</script>

<h2>Horizontal slider</h2>
<Slider min={0} max={100} stepSize={1} rtl={true} bind:values={sliderControl} />
<br />
<Slider min={0} max={100} stepSize={1} rtl={true} bind:values={sliderRangeControl} />
<h2>Vertical slider</h2>
<div class="d-flex" style="height: 350px">
	<div class="col-6" style="height: 300px">
		<Slider min={0} max={100} stepSize={1} rtl={true} vertical={true} bind:values={sliderVerticalControl} className="my-0" />
	</div>
	<div class="col-6" style="height: 300px">
		<Slider min={0} max={100} stepSize={1} rtl={true} vertical={true} bind:values={sliderRangeVerticalControl} className="my-0" />
	</div>
</div>
