// react/demo/src/bootstrap/samples/transition/Collapse.tsx
import {useMemo, type PropsWithChildren} from 'react';
import {createTransition} from '@agnos-ui/react-bootstrap/services/transitions/baseTransitions';
import {collapseVerticalTransition} from '@agnos-ui/react-bootstrap/services/transitions/bootstrap';
import {useDirective} from '@agnos-ui/react-bootstrap/utils/directive';
import '@agnos-ui/common/samples/transition/collapse.scss';
import CollapseIcon from '@agnos-ui/common/samples/transition/collapseButton.svg?react';
import {useObservable} from '@agnos-ui/react-bootstrap/utils/stores';

const Collapse = ({expanded, headerText, children}: PropsWithChildren<{expanded?: boolean; headerText: string}>) => {
	const {
		state$,
		directives: {directive},
		api: {toggle},
	} = useMemo(
		() =>
			createTransition({
				props: {
					visible: expanded,
					transition: collapseVerticalTransition,
				},
			}),
		[],
	);
	const transitionRef = useDirective(directive);
	const state = useObservable(state$);

	return (
		<div className="card">
			<div className="card-header p-0">
				<button
					type="button"
					id="collapse-toggle"
					onClick={() => toggle()}
					className="btn toggle-button"
					aria-controls="collapse-content"
					aria-expanded={state.visible || undefined}
				>
					{headerText}
					<span className={'ms-1 collapse-icon' + (state.visible ? ' expanded' : '')}>
						<CollapseIcon />
					</span>
				</button>
			</div>
			{state.hidden ? null : (
				<div id="collapse-content" {...transitionRef}>
					<div className="card-body">{children}</div>
				</div>
			)}
		</div>
	);
};
export default Collapse;

// svelte/demo/src/bootstrap/samples/transition/Collapse.svelte
<script lang="ts">
	import {createTransition} from '@agnos-ui/svelte-bootstrap/services/transitions/baseTransitions';
	import {collapseVerticalTransition} from '@agnos-ui/svelte-bootstrap/services/transitions/bootstrap';
	import '@agnos-ui/common/samples/transition/collapse.scss';
	import collapseIcon from '@agnos-ui/common/samples/transition/collapseButton.svg?raw';

	export let headerText: string;
	export let expanded = false;

	const {
		stores: {visible$, hidden$},
		api: {toggle},
		directives: {directive},
	} = createTransition({
		props: {
			visible: expanded,
			transition: collapseVerticalTransition,
		},
	});
</script>

<div class="card">
	<div class="card-header p-0">
		<button
			type="button"
			id="collapse-toggle"
			on:click={() => toggle()}
			class="btn toggle-button"
			aria-controls="collapse-content"
			aria-expanded={$visible$ || undefined}
		>
			{headerText}
			<span class="ms-1 collapse-icon" class:expanded={$visible$}>
				{@html collapseIcon}
			</span>
		</button>
	</div>
	{#if !$hidden$}
		<div id="collapse-content" use:directive>
			<div class="card-body">
				<slot />
			</div>
		</div>
	{/if}
</div>
