// react/demo/src/app/samples/transition/Flip.tsx
import {type PropsWithChildren} from 'react';
import {useWidget} from '@agnos-ui/react/utils/widget';
import {createTransition} from '@agnos-ui/react/services/transitions/baseTransitions';
import {createSimpleClassTransition} from '@agnos-ui/react/services/transitions/simpleClassTransition';
import {useDirective} from '@agnos-ui/react/utils/directive';
import '@agnos-ui/common/samples/transition/flip.scss';

const Flip = ({hiddenText, children}: PropsWithChildren<{hiddenText: string}>) => {
	const [, widget] = useWidget(
		createTransition,
		{},
		{
			props: {
				visible: false,
				transition: createSimpleClassTransition({hideClasses: ['hide'], animationPendingHideClasses: ['hide']}),
			},
		},
	);
	const transitionRef = useDirective(widget.directives.directive);

	return (
		<div className="flip-card">
			<div className="flip-card-inner" ref={transitionRef}>
				<div className="flip-card-front">
					{children}
					<button className="btn btn-outline-secondary" onClick={() => widget.api.hide()}>
						Hide again.
					</button>
				</div>
				<div className="flip-card-back">
					<button className="btn btn-outline-primary" onClick={() => widget.api.show()}>
						{hiddenText}
					</button>
				</div>
			</div>
		</div>
	);
};
export default Flip;

// svelte/demo/src/bootstrap/samples/transition/Flip.svelte
<script lang="ts">
	import {createTransition} from '@agnos-ui/svelte-bootstrap/services/transitions/baseTransitions';
	import {createSimpleClassTransition} from '@agnos-ui/svelte-bootstrap/services/transitions/simpleClassTransition';
	import '@agnos-ui/common/samples/transition/flip.scss';

	export let hiddenText: string;

	const {
		api: {show, hide},
		directives: {directive},
	} = createTransition({
		props: {
			visible: false,
			transition: createSimpleClassTransition({hideClasses: ['hide'], animationPendingHideClasses: ['hide']}),
		},
	});
</script>

<div class="flip-card">
	<div class="flip-card-inner" use:directive>
		<div class="flip-card-front">
			<slot />
			<button class="btn btn-outline-secondary" on:click={() => hide()}>Hide again.</button>
		</div>
		<div class="flip-card-back">
			<button class="btn btn-outline-primary" on:click={() => show()}>{hiddenText}</button>
		</div>
	</div>
</div>
