// angular/demo/daisyui/src/app/samples/slider/slider.component.ts
import {
	BaseWidgetDirective,
	type SliderProps,
	type SliderWidget,
	auBooleanAttribute,
	auNumberAttribute,
	callWidgetFactory,
	createSlider,
	UseDirective,
} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output} from '@angular/core';

@Component({
	selector: 'app-slider',
	standalone: true,
	imports: [UseDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './slider.component.html',
})
export class SliderComponent extends BaseWidgetDirective<SliderWidget> {
	@Input({transform: auBooleanAttribute}) disabled?: SliderProps['disabled'];
	@Input({transform: auNumberAttribute}) min?: SliderProps['min'];
	@Input({transform: auNumberAttribute}) max?: SliderProps['max'];
	@Input({transform: auNumberAttribute}) stepSize?: SliderProps['stepSize'];
	@Input() values?: SliderProps['values'];
	@Input() className?: SliderProps['className'];
	@Output() valuesChange = new EventEmitter<number[]>();

	readonly _widget = callWidgetFactory({
		factory: createSlider,
		widgetName: 'slider',
		events: {
			onValuesChange: (event) => {
				this.valuesChange.emit(event);
			},
		},
	});
}

<input
	[auUse]="widget.directives.sliderDirective"
	type="range"
	[min]="state().min"
	[max]="state().max"
	[value]="state().sortedHandles[0].value"
	[step]="state().stepSize"
	[class]="'range'"
	[attr.aria-label]="state().sortedHandles[0].ariaLabel"
	(click)="widget.actions.click($event)"
	(keydown)="widget.actions.keydown($event, 0)"
	(mousedown)="widget.actions.mouseDown($event, 0)"
	(touchstart)="widget.actions.touchStart($event, 0)"
/>

// svelte/demo/src/daisyui/samples/slider/Slider.svelte
<script lang="ts">
	import type {SliderProps as Props} from '@agnos-ui/svelte-headless/components/slider';
	import {createSlider} from '@agnos-ui/svelte-headless/components/slider';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';

	type $$Props = Partial<Pick<Props, 'min' | 'max' | 'values' | 'stepSize' | 'className'>>;

	export let values: number[] | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createSlider,
		widgetName: 'slider',
		$$props,
		events: {
			onValuesChange: (value: number[]) => {
				values = value;
			},
		},
	});
	const {
		stores: {min$, max$, stepSize$, sortedHandles$},
		directives: {sliderDirective},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);
</script>

<input
	type="range"
	use:sliderDirective
	min={$min$}
	max={$max$}
	value={$sortedHandles$[0].value}
	step={$stepSize$}
	class="range"
	aria-label={$sortedHandles$[0].ariaLabel}
	on:click={widget.actions.click}
	on:keydown={(e) => widget.actions.keydown(e, 0)}
	on:mousedown={(e) => widget.actions.mouseDown(e, 0)}
	on:touchstart={(e) => widget.actions.touchStart(e, 0)}
/>
