// svelte/demo/samples/accordion/Playground.route.svelte
<script lang="ts">
	import {Accordion, AccordionItem} from '@agnos-ui/svelte';
	import {hashChangeHook} from '../../utils';

	const props$ = hashChangeHook('accordion');
</script>

{#key $props$}
	<Accordion {...$props$}>
		<AccordionItem>
			<slot slot="itemHeader">Header 1</slot>
			<slot slot="itemBody">Body 1</slot>
		</AccordionItem>
		<AccordionItem>
			<slot slot="itemHeader">Header 2</slot>
			<slot slot="itemBody">Body 2</slot>
		</AccordionItem>
	</Accordion>
{/key}

// react/demo/src/app/samples/accordion/Playground.route.tsx
import {Accordion, AccordionItem} from '@agnos-ui/react/components/accordion';
import {WidgetsDefaultConfig} from '@agnos-ui/react/config';
import {useHashChange} from '../../utils';

const AccordionDemo = () => {
	const {config, props} = useHashChange();

	return (
		<WidgetsDefaultConfig accordion={config}>
			<Accordion {...props}>
				<AccordionItem {...props} slotItemHeader="Header 1" slotItemBody="Body 1"></AccordionItem>
				<AccordionItem {...props} slotItemHeader="Header 2" slotItemBody="Body 2"></AccordionItem>
			</Accordion>
		</WidgetsDefaultConfig>
	);
};
export default AccordionDemo;
