// react/demo/src/app/samples/select/Default.route.tsx
import {Select} from '@agnos-ui/react';
import {useCallback, useState} from 'react';

const wordsA = ['apple', 'apricot', 'asparagus', 'astronaut', 'athletic', 'autumn', 'avocado'];
const wordsB = ['banana', 'baseball', 'basketball', 'beautiful', 'bedroom', 'bee', 'bicycle'];
const wordsC = ['cat', 'caterpillar', 'cave', 'chair', 'cheese', 'cherry', 'chicken'];

const Default = () => {
	const [mainList] = useState([...wordsA, ...wordsB, ...wordsC]);
	const [items, setItems] = useState([] as string[]);
	const [filterTextProp, setFilterTextProp] = useState(undefined as string | undefined);
	const onFilterTextChange = useCallback((filterText: string) => {
		setFilterTextProp(filterText);
		setItems(filterText ? mainList.filter((item) => item.toLowerCase().startsWith(filterText)) : mainList.slice(0, 10));
	}, []);
	return (
		<div style={{height: '400px'}}>
			<div className="mb-3">
				<label className="form-label">Start typing with a, b or c</label>
				<Select items={items} filterText={filterTextProp} onFilterTextChange={onFilterTextChange} badgeClassName="badge text-bg-light" />
			</div>
		</div>
	);
};
export default Default;

// angular/demo/src/app/samples/select/default.route.ts
import {SelectComponent} from '@agnos-ui/angular';
import {Component} from '@angular/core';

@Component({
	standalone: true,
	imports: [SelectComponent],
	template: `
		<div style="height: 400px;">
			<div class="mb-3">
				<label class="form-label">Start typing with a, b or c</label>
				<div
					auSelect
					[auItems]="items"
					[auFilterText]="filterText"
					(auFilterTextChange)="onFilterTextChange($event)"
					auBadgeClassName="badge text-bg-light"
				></div>
			</div>
		</div>
	`,
})
export default class DefaultSelectComponent {
	wordsA = ['apple', 'apricot', 'asparagus', 'astronaut', 'athletic', 'autumn', 'avocado'];
	wordsB = ['banana', 'baseball', 'basketball', 'beautiful', 'bedroom', 'bee', 'bicycle'];
	wordsC = ['cat', 'caterpillar', 'cave', 'chair', 'cheese', 'cherry', 'chicken'];
	mainList = [...this.wordsA, ...this.wordsB, ...this.wordsC];

	items = this.mainList.slice(0, 10);

	filterText: string | undefined;

	onFilterTextChange(filterText: string) {
		const mainList = this.mainList;
		this.items = filterText ? mainList.filter((item) => item.toLowerCase().startsWith(filterText)) : mainList.slice(0, 10);
	}
}
