// react/demo/src/bootstrap/samples/slots/Context.route.tsx
import type {PaginationNumberContext} from '@agnos-ui/react-bootstrap/components/pagination';
import {Pagination} from '@agnos-ui/react-bootstrap/components/pagination';

const Usage = () => {
	const numberLabel = ({displayedPage}: PaginationNumberContext) => ['A', 'B', 'C', 'D', 'E', 'F'][displayedPage - 1];
	return (
		<>
			<p>The default look of the pagination:</p>
			<Pagination collectionSize={60} />

			<p>Changing the slot displaying the page number to use letters instead:</p>
			<Pagination collectionSize={60} numberLabel={numberLabel} />
		</>
	);
};
export default Usage;

// svelte/demo/src/app/samples/slots/Context.route.svelte
<script lang="ts">
	import {Pagination} from '@agnos-ui/svelte/components/pagination';
</script>

<p>The default look of the pagination:</p>
<Pagination collectionSize={60} />

<p>Changing the slot displaying the page number to use letters instead:</p>
<Pagination collectionSize={60}>
	<svelte:fragment slot="numberLabel" let:displayedPage>
		{['A', 'B', 'C', 'D', 'E', 'F'][displayedPage - 1]}
	</svelte:fragment>
</Pagination>
