// svelte/lib/src/components/progressbar/Progressbar.svelte
<script lang="ts" context="module">
	import type {ProgressbarProps as Props, ProgressbarSlots as Slots} from '@agnos-ui/svelte-headless/components/progressbar';
	import {createProgressbar} from '@agnos-ui/svelte-headless/components/progressbar';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	import ProgressbarDefaultStructure from './ProgressbarDefaultStructure.svelte';
	const defaultConfig: Partial<Props> = {
		slotStructure: ProgressbarDefaultStructure,
	};
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars
	type $$Slots = Slots; // eslint-disable-line @typescript-eslint/no-unused-vars
	export const widget = callWidgetFactory({factory: createProgressbar, widgetName: 'progressbar', $$slots, $$props, defaultConfig, events: {}});
	const {
		stores: {slotStructure$, ariaLabel$, value$, min$, max$, ariaValueText$},
		state$,
	} = widget;

	$: widget.patchChangedProps($$props);

	$: slotContext = {widget, state: $state$};
</script>

<div
	role="progressbar"
	aria-label={$ariaLabel$ || undefined}
	aria-valuenow={$value$}
	aria-valuemin={$min$}
	aria-valuemax={$max$}
	aria-valuetext={$ariaValueText$}
>
	<Slot slotContent={$slotStructure$} props={slotContext} let:component let:props>
		<slot slot="slot" name="structure" let:props {...props} />
		<svelte:component this={component} {...props}>
			<svelte:fragment let:state let:widget><slot {state} {widget} /></svelte:fragment>
			<slot name="structure" slot="structure" let:state let:widget {state} {widget} />
		</svelte:component>
	</Slot>
</div>

// react/lib/src/components/progressbar/progressbar.tsx
import {type PropsWithChildren} from 'react';
import type {ProgressbarContext, ProgressbarProps} from '@agnos-ui/react-headless/components/progressbar';
import {createProgressbar} from '@agnos-ui/react-headless/components/progressbar';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import {toSlotContextWidget} from '@agnos-ui/react-headless/types';
import {Slot} from '@agnos-ui/react-headless/slot';

export * from '@agnos-ui/react-headless/components/progressbar';

function DefaultSlotContent(slotContext: ProgressbarContext) {
	const classList = ['progress-bar'];
	if (slotContext.state.striped) {
		classList.push('progress-bar-striped');
	}
	if (slotContext.state.animated) {
		classList.push('progress-bar-animated');
	}
	if (slotContext.state.className) {
		classList.push(slotContext.state.className);
	}
	return (
		<div className="progress" style={{height: slotContext.state.height}}>
			<div className={classList.join(' ')} style={{width: `${slotContext.state.percentage}%`}}>
				<Slot slotContent={slotContext.state.slotDefault} props={slotContext} />
			</div>
		</div>
	);
}

const defaultConfig: Partial<ProgressbarProps> = {
	slotStructure: DefaultSlotContent,
};

export const Progressbar = (props: PropsWithChildren<Partial<ProgressbarProps>>) => {
	const [state, widget] = useWidgetWithConfig(createProgressbar, props, 'progressbar', {...defaultConfig, slotDefault: props.children});
	const slotContext: ProgressbarContext = {state, widget: toSlotContextWidget(widget)};
	return (
		<div
			role="progressbar"
			aria-label={state.ariaLabel || undefined}
			aria-valuenow={state.value}
			aria-valuemin={state.min}
			aria-valuemax={state.max}
			aria-valuetext={state.ariaValueText}
		>
			<Slot slotContent={state.slotStructure} props={slotContext} />
		</div>
	);
};
