// svelte/bootstrap/src/components/rating/Rating.svelte
<script lang="ts">
	import type {RatingApi, RatingProps, RatingSlots} from './rating';
	import {createRating} from './rating';
	import {callWidgetFactory} from '../../config';
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {classDirective, ssrAttributes} from '@agnos-ui/svelte-headless/utils/directive';

	type $$Props = Partial<RatingProps>;
	type $$Slots = RatingSlots;

	export let rating: number | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createRating,
		widgetName: 'rating',
		$$slots,
		$$props,
		events: {
			onRatingChange: (value: number) => {
				rating = value;
			},
		},
	});
	export const api: RatingApi = widget.api;

	const {
		stores: {visibleRating$, stars$, slotStar$},
		directives: {containerDirective, starDirective},
	} = widget;

	$: widget.patchChangedProps($$props);
</script>

<div use:containerDirective class="d-inline-flex" {...ssrAttributes([classDirective, 'd-inline-flex'], containerDirective)}>
	<!-- on:blur={onTouched} ?? -->
	{#each $stars$ as { fill, index }}
		<span class="visually-hidden">({index < $visibleRating$ ? '*' : ' '})</span>
		<span use:starDirective={{index}} {...ssrAttributes([starDirective, {index}])}>
			<Slot slotContent={$slotStar$} props={{fill, index}} let:component let:props>
				<svelte:fragment slot="slot" let:props><slot name="star" {...props} /></svelte:fragment>
				<svelte:component this={component} {...props} />
			</Slot>
		</span>
	{/each}
</div>

// react/bootstrap/src/components/rating/rating.tsx
import {Slot} from '@agnos-ui/react-headless/slot';
import {classDirective, useDirective, useDirectives} from '@agnos-ui/react-headless/utils/directive';
import React from 'react';
import {useWidgetWithConfig} from '../../config';
import type {RatingDirectives, RatingProps, RatingState, StarContext} from './rating.gen';
import {createRating} from './rating.gen';

function Star({star, state, directive}: {star: StarContext; state: RatingState; directive: RatingDirectives['starDirective']}) {
	const arg = {index: star.index};
	return (
		<React.Fragment key={star.index}>
			<span className="visually-hidden">({star.index < state.visibleRating ? '*' : ' '})</span>
			<span {...useDirective(directive, arg)}>
				<Slot slotContent={state.star} props={star}></Slot>
			</span>
		</React.Fragment>
	);
}

export function Rating(props: Partial<RatingProps>) {
	const {
		state,
		directives: {containerDirective, starDirective},
	} = useWidgetWithConfig(createRating, props, 'rating');

	return (
		<div {...useDirectives([classDirective, 'd-inline-flex'], containerDirective)}>
			{state.stars.map((star) => (
				<Star key={star.index} star={star} state={state} directive={starDirective} />
			))}
		</div>
	);
}
