// angular/demo/bootstrap/src/app/app.component.ts
import type {OnInit} from '@angular/core';
import {Component} from '@angular/core';
import {RouterModule} from '@angular/router';

@Component({
	selector: 'app-root',
	imports: [RouterModule],
	template: `<router-outlet />`,
})
export class AppComponent implements OnInit {
	ngOnInit() {
		window.addEventListener('storage', (event) => {
			if (event.key === 'theme') {
				if (event.newValue) {
					document.documentElement.setAttribute('data-bs-theme', event.newValue);
				}
			}
		});
	}
}

// svelte/demo/src/daisyui/App.svelte
<script lang="ts">
	import './app.css';
	import AppCommon from '../common/AppCommon.svelte';
	import {onMount} from 'svelte';
	const componentsToBeProcessed = import.meta.glob('./samples/*/*.route.svelte');
	onMount(() => {
		window.addEventListener('storage', (event) => {
			if (event.key === 'theme') {
				if (event.newValue) {
					document.documentElement.setAttribute('data-theme', event.newValue);
				}
			}
		});
	});
</script>

<AppCommon {componentsToBeProcessed} />
