// react/lib/Select.tsx
import type {ItemCtx, WidgetProps} from '@agnos-ui/core';
import {createSelect} from '@agnos-ui/core';
import type {SyntheticEvent} from 'react';
import type {AdaptWidgetSlots} from './Slot';
import {useDirective, useWidgetWithConfig} from './utils';

export type SelectWidget<Item> = AdaptWidgetSlots<ReturnType<typeof createSelect<Item>>>;
export type SelectProps<Item> = WidgetProps<SelectWidget<Item>>;

const inputGroupText = {
	backgroundColor: 'transparent',
};

function preventDefault(e: SyntheticEvent) {
	e.preventDefault();
}

function Badges<Item>({api, selected}: {api: SelectWidget<Item>; selected: Item[]}) {
	const badges = [];
	for (const item of selected) {
		badges.push(
			<div className="badge rounded-pill text-bg-primary d-inline-flex align-items-center m-1" onMouseDown={preventDefault}>
				<div className="me-1">{'' + item}</div>
				<span role="button" tabIndex={-1} aria-label="Close" onClick={() => api.api.unselect(item)}>
					x
				</span>
			</div>
		);
	}

	return badges.length ? (
		<div className="input-group-text" style={inputGroupText}>
			{badges}
		</div>
	) : null;
}

function Rows<Item>({visible, highlighted}: {visible: ItemCtx<Item>[]; highlighted: ItemCtx<Item> | undefined}) {
	return (
		<>
			{visible.map((itemCtx) => {
				const id = `au-select-checkbox-${itemCtx.id}`;
				const classname = ['dropdown-item position-relative'];
				if (itemCtx === highlighted) {
					classname.push('bg-light');
				}
				return (
					<li key={itemCtx.id} className={classname.join(' ')}>
						<div className="form-check">
							<input id={id} tabIndex={-1} type="checkbox" className="form-check-input" checked={itemCtx.selected} onChange={itemCtx.toggle} />
							<label
								htmlFor={id}
								className="form-check-label stretched-link"
								onClick={(e) => {
									itemCtx.toggle();
									e.preventDefault();
								}}
							>
								{'' + itemCtx.item}
							</label>
						</div>
					</li>
				);
			})}
		</>
	);
}

export function Select<Item>(props: Partial<SelectProps<Item>>) {
	const [state, widget] = useWidgetWithConfig<SelectWidget<Item>>(createSelect, props, 'select');
	const {visible, selected, highlighted, filterText, opened, className} = state;

	const {
		directives: {hasFocusDirective},
	} = widget;
	const refSetInput = useDirective(hasFocusDirective);
	const refSetMenu = useDirective(hasFocusDirective);

	return (
		<div className={`au-select dropdown input-group input-group-sm mb-3 d-block ${className}`}>
			<div ref={refSetInput} role="combobox" className="input-group" aria-haspopup="listbox" aria-expanded="true">
				<Badges api={widget} selected={selected}></Badges>
				<input
					className="form-control"
					type="text"
					value={filterText}
					aria-autocomplete="list"
					autoCorrect="off"
					autoCapitalize="none"
					autoComplete="off"
					onKeyDown={widget.actions.onInputKeydown}
					onInput={widget.actions.onInput}
				/>
			</div>
			{opened && visible.length > 0 && (
				<ul
					ref={refSetMenu}
					className="dropdown-menu show w-100"
					style={{
						position: 'absolute',
						inset: '0px auto auto 0px',
						margin: '0px',
						transform: 'translate3d(0px, 45px, 0px)',
					}}
					data-popper-placement="bottom-start"
					onMouseDown={preventDefault}
				>
					<Rows visible={visible} highlighted={highlighted}></Rows>
				</ul>
			)}
		</div>
	);
}

// angular/lib/src/lib/select/select.component.ts
import type {WidgetProps, WidgetState, ItemCtx} from '@agnos-ui/core';
import {createSelect} from '@agnos-ui/core';
import {CommonModule} from '@angular/common';
import type {OnChanges, Signal, SimpleChanges} from '@angular/core';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output} from '@angular/core';
import {toSignal} from '@angular/core/rxjs-interop';
import type {AdaptWidgetSlots} from '../slot.directive';
import {callWidgetFactory} from '../slot.directive';
import {UseDirective} from '../transition/use.directive';
import {patchSimpleChanges} from '../utils';

export type SelectWidget<Item> = AdaptWidgetSlots<ReturnType<typeof createSelect<Item>>>;
export type SelectProps<Item> = WidgetProps<SelectWidget<Item>>;

@Component({
	standalone: true,
	imports: [UseDirective, CommonModule],
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'au-select',
	templateUrl: './select.component.html',
	styles: [],
	host: {
		'[class]': '"au-select dropdown input-group input-group-sm mb-3 " + state$().className',
		style: 'display: block',
	},
})
export class SelectComponent<Item> implements OnChanges {
	/**
	 * List of available items for the dropdown
	 */
	@Input() items: Item[] | undefined;

	/**
	 * true if the select is open
	 */
	@Input() opened: boolean | undefined;

	/**
	 * Filtered text to be display in the filter input
	 */
	@Input() filterText: string | undefined;

	@Input() className: string | undefined;

	/**
	 * Callback called when the text filter change
	 */
	@Output() filterTextChange = new EventEmitter<string>();

	/**
	 * true if the select is disabled
	 */
	@Input() disabled: boolean | undefined;

	/**
	 * Custom function to filter an item.
	 * By default, item is considered as a string, and the function returns true if the text is found
	 */
	@Input() matchFn: ((item: Item, text: string) => boolean) | undefined;

	/**
	 * Custom function to get the id of an item
	 * By default, the item is returned
	 */
	@Input() itemId: ((item: Item) => string) | undefined;

	/**
	 * List of selected items
	 */
	@Input() selected: Item[] | undefined;

	/**
	 * true if a loading process is being done
	 */
	@Input() loading: boolean | undefined;

	readonly _widget = callWidgetFactory<SelectWidget<Item>>(createSelect, 'select');
	readonly api = this._widget.api;

	state$: Signal<WidgetState<SelectWidget<Item>>> = toSignal(this._widget.state$, {requireSync: true});

	constructor() {
		this._widget.patch({
			onFilterTextChange: (event) => this.filterTextChange.emit(event),
		});
	}

	ngOnChanges(changes: SimpleChanges) {
		patchSimpleChanges(this._widget.patch, changes);
	}

	itemCtxTrackBy(_: number, itemCtx: ItemCtx<Item>) {
		return itemCtx.id;
	}
}

<ng-container>
	<div [auUse]="_widget.directives.hasFocusDirective" role="combobox" class="input-group" aria-haspopup="listbox" aria-expanded="true">
		<ng-container *ngIf="state$().selected as selected">
			<div *ngIf="selected.length" class="input-group-text" (mousedown)="$event.preventDefault()">
				<div *ngFor="let item of selected" class="badge rounded-pill text-bg-primary d-inline-flex align-items-center m-1">
					<div class="me-1">{{ item }}</div>
					<span role="button" tabindex="-1" aria-label="Close" (click)="api.unselect(item)">x</span>
				</div>
			</div>
		</ng-container>
		<input
			type="text"
			class="form-control"
			[value]="state$().filterText"
			aria-autocomplete="list"
			autoCorrect="off"
			autoCapitalize="none"
			autoComplete="off"
			(keydown)="_widget.actions.onInputKeydown($event)"
			(input)="_widget.actions.onInput($event)"
		/>
	</div>
	<ul
		*ngIf="state$().opened && state$().visible.length"
		[auUse]="_widget.directives.hasFocusDirective"
		class="dropdown-menu show w-100"
		data-popper-placement="bottom-start"
		(mousedown)="$event.preventDefault()"
	>
		<li
			*ngFor="let itemCtx of state$().visible; trackBy: itemCtxTrackBy"
			class="dropdown-item position-relative"
			[class.bg-light]="itemCtx === state$().highlighted"
		>
			<div class="form-check">
				<input type="checkbox" tabindex="-1" class="form-check-input" [id]="itemCtx.id" [checked]="itemCtx.selected" (change)="itemCtx.toggle()" />
				<label [for]="itemCtx.id" class="form-check-label stretched-link" (click)="itemCtx.toggle(); $event.preventDefault()">
					{{ itemCtx.item }}
				</label>
			</div>
		</li>
	</ul>
</ng-container>
<style>
	.input-group-text {
		background-color: transparent;
	}
	.dropdown-menu {
		position: absolute;
		inset: 0px auto auto 0px;
		margin: 0px;
		transform: translate3d(0px, 45px, 0px);
	}
</style>
