// angular/demo/bootstrap/src/app/links.component.ts
import {Component, inject} from '@angular/core';
import {links} from './links';

@Component({
	template: `
		<h3>Samples:</h3>
		<div class="sample-links">
			@for (url of links; track url) {
				<div>
					<a href="#/{{ url }}">{{ url }}</a>
				</div>
			}
		</div>
	`,
	styles: "@use '@agnos-ui/common/samples/links.scss';",
})
export default class LinksComponent {
	links = inject(links);
}

// react/demo/app/Links.tsx
import '@agnos-ui/common/samples/links.scss';

export function Links({links}: {links: string[]}) {
	return (
		<>
			<h3>Samples:</h3>
			<div className="sample-links">
				{links.map((url) => (
					<div key={url}>
						<a href={'#/' + url}>{url}</a>
					</div>
				))}
			</div>
		</>
	);
}

export default Links;
