// svelte/demo/src/bootstrap/samples/configuration/Basic.route.svelte
<script lang="ts">
	import {Alert} from '@agnos-ui/svelte/components/alert';
	import {createWidgetsDefaultConfig} from '@agnos-ui/svelte/config';

	createWidgetsDefaultConfig().set({alert: {dismissible: false}});
</script>

<Alert type="primary">Simple primary alert</Alert>
<Alert type="secondary">Simple secondary alert</Alert>

// react/demo/src/app/samples/configuration/Basic.route.tsx
import {Alert} from '@agnos-ui/react/components/alert';
import {WidgetsDefaultConfig} from '@agnos-ui/react/config';

const BasicDemo = () => (
	<WidgetsDefaultConfig alert={{dismissible: false}}>
		<Alert type="primary">Simple primary alert</Alert>
		<Alert type="secondary">Simple secondary alert</Alert>
	</WidgetsDefaultConfig>
);
export default BasicDemo;
