// angular/demo/src/app/samples/configuration/basic.route.ts
import {AlertComponent, provideWidgetsConfig, injectWidgetsConfig} from '@agnos-ui/angular';
import {Component} from '@angular/core';

@Component({
	standalone: true,
	imports: [AlertComponent],
	providers: [provideWidgetsConfig()],
	template: `
		<au-component auAlert auType="primary">Simple primary alert</au-component>
		<au-component auAlert auType="secondary">Simple secondary alert</au-component>
	`,
})
export default class GenericAlertComponent {
	readonly widgetConfig$ = injectWidgetsConfig({alert: {dismissible: false}});
}

// react/demo/src/app/samples/configuration/Basic.route.tsx
import {Alert} from '@agnos-ui/react/components/alert';
import {WidgetsDefaultConfig} from '@agnos-ui/react/config';

const BasicDemo = () => (
	<WidgetsDefaultConfig alert={{dismissible: false}}>
		<Alert type="primary">Simple primary alert</Alert>
		<Alert type="secondary">Simple secondary alert</Alert>
	</WidgetsDefaultConfig>
);
export default BasicDemo;
