// svelte/lib/src/components/slider/Slider.svelte
<script lang="ts" context="module">
	import type {SliderProps as Props} from '@agnos-ui/svelte-headless/components/slider';
	import {createSlider} from '@agnos-ui/svelte-headless/components/slider';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
</script>

<script lang="ts">
	// cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars

	export let values: number[] | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createSlider,
		widgetName: 'slider',
		$$slots,
		$$props,
		events: {
			onValuesChange: function (newValues: number[]): void {
				values = newValues;
			},
		},
	});

	const {
		stores: {
			className$,
			combinedLabelDisplay$,
			combinedLabelPositionLeft$,
			combinedLabelPositionTop$,
			disabled$,
			handleDisplayOptions$,
			max$,
			maxValueLabelDisplay$,
			min$,
			minValueLabelDisplay$,
			progressDisplayOptions$,
			readonly$,
			sortedHandles$,
			sortedValues$,
			values$,
			vertical$,
			showValueLabels$,
			showMinMaxLabels$,
			rtl$,
		},
		actions: {click, keydown, mouseDown, touchStart},
		directives: {sliderDirective, minLabelDirective, maxLabelDirective},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);
</script>

<!-- on:blur={onTouched} ?? -->
<div
	use:sliderDirective
	class={`au-slider ${$vertical$ ? 'au-slider-vertical' : 'au-slider-horizontal'} ${$className$}`}
	class:disabled={$disabled$}
	aria-disabled={$disabled$ ? true : null}
>
	{#each $progressDisplayOptions$ as option}
		<div
			class="au-slider-progress"
			style:left={`${option.left}%`}
			style:right={`${option.right}%`}
			style:bottom={`${option.bottom}%`}
			style:top={`${option.top}%`}
			style:width={`${option.width}%`}
			style:height={`${option.height}%`}
		/>
	{/each}
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<!-- svelte-ignore a11y-no-static-element-interactions -->
	<div class={$vertical$ ? 'au-slider-clickable-area-vertical' : 'au-slider-clickable-area'} on:click={click} />
	{#if $showMinMaxLabels$}
		<div
			class={`${$vertical$ ? 'au-slider-label-vertical au-slider-label-vertical-min' : 'au-slider-label au-slider-label-min'}`}
			class:invisible={!$minValueLabelDisplay$}
			class:au-slider-rtl={$rtl$}
			use:minLabelDirective
		>
			{$min$}
		</div>
		<div
			class={`${$vertical$ ? 'au-slider-label-vertical au-slider-label-vertical-max' : 'au-slider-label au-slider-label-max'}`}
			class:invisible={!$maxValueLabelDisplay$}
			class:au-slider-rtl={$rtl$}
			use:maxLabelDirective
		>
			{$max$}
		</div>
	{/if}
	{#if $showValueLabels$ && $combinedLabelDisplay$}
		<div
			class={$vertical$ ? 'au-slider-label-vertical au-slider-label-vertical-now' : 'au-slider-label au-slider-label-now'}
			style:left={`${$combinedLabelPositionLeft$}%`}
			style:top={`${$combinedLabelPositionTop$}%`}
		>
			{#if $rtl$}
				{$sortedValues$[1]} - {$sortedValues$[0]}
			{:else}
				{$sortedValues$[0]} - {$sortedValues$[1]}
			{/if}
		</div>
	{/if}
	{#each $sortedHandles$ as item, i (item.id)}
		<button
			class={`au-slider-handle ${$vertical$ ? 'au-slider-handle-vertical' : 'au-slider-handle-horizontal'}`}
			role="slider"
			aria-valuemin={$min$}
			aria-valuemax={$max$}
			aria-readonly={$readonly$ ? true : null}
			aria-disabled={$disabled$ ? true : null}
			aria-valuenow={item.value}
			aria-valuetext={item.ariaValueText}
			aria-label={item.ariaLabel}
			aria-orientation={$vertical$ ? 'vertical' : null}
			disabled={$disabled$ ? true : null}
			style:left={`${$handleDisplayOptions$[item.id].left}%`}
			style:top={`${$handleDisplayOptions$[item.id].top}%`}
			on:keydown={(e) => keydown(e, item.id)}
			on:mousedown={(e) => mouseDown(e, item.id)}
			on:touchstart={(e) => touchStart(e, item.id)}
		>
			&nbsp;
		</button>
		{#if $showValueLabels$ && !$combinedLabelDisplay$}
			<div
				class={$vertical$ ? 'au-slider-label-vertical au-slider-label-vertical-now' : 'au-slider-label au-slider-label-now'}
				style:left={`${$handleDisplayOptions$[i].left}%`}
				style:top={`${$handleDisplayOptions$[i].top}%`}
			>
				{$values$[i]}
			</div>
		{/if}
	{/each}
</div>

// react/lib/src/components/slider/slider.tsx
import type {SliderProps} from '@agnos-ui/react-headless/components/slider';
import {createSlider} from '@agnos-ui/react-headless/components/slider';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import React from 'react';

export * from '@agnos-ui/react-headless/components/slider';

export function Slider(props: Partial<SliderProps>) {
	const [
		{
			className,
			combinedLabelDisplay,
			combinedLabelPositionLeft,
			combinedLabelPositionTop,
			disabled,
			handleDisplayOptions,
			max,
			maxValueLabelDisplay,
			min,
			minValueLabelDisplay,
			progressDisplayOptions,
			readonly,
			sortedHandles,
			sortedValues,
			values,
			vertical,
			showValueLabels,
			showMinMaxLabels,
			rtl,
		},
		{
			actions: {click, keydown, mouseDown, touchStart},
			directives: {sliderDirective, minLabelDirective, maxLabelDirective},
		},
	] = useWidgetWithConfig(createSlider, props, 'slider');

	const sliderSetRef = useDirective(sliderDirective);
	const minSetRef = useDirective(minLabelDirective);
	const maxSetRef = useDirective(maxLabelDirective);

	return (
		<div
			ref={sliderSetRef}
			className={`au-slider ${vertical ? 'au-slider-vertical' : 'au-slider-horizontal'} ${className} ${disabled ? ' disabled' : ''}`}
			aria-disabled={disabled ? 'true' : undefined}
		>
			{progressDisplayOptions.map((option, index) => (
				<div
					key={index}
					className={'au-slider-progress'}
					style={{
						left: `${option.left}%`,
						right: `${option.right}%`,
						bottom: `${option.bottom}%`,
						top: `${option.top}%`,
						width: `${option.width}%`,
						height: `${option.height}%`,
					}}
				/>
			))}
			<div
				className={vertical ? 'au-slider-clickable-area-vertical' : 'au-slider-clickable-area'}
				onClick={(e) => click(e as unknown as MouseEvent)}
			/>
			{showMinMaxLabels ? (
				<>
					<div
						ref={minSetRef}
						className={`${rtl ? 'au-slider-rtl' : ''} ${
							vertical ? 'au-slider-label-vertical au-slider-label-vertical-min' : 'au-slider-label au-slider-label-min'
						} ${!minValueLabelDisplay ? ' invisible' : ''}
						`}
					>
						{min}
					</div>
					<div
						ref={maxSetRef}
						className={`${rtl ? 'au-slider-rtl' : ''} ${
							vertical ? 'au-slider-label-vertical au-slider-label-vertical-max' : 'au-slider-label au-slider-label-max'
						} ${!maxValueLabelDisplay ? ' invisible' : ''}`}
					>
						{max}
					</div>
				</>
			) : (
				<></>
			)}
			{showValueLabels && combinedLabelDisplay ? (
				<div
					className={vertical ? 'au-slider-label-vertical au-slider-label-vertical-now' : 'au-slider-label au-slider-label-now'}
					style={{
						left: `${combinedLabelPositionLeft}%`,
						top: `${combinedLabelPositionTop}%`,
					}}
				>
					{rtl ? (
						<>
							{sortedValues[1]} - {sortedValues[0]}
						</>
					) : (
						<>
							{sortedValues[0]} - {sortedValues[1]}
						</>
					)}
				</div>
			) : (
				<></>
			)}

			{sortedHandles.map((item, i) => (
				<React.Fragment key={item.id}>
					<button
						className={`au-slider-handle ${vertical ? 'au-slider-handle-vertical' : 'au-slider-handle-horizontal'}`}
						role="slider"
						aria-valuemin={min}
						aria-valuemax={max}
						aria-valuenow={item.value}
						aria-valuetext={item.ariaValueText}
						aria-label={item.ariaLabel}
						aria-readonly={readonly ? 'true' : undefined}
						aria-disabled={disabled ? 'true' : undefined}
						aria-orientation={vertical ? 'vertical' : undefined}
						disabled={disabled}
						style={{
							top: `${handleDisplayOptions[item.id].top}%`,
							left: `${handleDisplayOptions[item.id].left}%`,
						}}
						onKeyDown={(e) => keydown(e as unknown as KeyboardEvent, item.id)}
						onMouseDown={(e) => mouseDown(e as unknown as MouseEvent, item.id)}
						onTouchStart={(e) => touchStart(e as unknown as TouchEvent, item.id)}
					>
						&nbsp;
					</button>
					{showValueLabels && !combinedLabelDisplay ? (
						<div
							className={vertical ? 'au-slider-label-vertical au-slider-label-vertical-now' : 'au-slider-label au-slider-label-now'}
							style={{
								left: `${handleDisplayOptions[i].left}%`,
								top: `${handleDisplayOptions[i].top}%`,
							}}
						>
							{values[i]}
						</div>
					) : (
						<></>
					)}
				</React.Fragment>
			))}
		</div>
	);
}
