// svelte/demo/src/app-tailwind/samples/pagination/Pagination.svelte
<script lang="ts" context="module">
	import type {PaginationProps as Props} from '@agnos-ui/svelte-headless/components/pagination';
	import {createPagination} from '@agnos-ui/svelte-headless/components/pagination';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
</script>

<script lang="ts">
	// // cf https://github.com/ota-meshi/eslint-plugin-svelte/issues/348
	type $$Props = Partial<Props>; // eslint-disable-line @typescript-eslint/no-unused-vars

	/**
	 *  The current page.
	 *
	 *  Page numbers start with `1`.
	 */
	export let page: Props['page'] | undefined = undefined;

	const widget = callWidgetFactory({
		factory: createPagination,
		widgetName: 'pagination',
		$$slots,
		$$props,
		events: {
			onPageChange: (value: number) => {
				page = value;
			},
		},
	});
	const {
		stores: {
			page$,
			boundaryLinks$,
			directionLinks$,
			nextDisabled$,
			previousDisabled$,
			ariaLabel$,
			ariaFirstLabel$,
			ariaPreviousLabel$,
			ariaNextLabel$,
			ariaLastLabel$,
			className$,
		},
		state$,
		actions: {first, previous, next, last},
		patchChangedProps,
	} = widget;
	$: patchChangedProps($$props);
</script>

<nav aria-label={$ariaLabel$}>
	<div class="join {$className$}">
		{#if $boundaryLinks$}
			<button
				class="join-item btn btn-outline"
				aria-label={$ariaFirstLabel$}
				on:click={() => first()}
				disabled={$previousDisabled$}
				aria-disabled={$previousDisabled$ ? 'true' : null}
				tabindex={$previousDisabled$ ? -1 : undefined}
			>
				<span aria-hidden="true"> « </span>
			</button>
		{/if}
		{#if $directionLinks$}
			<button
				class="join-item btn btn-outline"
				disabled={$previousDisabled$}
				aria-label={$ariaPreviousLabel$}
				on:click={() => previous()}
				tabindex={$previousDisabled$ ? -1 : undefined}
				aria-disabled={$previousDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> ‹ </span>
			</button>
		{/if}
		{#each $state$.pages as page, i}
			<button
				class="join-item btn btn-outline"
				class:btn-active={page === $state$.page}
				aria-current={page === $state$.page ? 'page' : null}
				tabindex={page === -1 ? -1 : $state$.disabled ? -1 : undefined}
				on:click={page === -1 ? () => {} : () => widget.actions.select(page)}
				disabled={page === -1 || $state$.disabled}
				>{page}
				{#if $state$.page === page}<span class="sr-only">{$state$.activeLabel}</span>{/if}
			</button>
		{/each}
		{#if $directionLinks$}
			<button
				class="join-item btn btn-outline"
				disabled={$nextDisabled$}
				aria-label={$ariaNextLabel$}
				on:click={() => next()}
				tabindex={$nextDisabled$ ? -1 : undefined}
				aria-disabled={$nextDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> › </span>
			</button>
		{/if}
		{#if $boundaryLinks$}
			<button
				class="join-item btn btn-outline"
				aria-label={$ariaLastLabel$}
				on:click={() => last()}
				disabled={$nextDisabled$}
				tabindex={$nextDisabled$ ? -1 : undefined}
				aria-disabled={$nextDisabled$ ? 'true' : null}
			>
				<span aria-hidden="true"> » </span>
			</button>
		{/if}
	</div>
	<div aria-live="polite" class="sr-only">
		{`Current page is ${$page$}`}
	</div>
</nav>

// react/demo/src/app-tailwind/samples/pagination/Pagination.tsx
import {type PaginationProps, createPagination} from '@agnos-ui/react-headless/components/pagination';
import {useWidgetWithConfig} from '@agnos-ui/react-headless/config';
import classNames from 'classnames';

export function Pagination(props: Partial<PaginationProps>) {
	const [
		state,
		{
			actions: {first, last, next, previous, select},
		},
	] = useWidgetWithConfig(createPagination, props, 'pagination', {});

	return (
		<nav aria-label={state.ariaLabel}>
			<div className={classNames('join', state.className)}>
				{state.boundaryLinks && (
					<button
						className="join-item btn btn-outline"
						aria-label={state.ariaFirstLabel}
						onClick={() => first()}
						disabled={state.previousDisabled}
						aria-disabled={state.previousDisabled ? 'true' : undefined}
						tabIndex={state.previousDisabled ? -1 : undefined}
					>
						<span aria-hidden="true"> « </span>
					</button>
				)}
				{state.directionLinks && (
					<button
						className="join-item btn btn-outline"
						disabled={state.previousDisabled}
						aria-label={state.ariaPreviousLabel}
						onClick={() => previous()}
						tabIndex={state.previousDisabled ? -1 : undefined}
						aria-disabled={state.previousDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> ‹ </span>
					</button>
				)}
				{state.pages.map((page) => (
					<button
						key={page}
						className={classNames('join-item', 'btn', 'btn-outline', page === state.page ? 'btn-active' : '')}
						aria-current={page === state.page ? 'page' : undefined}
						tabIndex={page === -1 ? -1 : state.disabled ? -1 : undefined}
						onClick={page === -1 ? () => {} : () => select(page)}
						disabled={page === -1 || state.disabled}
					>
						{page}
						{state.page === page && <span className="sr-only">{state.activeLabel}</span>}
					</button>
				))}
				{state.directionLinks && (
					<button
						className="join-item btn btn-outline"
						disabled={state.nextDisabled}
						aria-label={state.ariaNextLabel}
						onClick={() => next()}
						tabIndex={state.nextDisabled ? -1 : undefined}
						aria-disabled={state.nextDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> › </span>
					</button>
				)}
				{state.boundaryLinks && (
					<button
						className="join-item btn btn-outline"
						aria-label={state.ariaLastLabel}
						onClick={() => last()}
						disabled={state.nextDisabled}
						tabIndex={state.nextDisabled ? -1 : undefined}
						aria-disabled={state.nextDisabled ? 'true' : undefined}
					>
						<span aria-hidden="true"> » </span>
					</button>
				)}
			</div>
			<div aria-live="polite" className="sr-only">
				{`Current page is ${state.page}`}
			</div>
		</nav>
	);
}
