// react/demo/app/samples/transition/InnerComponent.tsx
import {writable} from '@amadeus-it-group/tansu';
import type {TransitionFn} from '@agnos-ui/core';
import {bootstrap, createTransition} from '@agnos-ui/core';
import {useDirective, useObservable, useWidget} from '@agnos-ui/react';

const paramTransition$ = writable(bootstrap.collapseVerticalTransition);
const paramAnimation$ = writable(true);
const paramAnimationOnInit$ = writable(false);
const paramVisible$ = writable(true);
const paramRemoveFromDom$ = writable(true);

const InnerComponent = () => {
	const paramTransition = useObservable(paramTransition$);
	const paramAnimation = useObservable(paramAnimation$);
	const paramAnimationOnInit = useObservable(paramAnimationOnInit$);
	const paramVisible = useObservable(paramVisible$);
	const paramRemoveFromDom = useObservable(paramRemoveFromDom$);
	const [transitionState, transitionWidget] = useWidget(
		createTransition,
		{
			transition: paramTransition,
			animation: paramAnimation,
		},
		{
			animationOnInit: paramAnimationOnInit,
			visible: paramVisible,
		}
	);
	const transitionRef = useDirective(transitionWidget.directives.directive);
	paramVisible$.set(transitionState.visible);

	const changeTransition = (newTransition: TransitionFn) => {
		// Make sure the element is removed from the DOM
		// so that it does not keep state from the previous transition
		transitionWidget.api.toggle(false, false);
		paramRemoveFromDom$.set(true);
		paramTransition$.set(newTransition);
	};

	return (
		<>
			<div className="transition-inner">
				<p className="mt-2">
					Transition:
					<button
						type="button"
						className={`ms-2 btn btn-sm btn-outline-secondary ${paramTransition === bootstrap.collapseVerticalTransition ? 'active' : ''}`}
						onClick={() => changeTransition(bootstrap.collapseVerticalTransition)}
					>
						Vertical collapse
					</button>
					<button
						type="button"
						className={`ms-2 btn btn-sm btn-outline-secondary ${paramTransition === bootstrap.collapseHorizontalTransition ? 'active' : ''}`}
						onClick={() => changeTransition(bootstrap.collapseHorizontalTransition)}
					>
						Horizontal collapse
					</button>
					<button
						type="button"
						className={`ms-2 btn btn-sm btn-outline-secondary ${paramTransition === bootstrap.fadeTransition ? 'active' : ''}`}
						onClick={() => changeTransition(bootstrap.fadeTransition)}
					>
						Fade
					</button>
				</p>
				<label className="form-check">
					<input type="checkbox" className="form-check-input" checked={paramAnimation} onChange={() => paramAnimation$.set(!paramAnimation)} />
					Animation
				</label>
				<label className="form-check">
					<input
						type="checkbox"
						className="form-check-input"
						checked={paramAnimationOnInit}
						onChange={() => paramAnimationOnInit$.set(!paramAnimationOnInit)}
					/>
					Animation on init
				</label>
				<label className="form-check">
					<input
						type="checkbox"
						className="form-check-input"
						checked={paramRemoveFromDom}
						onChange={() => paramRemoveFromDom$.set(!paramRemoveFromDom)}
					/>
					Remove from DOM
				</label>
				<label className="form-check mb-2">
					<input
						type="checkbox"
						className="form-check-input"
						checked={transitionState.visible}
						onChange={() => transitionWidget.patch({visible: !transitionState.visible})}
					/>
					Visible
				</label>

				<button type="button" className="btn btn-outline-primary" onClick={() => transitionWidget.api.toggle()}>
					Toggle
				</button>
				<button type="button" className="ms-2 btn btn-outline-primary" onClick={() => transitionWidget.api.toggle(undefined, true)}>
					Toggle with animation
				</button>
				<button type="button" className="ms-2 btn btn-outline-primary" onClick={() => transitionWidget.api.toggle(undefined, false)}>
					Toggle without animation
				</button>
				<ul className="mt-2">
					<li>visible = {transitionState.visible + ''}</li>
					<li>transitioning = {transitionState.transitioning + ''}</li>
					<li>shown = {transitionState.shown + ''}</li>
					<li>hidden = {transitionState.hidden + ''}</li>
				</ul>

				{paramRemoveFromDom && transitionState.hidden ? null : (
					<div ref={transitionRef} style={{maxWidth: '300px'}}>
						<div className="card" style={{width: '300px'}}>
							<div className="card-body">You can collapse this card by clicking Toggle</div>
						</div>
					</div>
				)}
			</div>
		</>
	);
};
export default InnerComponent;

// svelte/demo/samples/transition/InnerComponent.svelte
<script context="module" lang="ts">
	import {writable} from '@amadeus-it-group/tansu';
	import type {TransitionFn} from '@agnos-ui/core';
	import {bootstrap, createTransition} from '@agnos-ui/core';

	const paramTransition$ = writable(bootstrap.collapseVerticalTransition);
	const paramAnimation$ = writable(true);
	const paramAnimationOnInit$ = writable(false);
	const paramVisible$ = writable(true);
	const paramRemoveFromDom$ = writable(true);
</script>

<script lang="ts">
	const {
		stores: {visible$, transitioning$, shown$, hidden$},
		api: {toggle},
		directives: {directive},
		patch,
	} = createTransition({
		props: {
			animationOnInit: paramAnimationOnInit$,
			animation: paramAnimation$,
			visible: paramVisible$,
		},
	});

	const checkBoxVisible$ = {
		subscribe: visible$.subscribe,
		set: (value: boolean) => patch({visible: value}),
	};

	const changeTransition = (newTransition: TransitionFn) => {
		// Make sure the element is removed from the DOM
		// so that it does not keep state from the previous transition
		toggle(false, false);
		$paramRemoveFromDom$ = true;
		$paramTransition$ = newTransition;
	};
</script>

<div class="transition-inner">
	<p class="mt-2">
		Transition:
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === bootstrap.collapseVerticalTransition}
			on:click={() => changeTransition(bootstrap.collapseVerticalTransition)}>Vertical collapse</button
		>
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === bootstrap.collapseHorizontalTransition}
			on:click={() => changeTransition(bootstrap.collapseHorizontalTransition)}>Horizontal collapse</button
		>
		<button
			type="button"
			class="ms-2 btn btn-sm btn-outline-secondary"
			class:active={$paramTransition$ === bootstrap.fadeTransition}
			on:click={() => changeTransition(bootstrap.fadeTransition)}>Fade</button
		>
	</p>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramAnimation$} />Animation</label>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramAnimationOnInit$} />Animation on init</label>
	<label class="form-check"><input type="checkbox" class="form-check-input" bind:checked={$paramRemoveFromDom$} />Remove from DOM</label>
	<label class="form-check mb-2"><input type="checkbox" class="form-check-input" bind:checked={$checkBoxVisible$} />Visible</label>

	<button type="button" class="btn btn-outline-primary" on:click={() => toggle()}>Toggle</button>
	<button type="button" class="ms-2 btn btn-outline-primary" on:click={() => toggle(undefined, true)}>Toggle with animation</button>
	<button type="button" class="ms-2 btn btn-outline-primary" on:click={() => toggle(undefined, false)}>Toggle without animation</button>

	<ul class="mt-2">
		<li>visible = {$visible$}</li>
		<li>transitioning = {$transitioning$}</li>
		<li>shown = {$shown$}</li>
		<li>hidden = {$hidden$}</li>
	</ul>

	{#if !$paramRemoveFromDom$ || !$hidden$}
		<div use:directive={{transition: $paramTransition$, animation: $paramAnimation$}} style="max-width: 300px;">
			<div class="card" style="width: 300px;">
				<div class="card-body">You can collapse this card by clicking Toggle</div>
			</div>
		</div>
	{/if}
</div>
