// react/demo/app/samples/transition/Transition.route.tsx
import {useState} from 'react';
import InnerComponent from './InnerComponent';

const Transition = () => {
	const [showComponent, setShowComponent] = useState(true);
	return (
		<>
			<h2>Transition example</h2>
			<div className="demo-transition mb-3">
				<button id="toggle-component" className="btn btn-outline-secondary" onClick={() => setShowComponent(!showComponent)}>
					Toggle component
				</button>
				{showComponent && <InnerComponent />}
			</div>
		</>
	);
};
export default Transition;

// svelte/demo/samples/transition/Transition.route.svelte
<script lang="ts">
	import InnerComponent from './InnerComponent.svelte';

	let showComponent = true;
</script>

<h2>Transition example</h2>
<div class="demo-transition mb-3">
	<button id="toggle-component" class="btn btn-outline-secondary" on:click={() => (showComponent = !showComponent)}>Toggle component</button>
	{#if showComponent}
		<InnerComponent />
	{/if}
</div>
