// angular/demo/daisyui/src/app/samples/alert/alert.component.ts
import type {AlertProps, AlertWidget} from '@agnos-ui/angular-headless';
import {BaseWidgetDirective, auBooleanAttribute, callWidgetFactory, createAlert} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, EventEmitter, Input, Output} from '@angular/core';

@Component({
	selector: 'app-alert',
	template: `
		@if (!state().hidden) {
			<div role="alert" class="alert {{ state().className }}">
				<ng-content />
				@if (state().dismissible) {
					<button class="btn btn-sm btn-circle btn-ghost justify-self-end" (click)="api.close()" [attr.aria-label]="state().ariaCloseButtonLabel">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
						</svg>
					</button>
				}
			</div>
		}
	`,
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent extends BaseWidgetDirective<AlertWidget> {
	@Input({transform: auBooleanAttribute})
	dismissible?: AlertProps['dismissible'];
	@Input({transform: auBooleanAttribute})
	visible?: AlertProps['visible'];
	@Input() ariaCloseButtonLabel?: AlertProps['ariaCloseButtonLabel'];
	@Input() className?: AlertProps['className'];
	@Output() visibleChange = new EventEmitter<boolean>();
	@Output() hidden = new EventEmitter<void>();
	@Output() shown = new EventEmitter<void>();

	readonly _widget = callWidgetFactory({
		factory: createAlert,
		widgetName: 'alert',
		events: {
			onVisibleChange: (event) => this.visibleChange.emit(event),
			onShown: () => this.shown.emit(),
			onHidden: () => this.hidden.emit(),
		},
	});
}

// svelte/demo/src/daisyui/samples/alert/Alert.svelte
<script lang="ts">
	import {createAlert} from '@agnos-ui/svelte-headless/components/alert';
	import type {AlertProps} from '@agnos-ui/svelte-headless/components/alert';
	import {callWidgetFactory} from '@agnos-ui/svelte-headless/config';
	type $$Props = Partial<Pick<AlertProps, 'className' | 'visible' | 'dismissible' | 'ariaCloseButtonLabel'>>;
	export const {
		stores: {className$, dismissible$, ariaCloseButtonLabel$, hidden$},
		patchChangedProps,
		api,
	} = callWidgetFactory({
		factory: createAlert,
		widgetName: 'alert',
		$$props,
		events: {
			onVisibleChange: (event) => {
				visible = event;
			},
		},
	});

	export let visible: boolean | undefined = undefined;

	$: patchChangedProps($$props);
</script>

{#if !$hidden$}
	<div role="alert" class="alert {$className$}">
		<slot />
		{#if $dismissible$}
			<button class="btn btn-sm btn-circle btn-ghost justify-self-end" on:click={api.close} aria-label={$ariaCloseButtonLabel$}>
				<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"
					><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg
				>
			</button>
		{/if}
	</div>
{/if}
