// svelte/demo/src/bootstrap/samples/modal/Component.route.svelte
<script lang="ts">
	import {type ModalContext, openModal} from '@agnos-ui/svelte-bootstrap/components/modal';
	const onclick = () => openModal({title: 'Hi there!', children, contentData: {name: 'World'}});
</script>

{#snippet children({state, widget}: ModalContext<{name: string}>)}
	<p>Hello, {state.contentData.name}!</p>
	<button type="button" class="btn btn-outline-primary" onclick={() => widget.api.close()}>Close</button>
{/snippet}

<button type="button" class="btn btn-primary" {onclick}>Launch demo modal</button>

// react/demo/src/bootstrap/samples/modal/Component.route.tsx
import type {ModalContext} from '@agnos-ui/react-bootstrap/components/modal';
import {openModal} from '@agnos-ui/react-bootstrap/components/modal';

type ModalContent = {name: string};

const ModalBody = ({widget, state}: ModalContext<ModalContent>) => (
	<>
		<p>Hello, {state.contentData.name}!</p>
		<button type="button" className="btn btn-outline-primary" onClick={() => widget.api.close()}>
			Close
		</button>
	</>
);

export default () => (
	<button
		type="button"
		className="btn btn-primary"
		onClick={() => openModal({title: 'Hi there!', children: ModalBody, contentData: {name: 'World'}})}
	>
		Launch demo modal
	</button>
);
