// svelte/demo/src/bootstrap/samples/drawer/Basic.route.svelte
<script lang="ts">
	import {Drawer} from '@agnos-ui/svelte-bootstrap/components/drawer';

	// svelte-ignore non_reactive_update
	let drawer: Drawer;
</script>

<button class="btn btn-primary mb-3" onclick={() => drawer.api.open()}>Open Drawer</button>

<Drawer bind:this={drawer} header="Basic drawer" className="inline-start">
	<ul>
		<li>First item</li>
		<li>Second item</li>
		<li>Third item</li>
	</ul>
</Drawer>

// react/demo/src/bootstrap/samples/drawer/Basic.route.tsx
import type {DrawerApi} from '@agnos-ui/react-bootstrap/components/drawer';
import {Drawer} from '@agnos-ui/react-bootstrap/components/drawer';
import {useRef} from 'react';

const BasicDemo = () => {
	const refDrawer = useRef<DrawerApi>(null);

	return (
		<>
			<button className="btn btn-primary mb-3" onClick={() => refDrawer.current?.open()}>
				Open Drawer
			</button>
			<Drawer ref={refDrawer} className="inline-start" header={<>Hi, I am drawer!</>}>
				<ul>
					<li>First item</li>
					<li>Second item</li>
					<li>Third item</li>
				</ul>
			</Drawer>
		</>
	);
};

export default BasicDemo;
