// svelte/demo/src/bootstrap/samples/drawer/Sizes.route.svelte
<script lang="ts">
	import {Drawer} from '@agnos-ui/svelte-bootstrap/components/drawer';

	// svelte-ignore non_reactive_update
	let drawer: Drawer;
</script>

<button class="btn btn-primary mb-3" onclick={() => drawer.api.open()}>Open Drawer</button>

<Drawer bind:this={drawer} header="Hi, I am drawer!" className="drawer-custom-size inline-start" resizable>
	<ul>
		<li>First item</li>
		<li>Second item</li>
		<li>Third item</li>
	</ul>
</Drawer>

<style>
	:global(.drawer-custom-size) {
		--bs-drawer-size: 20rem;
		--bs-drawer-min-size: max-content;
		--bs-drawer-max-size: calc(100vw - 2rem);
	}
</style>

// react/demo/src/bootstrap/samples/drawer/Sizes.route.tsx
import type {DrawerApi} from '@agnos-ui/react-bootstrap/components/drawer';
import {Drawer} from '@agnos-ui/react-bootstrap/components/drawer';
import {useRef} from 'react';
import './sizes.css';

const BasicDemo = () => {
	const refDrawer = useRef<DrawerApi>(null);

	return (
		<>
			<button className="btn btn-primary mb-3" onClick={() => refDrawer.current?.open()}>
				Open Drawer
			</button>
			<Drawer ref={refDrawer} className="drawer-custom-size inline-start" header={<>Hi, I am drawer!</>} resizable>
				<ul>
					<li>First item</li>
					<li>Second item</li>
					<li>Third item</li>
				</ul>
			</Drawer>
		</>
	);
};

export default BasicDemo;
