// react/bootstrap/src/components/tree/tree.tsx
import {Slot} from '@agnos-ui/react-headless/slot';
import {useDirective} from '@agnos-ui/react-headless/utils/directive';
import {useWidget} from '../../config';
import type {TreeContext, TreeDirectives, NormalizedTreeItem, TreeProps, TreeSlotItemContext} from './tree.gen';
import {createTree} from './tree.gen';
import clsx from 'clsx';

const ToggleButtonDisplay = ({directive, item}: {directive: TreeDirectives['itemToggleDirective']; item: NormalizedTreeItem}) => {
	return (
		<button {...useDirective(directive, {item})}>
			<span className="au-tree-expand-icon-svg"></span>
		</button>
	);
};

/**
 * A functional component that renders a toggle element with a directive applied to it.
 * The directive is provided through the `slotContext` parameter.
 *
 * @param slotContext - The context object containing the directives and item the toggle.
 * @returns A toggle element with the applied directive.
 */
export const DefaultTreeSlotItemToggle = (slotContext: TreeSlotItemContext) => {
	const {directives, item} = slotContext;
	return item.children.length > 0 ? (
		<ToggleButtonDisplay directive={directives.itemToggleDirective} item={item} />
	) : (
		<span className="au-tree-expand-icon-placeholder"></span>
	);
};

/**
 * A functional component that renders a tree item content element.
 *
 * @param slotContext - The context object containing the item content for display.
 * @returns A tree item element.
 */
export const DefaultTreeSlotItemContent = (slotContext: TreeSlotItemContext) => {
	const {state, item} = slotContext;
	return (
		<>
			<span style={{width: '100%', height: '3px'}} {...useDirective(slotContext.directives.draggableDirective, {item, filler: true})}></span>
			<span className="au-tree-item" {...useDirective(slotContext.directives.draggableDirective, {item})}>
				<Slot slotContent={state.itemToggle} props={{...slotContext}} />
				{item.label}
			</span>
		</>
	);
};

/**
 * A functional component that renders a tree item element with a directive applied to it.
 * The directive is provided through the `slotContext` parameter.
 *
 * @param slotContext - The context object containing the directives and item for the tree item element.
 * @returns A tree root element with the applied directive.
 */
export const DefaultTreeSlotItem = (slotContext: TreeSlotItemContext) => {
	const {state, directives, item} = slotContext;
	return (
		<li {...useDirective(directives.itemAttributesDirective, {item})}>
			<Slot slotContent={state.itemContent} props={{...slotContext, item}} />
			{state.expandedMap.get(item) && (
				<ul role="group">
					{item.children.map((child, index) => (
						<Slot slotContent={state.item} props={{...slotContext, item: child}} key={child.label + child.level + index} />
					))}
				</ul>
			)}
		</li>
	);
};
/**
 * A functional component that renders a tree structure with a directive applied to it.
 * The directive is provided through the `slotContext` parameter.
 *
 * @param slotContext - The context object containing the directives and items for the tree display.
 * @returns A tree structure with the applied directive.
 */
export const DefaultTreeSlotStructure = (slotContext: TreeContext) => {
	const {state} = slotContext;
	return (
		<ul role="tree" className={clsx('au-tree', state.className)} {...useDirective(slotContext.directives.navigationDirective)}>
			{state.normalizedNodes.map((node, index) => (
				<Slot key={node.label + node.level + index} slotContent={state.item} props={{item: node, ...slotContext}} />
			))}
		</ul>
	);
};

const defaultConfig: Partial<TreeProps> = {
	structure: DefaultTreeSlotStructure,
	item: DefaultTreeSlotItem,
	itemContent: DefaultTreeSlotItemContent,
	itemToggle: DefaultTreeSlotItemToggle,
};

/**
 * Tree component that integrates with a widget context and renders a slot structure.
 *
 * @param props - The properties for the Tree component.
 * @returns The rendered Tree component.
 *
 * The Tree component uses the {@link useWidget} hook to create a widget context with the provided
 * configuration. It renders the slot content using the `Slot` component.
 */
export function Tree(props: Partial<TreeProps>) {
	const widgetContext = useWidget(createTree, props, {...defaultConfig});
	return <Slot slotContent={widgetContext.state.structure} props={widgetContext} />;
}

// angular/bootstrap/src/components/tree/tree.component.ts
import type {SlotContent} from '@agnos-ui/angular-headless';
import {BaseWidgetDirective, callWidgetFactory, ComponentTemplate, SlotDirective, UseDirective} from '@agnos-ui/angular-headless';
import {ChangeDetectionStrategy, Component, Directive, inject, input, output, TemplateRef, viewChild} from '@angular/core';
import type {NormalizedTreeItem, TreeContext, TreeItem, TreeSlotItemContext, TreeWidget} from './tree.gen';
import {createTree} from './tree.gen';

/**
 * Directive to provide a template reference for tree structure.
 *
 * This directive uses a template reference to render the {@link TreeContext}.
 */
@Directive({selector: 'ng-template[auTreeStructure]'})
export class TreeStructureDirective {
	public templateRef = inject(TemplateRef<TreeContext>);
	static ngTemplateContextGuard(_dir: TreeStructureDirective, context: unknown): context is TreeContext {
		return true;
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective, TreeStructureDirective, SlotDirective],
	template: `
		<ng-template auTreeStructure #structure let-state="state" let-directives="directives" let-api="api">
			<ul role="tree" class="au-tree {{ state.className() }}" [auUse]="directives.navigationDirective">
				@for (node of state.normalizedNodes(); track trackNode($index, node)) {
					<ng-template [auSlot]="state.item()" [auSlotProps]="{state, api, directives, item: node}" />
				}
			</ul>
		</ng-template>
	`,
})
class TreeDefaultStructureSlotComponent {
	readonly structure = viewChild.required<TemplateRef<TreeContext>>('structure');

	trackNode(index: number, node: NormalizedTreeItem): string {
		return node.label + node.level + index;
	}
}

/**
 * A constant representing the default slot for tree structure.
 */
export const treeDefaultSlotStructure: SlotContent<TreeContext> = new ComponentTemplate(TreeDefaultStructureSlotComponent, 'structure');

/**
 * Directive to provide a template reference for tree item toggle.
 *
 * This directive uses a template reference to render the {@link TreeSlotItemContext}.
 */
@Directive({selector: 'ng-template[auTreeItemToggle]'})
export class TreeItemToggleDirective {
	public templateRef = inject(TemplateRef<TreeSlotItemContext>);
	static ngTemplateContextGuard(_dir: TreeItemToggleDirective, context: unknown): context is TreeSlotItemContext {
		return true;
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective, TreeItemToggleDirective],
	template: `
		<ng-template auTreeItemToggle #toggle let-directives="directives" let-item="item">
			@if (item.children.length > 0) {
				<button [auUse]="[directives.itemToggleDirective, {item}]">
					<span class="au-tree-expand-icon-svg"></span>
				</button>
			} @else {
				<span class="au-tree-expand-icon-placeholder"></span>
			}
		</ng-template>
	`,
})
class TreeDefaultItemToggleSlotComponent {
	readonly toggle = viewChild.required<TemplateRef<TreeSlotItemContext>>('toggle');
}

/**
 * A constant representing the default slot for tree item toggle.
 */
export const treeDefaultItemToggle: SlotContent<TreeSlotItemContext> = new ComponentTemplate(TreeDefaultItemToggleSlotComponent, 'toggle');

/**
 * Directive to provide a template reference for tree item content.
 *
 * This directive uses a template reference to render the {@link TreeSlotItemContext}.
 */
@Directive({selector: 'ng-template[auTreeItemContent]'})
export class TreeItemContentDirective {
	public templateRef = inject(TemplateRef<TreeSlotItemContext>);
	static ngTemplateContextGuard(_dir: TreeItemContentDirective, context: unknown): context is TreeSlotItemContext {
		return true;
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [SlotDirective, TreeItemContentDirective, UseDirective],
	template: `
		<ng-template auTreeItemContent #treeItemContent let-state="state" let-directives="directives" let-item="item" let-api="api">
			<span style="width:100%; height:3px;" [auUse]="[directives.draggableDirective, {item: item, filler: true}]"></span>
			<span class="au-tree-item" [auUse]="[directives.draggableDirective, {item: item}]">
				<ng-template [auSlot]="state.itemToggle()" [auSlotProps]="{state, api, directives, item}" />
				{{ item.label }}
			</span>
		</ng-template>
	`,
})
class TreeDefaultItemContentSlotComponent {
	readonly treeItemContent = viewChild.required<TemplateRef<TreeSlotItemContext>>('treeItemContent');
}

/**
 * A constant representing the default slot for tree item.
 */
export const treeDefaultSlotItemContent: SlotContent<TreeSlotItemContext> = new ComponentTemplate(
	TreeDefaultItemContentSlotComponent,
	'treeItemContent',
);

/**
 * Directive to provide a template reference for tree item.
 *
 * This directive uses a template reference to render the {@link TreeSlotItemContext}.
 */
@Directive({selector: 'ng-template[auTreeItem]'})
export class TreeItemDirective {
	public templateRef = inject(TemplateRef<TreeSlotItemContext>);
	static ngTemplateContextGuard(_dir: TreeItemDirective, context: unknown): context is TreeSlotItemContext {
		return true;
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [UseDirective, SlotDirective, TreeItemDirective],
	template: `
		<ng-template auTreeItem #treeItem let-state="state" let-directives="directives" let-item="item" let-api="api">
			<li [auUse]="[directives.itemAttributesDirective, {item}]">
				<ng-template [auSlot]="state.itemContent()" [auSlotProps]="{state, api, directives, item}" />
				@if (state.expandedMap().get(item)) {
					<ul role="group">
						@for (child of item.children; track trackNode($index, child)) {
							<ng-template [auSlot]="state.item()" [auSlotProps]="{state, api, directives, item: child}" />
						}
					</ul>
				}
			</li>
		</ng-template>
	`,
})
class TreeDefaultItemSlotComponent {
	readonly treeItem = viewChild.required<TemplateRef<TreeSlotItemContext>>('treeItem');

	trackNode(index: number, node: NormalizedTreeItem) {
		return node.label + node.level + index;
	}
}

/**
 * A constant representing the default slot for tree item.
 */
export const treeDefaultSlotItem: SlotContent<TreeSlotItemContext> = new ComponentTemplate(TreeDefaultItemSlotComponent, 'treeItem');

/**
 * TreeComponent is an Angular component that extends the BaseWidgetDirective
 * to provide a customizable tree widget. This component allows for various
 * configurations and customizations through its inputs and outputs.
 */
@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: '[auTree]',

	imports: [SlotDirective],
	template: ` <ng-template [auSlot]="state.structure()" [auSlotProps]="{state, api, directives}" /> `,
})
export class TreeComponent extends BaseWidgetDirective<TreeWidget> {
	constructor() {
		super(
			callWidgetFactory(createTree, {
				defaultConfig: {
					structure: treeDefaultSlotStructure,
					item: treeDefaultSlotItem,
					itemContent: treeDefaultSlotItemContent,
					itemToggle: treeDefaultItemToggle,
				},
				events: {
					onExpandToggle: (item: NormalizedTreeItem) => this.expandToggle.emit(item),
				},
				slotTemplates: () => ({
					structure: this.slotStructureFromContent()?.templateRef,
					item: this.slotItemFromContent()?.templateRef,
					itemContent: this.slotItemContentFromContent()?.templateRef,
					itemToggle: this.slotItemToggleFromContent()?.templateRef,
				}),
			}),
		);
	}
	/**
	 * Optional accessibility label for the tree if there is no explicit label
	 *
	 * @defaultValue `''`
	 */
	readonly ariaLabel = input<string>(undefined, {alias: 'auAriaLabel'});
	/**
	 * Array of the tree nodes to display
	 *
	 * @defaultValue `[]`
	 */
	readonly nodes = input<TreeItem[]>(undefined, {alias: 'auNodes'});
	/**
	 * CSS classes to be applied on the widget main container
	 *
	 * @defaultValue `''`
	 */
	readonly className = input<string>(undefined, {alias: 'auClassName'});
	/**
	 * Retrieves expand items of the TreeItem
	 *
	 * @param node - HTML element that is representing the expand item
	 *
	 * @defaultValue
	 * ```ts
	 * (node: HTMLElement) => node.querySelectorAll('button')
	 * ```
	 */
	readonly navSelector = input<(node: HTMLElement) => NodeListOf<HTMLElement>>(undefined, {alias: 'auNavSelector'});
	/**
	 * Return the value for the 'aria-label' attribute of the toggle
	 * @param label - tree item label
	 *
	 * @defaultValue
	 * ```ts
	 * (label: string) => `Toggle ${label}`
	 * ```
	 */
	readonly ariaLabelToggleFn = input<(label: string) => string>(undefined, {alias: 'auAriaLabelToggleFn'});

	/**
	 * An event emitted when the user toggles the expand of the TreeItem.
	 *
	 * Event payload is equal to the TreeItem clicked.
	 *
	 * @defaultValue
	 * ```ts
	 * () => {}
	 * ```
	 */
	readonly expandToggle = output<NormalizedTreeItem>({alias: 'auExpandToggle'});

	/**
	 * Slot to change the default tree item content
	 */
	readonly itemContent = input<SlotContent<TreeSlotItemContext>>(undefined, {alias: 'auItemContent'});
	readonly slotItemContentFromContent = viewChild(TreeItemContentDirective);

	/**
	 * Slot to change the default display of the tree
	 */
	readonly structure = input<SlotContent<TreeContext>>(undefined, {alias: 'auStructure'});
	readonly slotStructureFromContent = viewChild(TreeStructureDirective);

	/**
	 * Slot to change the default tree item toggle
	 */
	readonly itemToggle = input<SlotContent<TreeSlotItemContext>>(undefined, {alias: 'auItemToggle'});
	readonly slotItemToggleFromContent = viewChild(TreeItemToggleDirective);

	/**
	 * Slot to change the default tree item
	 */
	readonly item = input<SlotContent<TreeSlotItemContext>>(undefined, {alias: 'auItem'});
	readonly slotItemFromContent = viewChild(TreeItemDirective);
}
