// svelte/demo/src/bootstrap/samples/drawer/Basic.route.svelte
<script lang="ts">
	import {Drawer} from '@agnos-ui/svelte-bootstrap/components/drawer';

	// svelte-ignore non_reactive_update
	let drawer: Drawer;
</script>

<button class="btn btn-primary mb-3" onclick={() => drawer.api.open()}>Open Drawer</button>

<Drawer bind:this={drawer} header="Basic drawer" className="inline-start">
	<ul>
		<li>First item</li>
		<li>Second item</li>
		<li>Third item</li>
	</ul>
</Drawer>

// angular/demo/bootstrap/src/app/samples/drawer/basic.route.ts
import {DrawerComponent, DrawerHeaderDirective} from '@agnos-ui/angular-bootstrap';
import {Component} from '@angular/core';

@Component({
	template: `
		<button class="btn btn-primary mb-3" (click)="drawer.api.open()">Open Drawer</button>
		<au-component #drawer auDrawer auClassName="inline-start">
			<ng-template auDrawerHeader> Hi, I am drawer! </ng-template>
			<ul>
				<li>First item</li>
				<li>Second item</li>
				<li>Third item</li>
			</ul>
		</au-component>
	`,
	imports: [DrawerComponent, DrawerHeaderDirective],
})
export default class BasicDrawerComponent {}
