// react/demo/src/bootstrap/samples/toast/Action.route.tsx
import type {ToastApi} from '@agnos-ui/react-bootstrap/components/toast';
import {Toast} from '@agnos-ui/react-bootstrap/components/toast';
import {WidgetsDefaultConfig} from '@agnos-ui/react-bootstrap/config';
import {useRef} from 'react';
import {ToastAction} from './ToastAction';

export default () => {
	const refToast = useRef<ToastApi>(null);

	function reset() {
		refToast.current?.open();
	}

	return (
		<>
			<p> To put the action in the toast simply create custom contents.</p>
			<p>
				<strong>Note:</strong> When header is not present default display is <code>flex</code>
			</p>
			<div className="col-auto col-md-6">
				<WidgetsDefaultConfig
					toast={{
						dismissible: true,
						className: 'text-bg-success',
						autoHide: false,
						structure: ToastAction,
					}}
				>
					<Toast ref={refToast}>This is a toast with action</Toast>
				</WidgetsDefaultConfig>
			</div>
			<button className="btn btn-primary mt-2" onClick={reset}>
				Reset
			</button>
		</>
	);
};

// svelte/demo/src/bootstrap/samples/toast/Action.route.svelte
<script lang="ts">
	import {Toast} from '@agnos-ui/svelte-bootstrap/components/toast';
	import {createWidgetsDefaultConfig} from '@agnos-ui/svelte-bootstrap/config';
	import ActionStructure from './ActionStructure.svelte';

	createWidgetsDefaultConfig().set({toast: {autoHide: false, dismissible: true, className: 'text-bg-success', structure: ActionStructure}});
	export let visible = true;

	function reset() {
		visible = true;
	}
</script>

<p>To put the action in the toast simply create custom contents.</p>
<p><strong>Note:</strong> When header is not present default display is <code>flex</code></p>
<div class="col-auto col-md-6">
	<Toast bind:visible>This is a toast with action</Toast>
</div>
<button class="btn btn-primary mt-2" on:click={() => reset()}>Reset</button>
