// angular/demo/bootstrap/src/app/samples/toast/toaster.route.ts
import {ToasterComponent, ToasterService, toastPositions} from '@agnos-ui/angular-bootstrap';
import {Component, effect, inject, signal} from '@angular/core';
import {FormsModule} from '@angular/forms';

@Component({
	imports: [ToasterComponent, FormsModule],
	template: `
		<p class="mb-2">Similar to dynamic stacking, we expose a service to ease the usage of Toasts</p>
		<div class="d-flex flex-column justify-content-between gap-2">
			<div class="d-flex flex-column flex-sm-row form-group align-items-center gap-3">
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="positionSelect">Position: </label>
					<select id="positionSelect" class="form-select w-auto" [(ngModel)]="position">
						@for (position of positions; track position) {
							<option [value]="position">{{ position }}</option>
						}
					</select>
				</div>
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="dismissible">Dismissible: </label>
					<input type="checkbox" class="form-check-input" id="dismissible" [disabled]="duration() === 0" [(ngModel)]="dismissible" />
				</div>
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="duration">Duration: </label>
					<input id="duration" type="number" class="form-control w-50" [(ngModel)]="duration" />
				</div>
			</div>
			<div class="d-flex flex-column flex-sm-row form-group align-items-center gap-3">
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="limit">Max # of toasts: </label>
					<input id="limit" type="number" class="form-control w-50" [(ngModel)]="limit" />
				</div>
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="pause">Pause timer on hover: </label>
					<input type="checkbox" class="form-check-input" id="pause" [(ngModel)]="pauseOnHover" />
				</div>
				<div class="d-flex w-100 align-items-center justify-content-between">
					<label class="me-3" for="closeAll">Close all toasts button</label>
					<input type="checkbox" class="form-check-input" id="closeAll" [(ngModel)]="closeAll" />
				</div>
			</div>
			<div class="d-flex form-group align-items-center gap-3 py-3">
				<button class="btn btn-primary ms-2" (click)="addToast()">Show toast</button>
				<button class="btn btn-primary ms-2" (click)="addToast('error')">Show error toast</button>
			</div>
		</div>
		<div class="d-flex position-relative mt-2 w-100" style="height: 500px; background-color: gray;"></div>
		<div
			auToaster
			[auDismissible]="dismissible()"
			[auDuration]="duration()"
			[auPosition]="position()"
			[auLimit]="limit()"
			[auCloseAll]="closeAll()"
		></div>
	`,
})
export default class ToasterExampleComponent {
	readonly toasterService = inject(ToasterService);
	readonly dismissible = signal(this.toasterService.options().dismissible);
	readonly duration = signal(this.toasterService.options().duration);
	readonly limit = signal(10);
	readonly pauseOnHover = signal(false);
	readonly closeAll = signal(false);
	readonly positions = Object.keys(toastPositions);

	readonly position = signal(this.toasterService.options().position);
	index = 0;

	constructor() {
		effect(() => {
			if (this.duration() === 0) {
				this.dismissible.set(true);
			}
		});
	}

	addToast(type?: string) {
		let payload = {children: `Simple toast ${this.index++}`, header: 'I am header'};
		if (type === 'error') {
			const errorProps = {className: 'text-bg-danger', dismissible: true, autoHide: true, delay: 10000};
			payload = {...payload, ...errorProps, header: ''};
		}
		this.toasterService.addToast(payload);
	}
}

// svelte/demo/src/bootstrap/samples/toast/Toaster.route.svelte
<script lang="ts">
	import {addToast, Toaster, defaultToasterProps, toastPositions} from '@agnos-ui/svelte-bootstrap/components/toast';
	const positions = Object.keys(toastPositions);
	let index = 0;
	const options = $state({...defaultToasterProps, limit: 10});
	$effect(() => {
		if (options.duration === 0) {
			options.dismissible = true;
		}
	});
</script>

<p class="mb-2">Similar to dynamic stacking, we expose a service to ease the usage of Toasts</p>
<div class="d-flex flex-column justify-content-between gap-2">
	<div class="d-flex flex-column flex-sm-row form-group align-items-center gap-3">
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="positionSelect">Position: </label>
			<select id="positionSelect" class="form-select w-auto" bind:value={options.position}>
				{#each positions as position}
					<option value={position}>{position}</option>
				{/each}
			</select>
		</div>
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="dismissible">Dismissible: </label>
			<input type="checkbox" class="form-check-input" id="dismissible" disabled={options.duration === 0} bind:checked={options.dismissible} />
		</div>
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="duration">Duration: </label>
			<input id="duration" type="number" class="form-control w-50" bind:value={options.duration} />
		</div>
	</div>
	<div class="d-flex flex-column flex-sm-row form-group align-items-center gap-3">
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="limit">Max # of toasts: </label>
			<input id="limit" type="number" class="form-control w-50" bind:value={options.limit} />
		</div>
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="pause">Pause timer on hover: </label>
			<input type="checkbox" class="form-check-input" id="pause" bind:checked={options.pauseOnHover} />
		</div>
		<div class="d-flex w-100 align-items-center justify-content-between">
			<label class="me-3" for="closeAll">Close all toasts button</label>
			<input type="checkbox" class="form-check-input" id="closeAll" bind:checked={options.closeAll} />
		</div>
	</div>
	<div class="d-flex form-group align-items-center gap-3 py-3">
		<button class="btn btn-primary ms-2" onclick={() => addToast({children: `Simple toast ${index++}`, header: 'I am header', className: 'mb-3'})}
			>Show toast</button
		>
		<button
			class="btn btn-primary ms-2"
			onclick={() =>
				addToast({children: `Simple toast ${index++}`, className: 'mb-3 text-bg-danger', dismissible: true, autoHide: true, delay: 10000})}
			>Show error toast</button
		>
	</div>
</div>

<div class="d-flex position-relative mt-2 w-100" style="height: 500px; background-color: gray;"></div>

<Toaster
	duration={options.duration}
	position={options.position}
	dismissible={options.dismissible}
	limit={options.limit}
	pauseOnHover={options.pauseOnHover}
	closeAll={options.closeAll}
/>
