// react/demo/src/bootstrap/samples/toast/Toaster.route.tsx
import {defaultToasterProps, ToastPositions, useToaster} from '@agnos-ui/react-bootstrap/services/toaster';
import {ToasterProvider} from '@agnos-ui/react-bootstrap/services/toaster';
import {useEffect, useState} from 'react';

const ToasterActions = () => {
	const toaster = useToaster();
	let [index, setIndex] = useState(0);
	return (
		<>
			<button
				className="btn btn-primary addToast ms-2"
				onClick={() => {
					toaster.addToast({children: `Simple toast ${index}`, header: 'I am header'});
					setIndex(++index);
				}}
			>
				Show toast
			</button>
			<button
				className="btn btn-primary addToast ms-2"
				onClick={() => {
					toaster.addToast({children: `Simple toast ${index}`, className: 'text-bg-danger', dismissible: true, autoHide: true, delay: 10000});
					setIndex(++index);
				}}
			>
				Show error toast
			</button>
		</>
	);
};

const ToasterDemo = () => {
	const positions = Object.entries(ToastPositions).map((entry) => {
		return {
			value: entry[1],
			label: entry[0],
		};
	});
	const [options, setOptions] = useState({...defaultToasterProps, pauseOnHover: false, closeAll: false, limit: 10});
	useEffect(() => {
		if (options.duration === 0) {
			setOptions((prevOptions) => ({...prevOptions, dismissible: true}));
		}
	}, [options.duration]);

	return (
		<ToasterProvider options={options}>
			<p className="mb-2">Similar to dynamic stacking, we expose a service to ease the usage of Toasts</p>
			<div className="d-flex flex-column justify-content-between gap-2">
				<div className="d-flex form-group align-items-center gap-3">
					<label className="me-3" htmlFor="positionSelect">
						Position:{' '}
					</label>
					<select
						id="positionSelect"
						className="form-select w-auto"
						value={options.position}
						onChange={(e) => setOptions({...options, position: e.target.value as ToastPositions})}
					>
						{positions.map(({value, label}) => (
							<option key={value} value={value}>
								{' '}
								{label}
							</option>
						))}
					</select>
					<label className="me-3" htmlFor="dismissible">
						Dismissible:{' '}
					</label>
					<input
						type="checkbox"
						className="form-check-input"
						id="dismissible"
						disabled={options.duration === 0}
						checked={options.dismissible}
						onChange={(e) => setOptions({...options, dismissible: e.target.checked})}
					/>
					<label className="me-3" htmlFor="duration">
						Duration:{' '}
					</label>
					<input
						id="duration"
						type="number"
						className="form-control w-auto"
						value={options.duration}
						onChange={(e) => setOptions({...options, duration: Number(e.target.value)})}
					/>
				</div>
				<div className="d-flex form-group align-items-center gap-3">
					<label className="me-3" htmlFor="limit">
						Max # of toasts:{' '}
					</label>
					<input
						id="limit"
						type="number"
						className="form-control w-auto"
						value={options.limit}
						onChange={(e) => setOptions({...options, limit: Number(e.target.value)})}
					/>
					<label className="me-3" htmlFor="pause">
						Pause timer on hover:{' '}
					</label>
					<input
						type="checkbox"
						className="form-check-input"
						id="pause"
						checked={options.pauseOnHover}
						onChange={(e) => setOptions({...options, pauseOnHover: e.target.checked})}
					/>
					<label className="me-3" htmlFor="closeAll">
						Close all toasts button
					</label>
					<input
						type="checkbox"
						className="form-check-input"
						id="closeAll"
						checked={options.closeAll}
						onChange={(e) => setOptions({...options, closeAll: e.target.checked})}
					/>
				</div>
				<div className="d-flex form-group align-items-center gap-3 py-3">
					<ToasterActions />
				</div>
			</div>
		</ToasterProvider>
	);
};

export default ToasterDemo;

// svelte/demo/src/bootstrap/samples/toast/Toaster.route.svelte
<script lang="ts">
	import {addToast, Toaster} from '@agnos-ui/svelte-bootstrap/components/toast';
	import {defaultToasterProps, ToastPositions} from '@agnos-ui/svelte-bootstrap/services/toaster';
	const positions = Object.entries(ToastPositions).map((entry) => {
		return {
			value: entry[1],
			label: entry[0],
		};
	});
	let index = 0;
	const options = $state({...defaultToasterProps, limit: 10});
	$effect(() => {
		if (options.duration === 0) {
			options.dismissible = true;
		}
	});
</script>

<p class="mb-2">Similar to dynamic stacking, we expose a service to ease the usage of Toasts</p>
<div class="d-flex flex-column justify-content-between gap-2">
	<div class="d-flex form-group align-items-center gap-3">
		<label class="me-3" for="positionSelect">Position: </label>
		<select id="positionSelect" class="form-select w-auto" bind:value={options.position}>
			{#each positions as { value, label }}
				<option {value}> {label}</option>
			{/each}
		</select>
		<label class="me-3" for="dismissible">Dismissible: </label>
		<input type="checkbox" class="form-check-input" id="dismissible" disabled={options.duration === 0} bind:checked={options.dismissible} />
		<label class="me-3" for="duration">Duration: </label>
		<input id="duration" type="number" class="form-control w-auto" bind:value={options.duration} />
	</div>
	<div class="d-flex form-group align-items-center gap-3">
		<label class="me-3" for="limit">Max # of toasts: </label>
		<input id="limit" type="number" class="form-control w-auto" bind:value={options.limit} />
		<label class="me-3" for="pause">Pause timer on hover: </label>
		<input type="checkbox" class="form-check-input" id="pause" bind:checked={options.pauseOnHover} />
		<label class="me-3" for="closeAll">Close all toasts button</label>
		<input type="checkbox" class="form-check-input" id="closeAll" bind:checked={options.closeAll} />
	</div>
	<div class="d-flex form-group align-items-center gap-3 py-3">
		<button class="btn btn-primary addToast ms-2" onclick={() => addToast({children: `Simple toast ${index++}`, header: 'I am header'})}
			>Show toast</button
		>
		<button
			class="btn btn-primary addToast ms-2"
			onclick={() => addToast({children: `Simple toast ${index++}`, className: 'text-bg-danger', dismissible: true, autoHide: true, delay: 10000})}
			>Show error toast</button
		>
	</div>
</div>

<Toaster
	duration={options.duration}
	position={options.position}
	dismissible={options.dismissible}
	limit={options.limit}
	pauseOnHover={options.pauseOnHover}
	closeAll={options.closeAll}
/>
